### PR TITLE
Bump docker SDK dependency

### LINKED ISSUE #4378: docker-compose ports range
Hello, I can use docker in next way:
**docker run -p 5001-5010:5000 registry:2**
Every time I run this command docker determines free port from defined range and publish it:
**CONTAINER ID IMAGE COMMAND PORTS
9cd40afd2ff5 registry "/entrypoint.sh /etc/" 0.0.0.0:5004->5000/tcp
1b7268e6d6ab registry "/entrypoint.sh /etc/" 0.0.0.0:5003->5000/tcp
2b1568c7ad57 registry "/entrypoint.sh /etc/" 0.0.0.0:5002->5000/tcp
e709fae805d1 registry "/entrypoint.sh /etc/" 0.0.0.0:5001->5000/tcp**

But, I am not able to simulate the same behavior with docker-compose... Having docker-compose.yml:
**version: '2'
   services:
      registry:
         image: registry:latest
         ports:
            - "5001-5010:5000"**
I receive error:
**services.registry.ports is invalid: Port ranges don't match in length.**

Please advise.

**docker version**:
Client:
Version: 1.12.6
API version: 1.24
Go version: go1.6.4
Git commit: 78d1802
Built: Wed Jan 11 00:23:16 2017
OS/Arch: windows/amd64

Server:
Version: 1.12.6
API version: 1.24
Go version: go1.6.4
Git commit: 78d1802
Built: Wed Jan 11 00:23:16 2017
OS/Arch: linux/amd64

**docker info**:
Containers: 4
Running: 4
Paused: 0
Stopped: 0
Images: 30
Server Version: 1.12.6
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 103
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.821 GiB
Name: moby
ID: MODJ:FE2K:YQY3:ERZJ:4UIL:ZT4G:LTF6:C4B7:WR7E:HGCG:ZOX5:BYC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://bla-bla:8080
Https Proxy: http://bla-bla:8080
No Proxy: 127.0.0.1,localhost,bla-bla
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
127.0.0.0/8

**docker-compose --version**:
docker-compose version 1.9.0, build 2585387

### LINKED ISSUE #4525: compose does not make use of config.json for "events" daemon command.
Due to https://github.com/docker/docker-py/issues/1472, compose 1.11.1 is unable to propagate the HttpHeaders from config.json on "events" commands. 

Compose looks for containers events when performing "docker-compose up".

### PR DESCRIPTION
**Pull request by shin-**
Fixes #4378 
Fixes #4525

### CODE REVIEW

**Comment by shin-** [comment]
On hold until we release docker-py 2.2.1, because of https://github.com/docker/docker-py/issues/1523

**Comment by thaJeztah** [comment]
@shin- @dnephin @vdemeester we should call out in the docs that port ranges are not (yet) supported for services; https://docs.docker.com/compose/compose-file/#ports

```bash
$ docker service create -p 9090-9100:80 nginx:alpine
invalid argument "9090-9100:80" for p: invalid hostport binding (9090-9100) for port (80)
```

**Comment by gitstercode** [comment]
```
docker-compose up --scale nginx_rp=3 
ERROR: Invalid published port: 8080-8082
```

**Comment by guilbill** [comment]
Hello,
I'm working with docker-compose version 1.16.1, build 6d1ac21
The port range syntax p1-p2:p3 does not seems to work...  (ERROR: Invalid published port: 4200-4500)
Here is a sample docker-compose.yml which reproduce the error :
```
version: '3.3'
services:
  nginx:
    image: nginx
    ports:
    - 4200-4500:80
```
docker-compose version : 1.16.1, build 6d1ac21
docker version : 17.06.0-ce

Am I missing something? or should we re-open an issue?

**Pull request merged**
