### PR TITLE
Remove one-off containers in `rm` and `down`

### PR DESCRIPTION
**Pull request by aanand**
- Carry #3141 
- Address https://github.com/docker/compose/pull/3141#discussion_r56531097
- Warn when `--all` is not passed to `rm`
- Remove one-off containers in `down`

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
Bit confused by the test failure, which I can't reproduce locally:

```
____________________________ ServiceTest.test_tmpfs ____________________________
tests/integration/service_test.py:881: in test_tmpfs
    container = create_and_start_container(service)
tests/integration/service_test.py:35: in create_and_start_container
    container = service.create_container(**override_options)
compose/service.py:269: in create_container
    previous_container=previous_container,
compose/service.py:634: in _get_container_create_options
    one_off=one_off)
compose/service.py:671: in _get_container_host_config
    tmpfs=options.get('tmpfs'),
.tox/py34/lib/python3.4/site-packages/docker/api/container.py:141: in create_host_config
    return utils.create_host_config(*args, **kwargs)
.tox/py34/lib/python3.4/site-packages/docker/utils/utils.py:785: in create_host_config
    raise host_config_version_error('tmpfs', '1.22')
E   docker.errors.InvalidVersion: tmpfs param is not supported in API versions < 1.22
```

**Comment by aanand** [comment]
Just realised `down` still doesn't clean up still-running one-off containers. Working on a fix now.

**Comment by dnephin** [comment]
I think this test is missing a skip for the Docker 1.9, I'll prepare a fix.

**Comment by aanand** [comment]
Pushed fix for still-running one-off containers

**Comment by dnephin** [comment]
Fix for the test failure: #3179 
LGTM

**Comment by shin-** [comment]
LGTM!

**Pull request merged**
