### PR TITLE
Touchup "Extending services in Compose"

### PR DESCRIPTION
**Pull request by charleswhchan**
(The rendered version, if it's easier for review: 
https://github.com/charleswhchan/compose/blob/patch-2/docs/extends.md)

### CODE REVIEW

**Comment by aanand** [comment]
Thanks for the contribution!

In my opinion, this guide is going to need to change significantly as a result of #2051, since the process of configuring an app for multiple environments should now be simplified. Perhaps we should incorporate some of these changes when revising it.

**Comment by dnephin** [comment]
Ya, I'm about to start working on #2141 which will make significant changes to this section.

I'll cherry-pick this commit first and try and preserve some of the edits.

**Comment by charleswhchan** [comment]
Thanks @dnephin.

**Comment by dnephin** [comment]
The new version is out.  I tried to incorporate some of these changes.  It did change pretty drastically, so I wasn't able to apply the cherry-pick, but hopefully the new version is better.

Thanks again for the PR!

**Pull request closed without merging**
