### PR TITLE
Ability to set "privileged" flag (boolean) from environment var

### PR DESCRIPTION
**Pull request by snowsky**

### CODE REVIEW

**Comment by shin-** [comment]
Thank you for your contribution! Code looks good at first glance. Do you mind squashing your commits into a single one?

Fixes #4028

**Comment by snowsky** [comment]
Build failed but not related to the change. Probably it is Jenkins slave issue.

**Comment by snowsky** [comment]
@shin- you know why this failed, https://jenkins.dockerproject.org/job/Compose-PRs/3387/console?

**Comment by snowsky** [comment]
Apparently, it was aborted. How could it be aborted by some one else? not getting it.

**Pull request closed without merging**
