### PR TITLE
Fix a typo (dsb -> dab)

### PR DESCRIPTION
**Pull request by sctlee**

### CODE REVIEW

**Comment by albers** [comment]
I think this PR is incorrect: docker-composer 1.8.0-rc1 actually writes a `dsb` file.

```bash
$ docker-compose --version
docker-compose version 1.8.0-rc1, build 9bf6bc6
$ docker-compose bundle
Wrote bundle to wpad.dsb
```

Or was this changed after RC1?

**Comment by yank1** [comment]
To see https://github.com/docker/docker/issues/23791.

LGTM

**Comment by albers** [comment]
I see. So the code will be adjusted as well to reflect this change?

**Comment by sctlee** [comment]
Yes, I think so.

**Comment by aanand** [comment]
Whoops, sorry - I just opened https://github.com/docker/compose/pull/3638 to do the same thing.

You can either update this PR so it includes the extra change I made ("Docker bundle" -> "Distributed Application Bundle") or just close it. Up to you!

**Comment by sctlee** [comment]
No worries. I will close it, since you have done more precise modification.

**Pull request closed without merging**
