### PR TITLE
Fix the maintainers array in MAINTAINERS

### PR DESCRIPTION
**Pull request by rumpl**
**What I did**

Fixed the maintainers TOML file

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Love the (very meta) "uploading image" caption for the ("not yet uploaded") image

Screenshot 2021-11-02 at 22 48 25

**Comment by rumpl** [comment]
> Love the (very meta) "uploading image" caption for the ("not yet uploaded") image
> 
> Screenshot 2021-11-02 at 22 48 25

Haha yes, my internet is really bad and can't even upload a nice image :D

**Comment by rumpl** [comment]
> Love the (very meta) "uploading image" caption for the ("not yet uploaded") image

Fixed

**Comment by thaJeztah** [comment]
> Fixed!

upload-patch

**Review by mat007 — APPROVED** [review]

**Pull request merged**
