### PR TITLE
Fix -d description

### LINKED ISSUE #1582: Daemon vs detached terms in docker-compose
Port https://github.com/docker/docs-base/issues/43 to here.

Here: http://docs.docker.com/compose/
image

it says "daemon mode" to the -d flag.

in the cli reference it refers to it as "detached mode":

image

image
I believe the correct and accurate one is "detached mode".

 ping @ahmetalpbalkan original reporter

### PR DESCRIPTION
**Pull request by aanand**
Closes #1582

### CODE REVIEW

**Comment by aanand** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM

**Comment by aanand** [comment]
Cherry-picked into the `docs` branch

**Comment by moxiegirl** [comment]
@aanand I'm doing a push this morning for DTR so you should se this live shortly.

**Pull request merged**
