### PR TITLE
Add support to push images quietly via compose cli 🤫

### PR DESCRIPTION
**Pull request by KoditkarVedant**
**What I did**
Add support to docker compose push --quiet option.

**Related issue**
#9089 

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by KoditkarVedant** [comment]
@n-rodriguez this has been delayed for long time. I need to get my local setup up and running again. I will spend some time over the weekend.

**Comment by KoditkarVedant** [comment]
@ulyssessouza @ndeloof I have resolved the merge conflicts. There are few e2e tests failing locally but when I tried to see if that is because of my changes I tried them on `v2` branch and they still fails. So, I'm bit confused what should I do. I don't want to delay this branch from merging as it already been procrastinated for long. I need you guys help to get this across the line.

**Comment by KoditkarVedant** [comment]
@laurazard would it be possible for you to have a look at this PR?

**Comment by KoditkarVedant** [comment]
@laurazard need little help to get this over the line.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by KoditkarVedant** [comment]
I am not sure - if team is getting time to look after this PR.

**Comment by nicksieger** [comment]
@KoditkarVedant can you please try updating your branch one more time and I'll make sure CI runs cleanly.

**Comment by KoditkarVedant** [comment]
@nicksieger I have updated my branch.

**Comment by KoditkarVedant** [comment]
@nicksieger I tried to run `make docs` on my local machine but it was failing. Would it be possible for you to look into this?

**Review by nicksieger — APPROVED** [review]
LGTM

**Pull request merged**
