### PR TITLE
Add documentation about installing a pre-release version of fig

### PR DESCRIPTION
**Pull request by dnephin**
Requested in https://github.com/docker/fig/issues/729#issuecomment-66886839 and seems to be a common enough case

### CODE REVIEW

**Comment by bfirsh** [comment]
Not sure we should recommend this in the docs. Perhaps as part of the contributing docs in the repo?

**Comment by dnephin** [comment]
This had come up a bunch because there was a pretty big gap between releases. If docker-compose is on a consistent release schedule now it's probably less necessary to mention it. 

Will close this for now.

**Comment by thaJeztah** [comment]
@dnephin perhaps https://github.com/docker/compose/pull/730#issuecomment-66888530 could still be considered? It's especially handy for support issues ("could you download the latest master and try with that?")

**Comment by dnephin** [comment]
I like that idea (setting up automated nightly builds), but I'm not really in a position to implement it.

@aanand with the work you're doing to get the build on jenkins, would it be possible/easy to set that up?

**Comment by thaJeztah** [comment]
@dnephin want me to open a new ticket for that, to discus options?

**Comment by dnephin** [comment]
Sure, sounds good!

**Comment by thaJeztah** [comment]
Done, see #1070

**Pull request closed without merging**
