### PR TITLE
Add commit to run command

### PR DESCRIPTION
**Pull request by madwire**
Added a commit option on the run command, this will help to improve productivity with various package manages. For example if Im building a rails app and I would like to change/update a dependancy. I would have to rebuild the docker image every time which can take some time. If after the run command it could commit the changes made to the docker image then it would save a load of time.

Also see #1168 

Signed-off-by: Richard Adams <richard@madwire.co.uk>

### CODE REVIEW

**Comment by dnephin** [comment]
I don't think this is going to work. The container is discarded and recreated on the next `up`, so that commit isn't going to really do anything.

More generally I don't think this really belongs in compose. It doesn't really have anything to do with composition. If you're just iterating on a `Dockerfile` you can do that just the default docker cli.

In general I think commit is only used in rare situations where you don't care about repeatable builds, usually you want to rebuild the container.

There are some other ways to work around the problem you describe. Best practice is to group all your `apt-get install` all together in a single line, but while developing the container you can just keeping adding new `RUN` lines. That way all your previous installs are cached, and you don't have to wait for them again.  At the end when you're done you can just merge them together into a single `RUN` line.

Another option is to use http://jpetazzo.github.io/2014/06/17/transparent-squid-proxy-docker/ to cache the downloads, which saves a bunch of time.

**Comment by madwire** [comment]
@dnephin Sorry I want to make it clear this is not to be used for OS packages, Just for application dependencies manages like Bundler, NPM, Pip etc.

I do agree with you that in most cases this should not be the way to go. But some dependency manages create lock files after you have ran them and a quick commit of the installed files and lock file does speed things up. The lock files are also synced back to the end users app directory so this is repeatable.

As for a proxy cache that only works for packages that have already been compiled or don't need to be, which is not the case for all.

In general you would only use it in rare situations yes, but it doesn't mean it doesn't have a place.

**Comment by sorby69** [comment]
+1

**Comment by aanand** [comment]
:-1: The problem you describe is a real and annoying one, but I don't want to encourage non-repeatable practices like this.

**Comment by madwire** [comment]
@aanand Sorry I may be missing the bigger picture, could you elaborate on what you mean by non-repeatable?

I've been using a bash script equivalent for about a month and only on running bundle update and it works great. Fast, reliable and repeatable.

**Comment by DVG** [comment]
:+1: This is one of the big pain points in using docker/compose for a developing application where application-level dependencies (things that don't go in a Dockerfile) change frequently. It can take 5-10 minutes to do a bundle install from scratch for a Rails project, versus a few seconds to just install the new gemdependency. Being able to quickly automate things like that would be a big plus in favor of docker as a development environment.

**Comment by dnephin** [comment]
You can always use volumes during development to handle  the changing of dependencies.

**Comment by dnephin** [comment]
Thanks for the contribution! Unfortunately this is not something we want to include in compose.

Committing the result of a run command is not a repeatable process (there are too many external factors which can't be accounted for). There are already a few options for dealing with the problem this intends to fix:

* use a cache to reduce download time
* optimize the install process (https://github.com/Yelp/venv-update and http://pythonwheels.com/ are both good options for python. Unfortunately I don't know enough about ruby to suggest options)
* build as part of a "builder" container that uses a host volume mount, produce a tarball, then add the tarball to the image (https://github.com/openshift/source-to-image describes that pattern). This is very similar to what you're doing with commit, but it's more explicit about what is happening.
* use a volume mount for the source in development (where the dependencies change frequently), and use an `ADD` for CI/CD (where they don't change nearly as often).

**Pull request closed without merging**
