### PR TITLE
Feature/env

### PR DESCRIPTION
**Pull request by SkinyMonkey**
This feature allow you to use environment variables in the fig.yml file.
It simply expand any found environment variable (ex: $HOST) to the value defined in the environment running fig.

useful example : 

I'm using Skydock (https://github.com/crosbymichael/skydock) along with skydns.

When i launch a skydns container by hand I need to specify the ip of the docker0 interface so that docker inject a new nameserver into /etc/resolv.conf:

ex:

Here the ip is "172.17.42.1"

`docker run -d -dns 172.17.42.1 -p 172.17.42.1:53:53/udp -name skydns crosbymichael/skydns -nameserver 8.8.8.8:53 -domain docker`

A nice way to be more flexible, compute what is the address automatically for example, is to add an environment variable in the equation : 

`env DNS_IP=172.17.42.1 docker run -d -dns $DNS_IP -p $DNS_IP:53:53/udp -name skydns crosbymichael/skydns -nameserver 8.8.8.8:53 -domain docker`

Wouldn't it be nice to be able to do the same thing in a fig.yml file? 

ex:

`env DNS_IP=172.17.42.1 fig up`

with this fig.yml:

```
skydns:
    image: crosbymichael/skydns
    ports:
        - $DNS_IP:53:53/udp
        - 8080:8080
    dns:
        - $DNS_IP
    command: "-nameserver 8.8.8.8:53 -domain docker"
```

I wanted to add a flag to make this expansion optional, just in case. What do you think?

### CODE REVIEW

**Comment by Stono** [comment]
+1

**Comment by pongo710** [comment]
+1

**Comment by hadim** [comment]
Any news here ?

**Comment by relwell** [comment]
Please refer to #845 for the implementation as outlined by some of the repo admins, as discussed in #495

**Comment by muddydixon** [comment]
+1

**Comment by hamiltont** [comment]
+1

**Comment by ysaotome** [comment]
+1

**Comment by ajmath** [comment]
+1 Would like to use this to pass in AWS credentials into containers

**Comment by dnephin** [comment]
#1488 will be in the next release, which will let you do something like this if you wanted to:

```bash
cat docker-compose.yml | python -c "import os, sys; os.path.expandvars(sys.stdin.read())" | docker-compose up -f -
```

Which can be aliased as `dc` or put into a script along with the project.

I think it's still work calling out that this can easily break the yaml syntax, so should be used with caution.

**Comment by griwes** [comment]
This is a non-solution, @dnephin. Heck, it might even be an unsolution.

When invoking `docker run` yourself, you have an option to specify important parameters with (shell expanded) env variables... like the IP to expose ports to, which in most cases can't be statically embedded in the .yml file. So, while this might be an extremely specific thing, the one *absolutely crucial* feature is a way to reference an IP of an interface in Compose's .yml file.

Wrapping an invocation of a tool with something like the above basically means the tool in question sucks majorly.

**Comment by albers** [comment]
I agree that the need to interpolate IP addresses in a Compose file is a legal request that is insufficiently addressed by this solution.

The suggested solution is only a minor improvement to command substitution which was possible before:

```
IP=1.2.3.4
docker-compose -f <(sed "s/IP/$IP/" docker-compose.yml) -p projectname ps
```

**Comment by dnephin** [comment]
@albers that's true, 

#1377 is still tracking a more robust solution for this problem

**Comment by jayfk** [comment]
I totally agree with @griwes, this looks like an unsolution.

**Comment by dnephin** [comment]
This is done in #1765

**Pull request closed without merging**
