### PR TITLE
Add support for network priority

### LINKED ISSUE #5042: Cannot determine which port mapping should apply to which network
I've been struggling with an issue while trying to document Compose support for a three tier app using two networks in vSphere Integrated Containers. Our documentation really needed improving and as part of that work, I'm putting together guidelines on how to get the best out of both technologies.

The issue I have is that for a container that uses multiple networks, the order in which they're brought up matters. For example, when using a docker client, I would do the following:

```
docker network create internal
docker create -d --name web --net external -p 80 myImage
docker network connect internal web
docker start web
```
In the above example, I'm asking for port 80 to be exposed on the external network. If I flip it around, instead I get a port mapping on the bridge network.

```
docker network create internal
docker create -d --name web --net internal -p 80 myImage
docker network connect external web
docker start web
```
docker-compose seems to always use the same order, regardless of how the compose file is written - creating the container with the internal network and then adding the external network before starting it.

My question is: Is there any way to influence this ordering? The current compose file format leave it somewhat ambiguous - it allows you to expose ports and specify multiple networks, but there's no way to determine which ports are exposed on which networks. 

Any help in resolving this would be appreciated. Thanks!

### LINKED ISSUE #5261: docker-compose and mac_address only uses mac_address on one network
I have the following compose-file:

```
version: '3.2'
services:
  wordpress:
    image: wordpress:4.7
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpressuser
      - WORDPRESS_DB_PASSWORD=change_this_db_password
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - html_data:/var/www/html
    links:
      - db:mysql
    ports:
      - "80:80"
    hostname: wordpress
    domainname: wordpress.local
    mac_address: 8a:ca:58:b9:e9:51
    networks:
      - front
      - back

  db:
    image: mariadb:10.1.13
    environment:
      - MYSQL_ROOT_PASSWORD=change_this_root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpressuser
      - MYSQL_PASSWORD=change_this_db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back

volumes:
  html_data:
  mysql_data:

networks:
  front:
    external:
      name: qnet-dhcp-eth1
  # front:
  #   driver: qnet
  #   ipam:
  #     driver: qnet
  #     options: 
  #       iface: eth1
  back:
    driver: bridge
    internal: true
    ipam:
      driver: default
```

The container wordpress has two networks front and back.  The front one is external I create with the following command before runnning docker-compose up: docker network create -d qnet --ipam-driver=qnet --ipam-opt=iface=eth1 qnet-dhcp-eth1

The problem I have is the mac_address is set properly on the "back" network - but not the "front" network (which is where I really need to set it!)

Here is what I get from docker inspect:
```
            "MacAddress": "8a:ca:58:b9:e9:51",
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "63a0b882bab0b519128a2d5c89f34638ec5842a5010581e909b106a2d31c86c3",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "wordpress",
                "com.docker.compose.service": "wordpress",
                "com.docker.compose.version": "1.16.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0d52789a1a1b987632e64bff6912fb49b9f19e07d070e5a24e975772d6679f56",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/0d52789a1a1b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "qnet-dhcp-eth1": {
                    "IPAMConfig": null,
                    "Links": [
                        "wordpress_db_1:db_1",
                        "wordpress_db_1:mysql",
                        "wordpress_db_1:wordpress_db_1"
                    ],
                    "Aliases": [
                        "fc7182429e1f",
                        "wordpress"
                    ],
                    "NetworkID": "c4f4713f933d8a6a6d3a623b5502ff80a42d0e6581ca8ec9260d35831b1ebff0",
                    "EndpointID": "67a4665e3b505835a0cac76272ea4b0903ee735b43eca4ef6e13abfc10829740",
                    "Gateway": "192.168.2.1",
                    "IPAddress": "192.168.2.60",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:e9:f5:17:12"
                },
                "wordpress_back": {
                    "IPAMConfig": null,
                    "Links": [
                        "wordpress_db_1:db_1",
                        "wordpress_db_1:mysql",
                        "wordpress_db_1:wordpress_db_1"
                    ],
                    "Aliases": [
                        "fc7182429e1f",
                        "wordpress"
                    ],
                    "NetworkID": "b48d420567c210afe71274313517997f78fe611fe16f8510420649c71bc0650a",
                    "EndpointID": "f2d166caf02103b8c1502589b31772e3d195b9a758b32e833aa7a89c9ecdefaf",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "8a:ca:58:b9:e9:51"
                }
            }
```

So why is the mac_address used for the "back" network but not the "front" network?

### PR DESCRIPTION
**Pull request by shin-**
Fixes #5042 
Fixes #5261 

Based on #5474

### CODE REVIEW

**Comment by salanki** [comment]
Did this actually make it into a release?
```
version: '3.5'

networks:
  public:
    # Use a custom driver which takes special options
    driver: bridge
    priority: 100
```
```
docker-compose -f common-compose.yml up -d parity
ERROR: The Compose file './common-compose.yml' is invalid because:
networks.public value Additional properties are not allowed ('priority' was unexpected)
```

**Comment by shin-** [comment]
@salanki Yes, but it's not in v3 of the Compose file and you're setting it [in the wrong place](https://docs.docker.com/compose/compose-file/compose-file-v2/#priority).

**Comment by Ape** [comment]
@shin- Is there any plans to add this to Compose file v3?

**Comment by jacekchalupka** [comment]
@shin- As asked above. Is there any plans to add this to Compose file v3?

**Comment by Webdown404** [comment]
@shin- As asked above and beyond. :)

**Comment by dubisoft-solutions** [comment]
it does not work for me.. probably I am doing something wrong, so I have the following networks config


```
networks:
    rtpdaznetv4:
        enable_ipv6: false
        name: rtpdaz_primary
    rtpdaznetv6:
        enable_ipv6: true
        name: rtpdaz_secondary
        ipam:
            config:
                - subnet: "fd12:3456:789a:1::/64"
```

service level looks like this:

```
      networks:
            rtpdaznetv4:
                priority: 1000
            rtpdaznetv6:
                priority: 100
```

and now when i run the container and do ifconfig, I see this:

```
root@364ad5ae0d1d:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.24.32.2  netmask 255.255.255.0  broadcast 172.24.32.255
        inet6 fe80::42:acff:fe18:2002  prefixlen 64  scopeid 0x20<link>
        inet6 fd12:3456:789a:1::2  prefixlen 64  scopeid 0x0<global>
        ether 02:42:ac:18:20:02  txqueuelen 0  (Ethernet)
        RX packets 77  bytes 256594 (250.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60  bytes 4365 (4.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.24.33.2  netmask 255.255.255.0  broadcast 172.24.33.255
        ether 02:42:ac:18:21:02  txqueuelen 0  (Ethernet)
        RX packets 13  bytes 1546 (1.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6  bytes 510 (510.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 510 (510.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

as you can see, eth0 has ipv6, so it is rtpdaznetv6 network, which should be the second one according to priority

**Pull request merged**
