### PR TITLE
Support links in v2 files

### PR DESCRIPTION
**Pull request by aanand**
TODO:

- [x] Merge https://github.com/docker/docker-py/pull/901 and update `requirements.txt`
- [x] Update docs

### CODE REVIEW

**Comment by aanand** [comment]
AppVeyor build is failing because of `requirements.txt`, janky failures look unrelated.

**Comment by dnephin** [comment]
For appveyor , I think we just need to move the `$ErrorActionPreference = "Continue"` above the pip install lines.  The stderr is  causing the failure.

**Comment by aanand** [comment]
Build is green. Docs updated in https://github.com/docker/compose/pull/2699.

**Comment by shin-** [comment]
LGTM :+1:

**Comment by aanand** [comment]
Cherry-picked into #2753

**Pull request merged**
