### PR TITLE
WIP: `labels` option in docker-compose.yml

### PR DESCRIPTION
**Pull request by aanand**
```yaml
labels:
  com.example.description: "Accounting webapp"
  com.example.department: "Finance"
```

```yaml
labels:
  - "com.example.description=Accounting webapp"
  - "com.example.department=Finance"
```

This is WIP for two reasons:

1. It tests against a development version of Docker which is just bundled in the repo. Not nice.
2. It uses an unreleased docker-py implementation of labels (https://github.com/docker/docker-py/pull/532).

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm still in preference of the first notation (a dict). I realise an array more closely matches the way ENV-vars are currently implemented, but a dict makes it more verbose that label names (keys) are unique. In addition, I can imagine a dict will be easier to handle, e.g., when merging labels from various sources (yaml, CLI, label-file), but that's a lesser concern.

**Comment by aanand** [comment]
@thaJeztah I also prefer the dict form, and I feel the same way about environment variables too - but for consistency between the two features, and between Compose and the Docker CLI, I think it's important to support both.

Both env vars and labels are normalised to a dictionary when we read them, so it's purely cosmetic.

**Comment by thaJeztah** [comment]
@aanand no problem! Just emphasising the "dict" approach in the documentation should do :)

**Comment by dnephin** [comment]
I like it

**Comment by aanand** [comment]
I've force-unmerged this, since the docker binary is kind of big and we don't want to make everyone who clones docker/compose download it. Will re-merge it once #1144 is addressed.

**Pull request merged**
