### PR TITLE
Properly escape values coming from env_files, fixes #6871

### LINKED ISSUE #6871: [bug] `config --no-interpolate` returns wrong results
## Description of the issue

docker-compose 1.25 introduces a `--no-interpolate` command to the `config` subcommand. I would expect that `docker-compose config` and `docker-compose config --no-interpolate > new_compose.yml && docker-compose -f new_compose.yml config` return the same output. Sadly they dont.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0-rc2, build 661ac20e
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:20:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

Assume the following compose file:

```
version: "2.4"

services:
  whoami:
    image: ubuntu
    command: sleep infinity
    env_file: data.env
    environment:
      IN_COMPOSE: ${IN_COMPOSE}
```
and the `data.env`:
```
IN_ENV_FILE=$THIS_SHOULDNT_BE_A_VAR
```
Now `docker-compose config` correctly returns:
```
WARNING: The IN_COMPOSE variable is not set. Defaulting to a blank string.
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ''
      IN_ENV_FILE: $$THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'
```
As you can see `$THIS_SHOULDNT_BE_A_VAR` is escaped correctly.
Now if you run the following sequence:
```
docker-compose config --no-interpolate > new_compose.yml
docker-compose -f new_compose.yml config
```
you will get:
```
WARNING: The IN_COMPOSE variable is not set. Defaulting to a blank string.
WARNING: The THIS_SHOULDNT_BE_A_VAR variable is not set. Defaulting to a blank string.
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ''
      IN_ENV_FILE: ''
    image: ubuntu
version: '2.4'
```
Now all of a sudden, `$THIS_SHOULDNT_BE_A_VAR` got evaluated. The cause can be seen when viewing the intermediate file:
```
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ${IN_COMPOSE}
      IN_ENV_FILE: $THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'
```
I think `docker-compose config --no-interpolate` should replace `$` with `$$` for environment variables coming from env files.

### PR DESCRIPTION
**Pull request by apollo13**
Resolves #6871

### CODE REVIEW

**Comment by apollo13** [comment]
Hi @xificurC, since you wrote the original implementation of `config --no-interpolate` might I get your thoughts on this PR?

Is there any chance we could get this into 1.25 @ijc? I am asking because basically it is a bug in a new feature and it would be great if we could fix this now.

**Comment by xificurC** [comment]
Hi @apollo13 ,

I'm sorry you had trouble with this new feature. Unfortunately I didn't know of the environment file feature, therefore I didn't account for it when creating the PR. As noted in #6367 my wish was for `config` to be idempotent. So these should all behave identically:

```zsh
function run() { docker-compose up }
function config() { docker-compose config --no-interpolate }

up
config | up
config | config | up
config | config | config | up
```

(I'm not sure if compose can read from stdin but you get the idea)

If this PR works as I just described than that's in line with my expectations.

Either way this is a bug, thank you for fixing it!

**Comment by apollo13** [comment]
> As noted in #6367 my wish was for `config` to be idempotent. So these should all behave identically

Yes, my PR ensure that this even is the case when `env_file` is used

> (I'm not sure if compose can read from stdin but you get the idea)

Yes it can with `docker-compose -f -`

> If this PR works as I just described than that's in line with my expectations.

Perfect, yes it does, see the following shell output for an example:
```
➜  data git:(master) ✗ cat docker-compose.yml 
version: "2.4"

services:
  whoami:
    image: ubuntu
    command: sleep infinity
    env_file: data.env
    environment:
      IN_COMPOSE: ${IN_COMPOSE}
➜  data git:(master) ✗ export IN_COMPOSE=42  
➜  data git:(master) ✗ docker-compose config                                                                                        
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: '42'
      IN_ENV_FILE: $$THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'

➜  data git:(master) ✗ docker-compose config --no-interpolate|docker-compose -f - config --no-interpolate|docker-compose -f - config
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: '42'
      IN_ENV_FILE: $$THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'
```

**Comment by xificurC** [comment]
Great, thank you!

**Comment by apollo13** [comment]
@ulyssessouza Would it be possible that you take a look at this. It would fix a bug (#6871) in `docker-compose config --no-interpolate` which sadly made it into 2.25 :(

**Comment by ulyssessouza** [comment]
Please, just rebase to resolve the conflicts.

**Comment by apollo13** [comment]
@ulyssessouza You added python-dotenv 12 days ago which now replaces environment variables in env files at this stage already: https://github.com/docker/compose/commit/6d2658ea65bc01655d0615bdb8d023e1982ca681#diff-f13c4e730aafa68fe2cff763b49ece6aR42 :( 

This seems to be a massive change in behaviour and also prevents my patch from being rebasable. Is the goal now that env files are recursively expanded? The docs cleary state in https://docs.docker.com/compose/compose-file/#env_file : 
```
The value of VAL is used as is and not modified at all. For example if the value is surrounded by quotes (as is often the case of shell variables), the quotes are included in the value passed to Compose.
```

**Comment by apollo13** [comment]
Also the documentation for the default `.env` links to https://docs.docker.com/compose/env-file/ which states: 
> There is no special handling of quotation marks. This means that they are part of the VAL.

**Comment by apollo13** [comment]
@ulyssessouza FWIW, I fully understand the desire to get the reading of the `.env` file in line with how other tools operate. But this change will most likely break any compose file using `env_file` which by accident already contains ${X} for instance.

**Comment by apollo13** [comment]
I have force pushed a commit which contains a TODO that was broken by the introduction of python-dotenv as well as a test which now fails.

In the end I could also add tests against master with no code changes at all that show how documented behaviour is now broken. Not sure how to proceed :/

**Comment by ulyssessouza** [comment]
I'm having a look. Probably needs a change in `python-dotenv` to avoid interpolation on their side too.

**Comment by ulyssessouza** [comment]
@apollo13  I've just opened a [PR](https://github.com/theskumar/python-dotenv/pull/232) to add the `no-interpolation` on `python-dotenv` side too.

I also pushed a commit on your branch pointing to my personal fork using the missing part for now (I hope you don't mind :smiley_cat:)

**Comment by apollo13** [comment]
@ulyssessouza Thank you very much and feel free to push whatever you want into my branch, after all I checked "allow edits from maintainers" ;) Your changes look good so far!

**Comment by apollo13** [comment]
@ulyssessouza python-dotenv 0.11.0 is now released. I've updated the PR accordingly. Anything else you'd like me to do?

**Comment by apollo13** [comment]
@ulyssessouza Since python-dotenv 0.11 now made it into the master branch already, do you think you could merge this?

**Comment by ulyssessouza** [comment]
Thanks a lot @apollo13 !

**Comment by apollo13** [comment]
Thank you @ulyssessouza. Is there any policy with regards to backports? IE is there a way to get this into 1.26 or so?

**Comment by ulyssessouza** [comment]
That will probably make it's way to 1.26.0 since the RC made today was for a specific reason. The next one will be based on `master` again. But that's an exception

**Pull request merged**
