### PR TITLE
Close the open file handle using context manager

### PR DESCRIPTION
**Pull request by pts-kevinqiu**
Use context manager to close the open file handle automatically.

### CODE REVIEW

**Comment by pts-kevinqiu** [comment]
@shin- oops, I `rebase -i HEAD~n` one too many, and now the previous changeset is included in this PR. Do you know can I solve it?

**Comment by shin-** [comment]
@pts-kevinqiu I'd start a new branch off master and cherry-pick 00d4f77d838dbce850bc2ce65ad8ecaf98a0fdde into it.

**Comment by pts-kevinqiu** [comment]
@shin- ok will do.

**Comment by pts-kevinqiu** [comment]
@shin- Cherry-picked https://github.com/docker/compose/pull/4392/commits/a92404207deedaafe65a30e79f7cc34ebe965de5

**Comment by shin-** [comment]
Thanks! I merged via #4426 . Closing now :+1:

**Pull request closed without merging**
