### PR TITLE
add msg attribute to ProjectError class

### PR DESCRIPTION
**Pull request by anton44eg**
#3432

### CODE REVIEW

**Comment by shin-** [comment]
LGTM, thanks!

**Comment by aanand** [comment]
LGTM

**Comment by christianbundy** [comment]
We're currently dealing with #3432 and can't find any workaround, is there any way this code could be released as a patch for 1.7.1 before the 1.8.0 release date.

**Comment by shin-** [comment]
@christianbundy You should only see this error if something went wrong with your `up` command. Unless I'm mistaken, more details about should be printed in your console before the program hits that point. If you're still having trouble though, could you share the ouput of `docker-compose --verbose up`?

**Comment by christianbundy** [comment]
You're totally right, there was another error in the line above, I didn't realize that this was logging-specific (although by the error message, I probably could've figured that out). Thanks @shin-!

**Comment by 0xadada** [comment]
Heres my error
```
sudo docker-compose -f docker/django/dev/docker-compose.yml up -d
Recreating 278801807dbf_278801807dbf_278801807dbf_278801807dbf_dev_django_1

ERROR: for django  b'No such image: sha256:a7b3a3cbdd72294369068f78939d8f8a77f2fabc897ac76a6bc78057daa7cd55'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 58, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 109, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 734, in up
    remove_orphans=remove_orphans)
  File "/usr/lib/python3.5/site-packages/compose/project.py", line 402, in up
    'Encountered errors while bringing up the project.'
compose.project.ProjectError: Encountered errors while bringing up the project.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
```

**Comment by christianbundy** [comment]
@0xadada The `AttributeError: 'ProjectError' object has no attribute 'msg'` is just a symptom of the real error, which is:

> No such image: sha256:a7b3a3cbdd72294369068f78939d8f8a77f2fabc897ac76a6bc78057daa7cd55

If this is unexpected, it may be worth opening a new issue, but I don't think that you'll get the help you're looking for by commenting on this PR .

**Comment by richburdon** [comment]
Same issue (below). No idea what is referencing the missing image (build and start both succeed). My trivial docker-compose.yml

```
services:
  test_container:
    build:
      context: ./container
    volumes:
      - /usr/share

  test_client:
    build:
      context: ./client
    volumes_from:
      - service:test_container:ro
```


```
ERROR: for test_container  No such image: sha256:e90ea94405e53a2389b922bc5c7e47682f6e3ab57e0f7252efd362034de1e2b0
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.7.1/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
```

**Comment by shin-** [comment]
I replied in #3557. This specific PR has been merged in master and will be in the next release.

**Pull request merged**
