### PR TITLE
update `projectOptions` to be public by renaming it to `ProjectOptions`

### PR DESCRIPTION
**Pull request by tigerinus**
Signed-off-by: Tiger Wang <tigerwang@outlook.com>

**What I did**

- updated `projectOptions` to be public by renaming it to `ProjectOptions`
- updated `toProject(...)` method of `projectOptions` to be public by renaming it to `ToProject(...)`
- tested all impacted code to make sure they are passing 

**Related issue**

- #10102 

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

my cat

This is my cat - she never shows up and always hide herself somewhere in the house.

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]
LGTM

**Comment by tigerinus** [comment]
@ndeloof - how should I handle thie code coverage issue? The change is literally turning lower cases to upper cases.

Should I add unit tests for `ToProject` method that is now public?

**Review by laurazard — APPROVED** [review]
LGTM

**Comment by ndeloof** [comment]
I also had strange results from codecov, seems this one is buggy :P

**Pull request merged**
