### PR TITLE
Add --pull arg to "up" command

### PR DESCRIPTION
**Pull request by GabrielBB**
Ability to do: 

 `docker-compose -f my-docker-compose.yml up --pull` 

Instead of :

`docker-compose -f my-docker-compose.yml pull && docker-compose -f my-docker-compose.test.yml up`. 

Why:

- It's shorter

- Less prone to errors since you don't have to type the yml file name twice (Which means double chance for typos)

- It has better performance because `&&` throws away the asynchrony

- Makes the API more consistent since there is already a `--build` flag and one expect to be a `--pull` one.

One example without this flag that looks weird to me (maybe is just me) is this:

`docker-compose pull && docker-compose up --build`

There it looks like `pull` and `build` are two features with different degrees of importance, when in fact, they don't, the condition to do one thing or another is even in the same function in the code:

```
def ensure_image_exists(self, do_build=BuildAction.none, silent=False, cli=False):
        if self.can_be_built() and do_build == BuildAction.force:
            self.build(cli=cli)
            return

        try:
            self.image()
            return
        except NoSuchImageError:
            pass

        if not self.can_be_built():
            self.pull(silent=silent)
            return

        if do_build == BuildAction.skip:
            raise NeedsBuildError(self)

        self.build(cli=cli)

```

This looks a better fit:

`docker-compose up --build --pull`

I added unit tests and acceptance tests

### CODE REVIEW

**Comment by nojvek** [comment]
I really hope this still doesn't have the same problem as #3513.

It's really a pain to have to separate but almost identical docker-compose.yaml files.

Ideally I would love to see a single command `docker-compose restart/up --pull` that gets the latest built images and gracefully (re)starts all containers with the latest code.

**Comment by GabrielBB** [comment]
> I really hope this still doesn't have the same problem as #3513.

The pull arg will have the same “issues” as docker-compose pull. It calls the same code.

> Ideally I would love to see a single command `docker-compose restart/up --pull` that gets the latest built images and gracefully (re)starts all containers with the latest code.

That will be possible with this PR

**Comment by ndeloof** [comment]
I wonder it would make sense to introduce an equivalent for kubernetes `pull_strategy` so one can define on a per-service basis how to update images vs rebuild.

**Comment by thaJeztah** [comment]
it should at least not be a boolean, but preferably more like https://github.com/docker/cli/pull/1498

There's also the `--resolve-image` option includes `docker stack deploy`, which is slightly related

**Comment by tomaswarynyca** [comment]
Could you please review and approve this change that many of us need?
@ndeloof @rumpl @ulyssessouza

**Comment by tomaswarynyca** [comment]
@GabrielBB could you sign the commits properly and fix the conflicts?
https://github.com/docker/compose/pull/7213#issuecomment-581676830

**Comment by GabrielBB** [comment]
> @GabrielBB **[could you sign the commits properly](https://github.com/docker/compose/pull/7213#issuecomment-581676830) and fix the conflicts?**

@tomaswarynyca I messed by branch while trying to fix the commits signing. I had to open a new PR: https://github.com/docker/compose/pull/8328

**Pull request closed without merging**
