### PR TITLE
Clarify depends_on logic

### PR DESCRIPTION
**Pull request by aanand**
Closes https://github.com/docker/compose/issues/2868.

Is there a way to define custom anchors for sections on a doc page? That FAQ anchor title is *really* long.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM, I don't know of any way to set a custom anchor

**Comment by aanand** [comment]
I've done it with an `<a name="custom-anchor-name"></a>` tag, which seems to work. @SvenDowideit, @moxiegirl - does this look OK?

**Comment by aanand** [comment]
After discussing with @moxiegirl, I've moved the answer into its own document.

**Comment by dnephin** [comment]
LGTM

**Comment by moxiegirl** [comment]
I'd take the tics, for example `COPY/ADD`, out of the headings in the FAQ.md and squash.  Those are nits tho.

**Comment by aanand** [comment]
@moxiegirl I did those separately - see https://github.com/docker/compose/pull/3059.

**Pull request merged**
