### PR TITLE
Ubuntu: install latest release always addition

### PR DESCRIPTION
**Pull request by digitalist**
Signed-off-by: Aleksey Elymanov <“strangeqargo@gmail.com”>

### CODE REVIEW

**Comment by digitalist** [comment]
I removed `sudo` with dd, because `sudo` usage is described earlier

**Comment by aanand** [comment]
Thanks! Interesting idea, but I think it needs more consideration. If we're going to give people a command that always installs the latest version, we should arguably come up with one that works with less shell magic - e.g. by setting up stable 'latest' download URLs that redirect.

**Comment by digitalist** [comment]
@aanand  it's just Linux/ubuntu related code, so, I suppose it will work ok. 
Though your idea is better.
I guess, we can't patch documentation to get latest version without using JS, and JS browser dependency is not good for automation. 
So we must switch to server-side, is there some docker server-side code repository, or I should write someone to make this  "always stable" link script?

**Comment by shin-** [comment]
This should be moved to https://github.com/docker/docker.github.io where the docs have migrated!

**Pull request closed without merging**
