### PR TITLE
update readme file images

### LINKED ISSUE #10349: Badges are not consistent
Modify the badge which is displaying the URL to the issue related the shields.io repo but not the message.

### PR DESCRIPTION
**Pull request by hemanthkotaprolu**
**Fixed a broken broken badge URL and aligned images to look nice**

These are the changes i made:
- Modified the badge which is displaying the URL to the issue related the shields.io repo. 
- Positioned the badges to make them look nice
- Aligned the image to the cener to look nice.

I am not sure what to send as the message so i sent the the message as action, since on clicking it is opening the actions tab in the compose repo. Please let me know if there is any change and can close #10349

### CODE REVIEW

**Comment by ndeloof** [comment]
I'd prefer we avoid using html in markdown files.
I wonder we could just introduce a line break before logo

**Comment by hemanthkotaprolu** [comment]
- Please take a look at the picture. Markdown doesn't provide a way to style so this way by using html it is looking nice.
- We can add a horizontal line before logo as well. Let me add it as well.

docker_compose

**Comment by ndeloof** [comment]
> Markdown doesn't provide a way to style

yes, this is the intent: it is not designed to offer a candy-looking web site, but offer some readable documentation while keeping the source easy to edit and maintain.

**Comment by ndeloof** [comment]
Closing this as "won't fix" as README is not intended to be more than a plain markdown file

**Pull request closed without merging**
