### PR TITLE
Fix a typo in a test's name.

### PR DESCRIPTION
**Pull request by stakodiak**
Change 'priviliged' -> 'privileged'.

### CODE REVIEW

**Comment by bfirsh** [comment]
LGTM

**Comment by bfirsh** [comment]
To fix the dco-signed failure: `git rebase master; git push -f` or something along those lines.

**Comment by aanand** [comment]
Thanks - could you rebase and squash please?

**Comment by stakodiak** [comment]
Okay, I think this is all good now.

**Comment by aanand** [comment]
LGTM

**Pull request merged**
