### PR TITLE
Missing dependency on Ubuntu 16.04 #3525

### PR DESCRIPTION
**Pull request by dooman87**
* Updated install instruction.

### CODE REVIEW

**Comment by dnephin** [comment]
I don't think this is correct. If you're using the binary install you shouldn't need to install any other packages.

**Comment by kevinrood** [comment]
@dooman87 thank you for this update. I can confirm this helped me work around my setup issue on Ubuntu 16.04.

**Comment by dooman87** [comment]
@dnephin Sorry, what you mean by "shouldn't need to install any other packages"? In the documentation the first step is to install docker-engine which will install python and other packages. However, you still need to install that additional package on Ubuntu 16.04.

**Comment by dnephin** [comment]
I think the problem might be that our requirements.txt is not correct anymore, I'll submit a PR to fix that.

Are you install Compose by curling the binary, or are you using pip to install it?

**Comment by dooman87** [comment]
I used curl.

Cheers,
Dmitry

**Pull request closed without merging**
