### PR TITLE
bash completion for migrate_to_labels

### PR DESCRIPTION
**Pull request by albers**
Adds `migrate_to_labels` to the list of available commands.

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks again! LGTM

**Comment by aanand** [comment]
Thanks!

Could you update it now that it's `migrate-to-labels`? (#1442)

**Comment by albers** [comment]
Done! 
The dashes are definitely better.

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
