### PR TITLE
possiblity to override the client version 

### PR DESCRIPTION
**Pull request by httpPrincess**
it is not the best idea to hard code the version of the client. At least the possibility to override this should be provided.

### CODE REVIEW

**Comment by dnephin** [comment]
I think we should make this change, the only question is about what the environment variable should be called.  I believe @aanand has suggested `COMPOSE_CLIENT_VERSION`.

Please squash your changes into a single commit

**Comment by httpPrincess** [comment]
as you wished

**Comment by dnephin** [comment]
I'm not sure why that first commit from albers is showing up. I think that's already in master?

**Comment by httpPrincess** [comment]
I had some strange problems with squashing, perhaps this is the reason why i appears here.

**Comment by dnephin** [comment]
You should be able to rebase with master to get rid of it

**Comment by httpPrincess** [comment]
forget it.

**Pull request closed without merging**
