### PR TITLE
Remove Jenkinsfile used for docs CI

### PR DESCRIPTION
**Pull request by joaofnfernandes**
The documentation has been migrated to docker/docker.github.io, so I'm removing this Jenkins file that was running docs-related CI and can start breaking the builds.

Signed-off-by: Joao Fernandes joao.fernandes@docker.com

### CODE REVIEW

**Comment by dmp42** [comment]
@joaofnfernandes can you sign your commits?

**Comment by joaofnfernandes** [comment]
Now it should be signed.

**Comment by bfirsh** [comment]
@joaofnfernandes Needs rebasing now, sorry! (It might have already been fixed?)

**Comment by joaofnfernandes** [comment]
Closing this and waiting for @mikedougherty opinion, since he is cleaning up the Jenkinsfile in #4073

**Comment by mikedougherty** [comment]
Sure, that's easy enough. I'll put in a PR with docs removed.

**Pull request closed without merging**
