### PR TITLE
Allow requests 2.20.x for CVE fix

### PR DESCRIPTION
**Pull request by ofek**
In ~1 week `requests` will release `2.20.0` https://github.com/requests/requests/pull/4835

It would be excellent if, since we're about to release, `1.23` included support for that, especially since it will address a rather important CVE https://github.com/requests/requests/pull/4836

@shin- I'm quite sorry to bother again, but do you think we can do this? That security fix is rather critical to some of us 🙏

### CODE REVIEW

**Comment by ofek** [comment]
`2.20.x` has been released

**Comment by ofek** [comment]
@shin- I'm not sure how our release process works. Can this still get in `1.23`?

**Comment by shin-** [comment]
@ofek Seems important enough to warrant including in 1.23. Do you mind rebasing against current master to clear the flake8 errors?

**Comment by ofek** [comment]
I rebased and everything is passing now!

**Comment by ofek** [comment]
@shin- You're the absolute best; thank you so much!

**Pull request merged**
