### PR TITLE
Upgrade Windows-specific dependency colorama

### PR DESCRIPTION
**Pull request by ofek**
### Motivation

Allow users to benefit from numerous bug fixes https://github.com/tartley/colorama/blob/master/CHANGELOG.rst

Most notably https://github.com/tartley/colorama/issues/147, which would:

Resolve https://github.com/docker/compose/issues/5263 & (possibly) https://github.com/docker/compose/issues/5019

@shin- Hello again! Is there any way we could please get this in `1.23.0`? 🙏

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! Can you update the version in requirements.txt as well?

**Comment by ofek** [comment]
@shin- Done!

**Comment by shin-** [comment]
Thanks!

**Comment by ofek** [comment]
@shin- Anytime, thank you as well! Do you know when you'll release `1.23.0`? 😄

**Pull request merged**
