### PR TITLE
Display in the log output the name of those containers created using …

### PR DESCRIPTION
**Pull request by JesusTinoco**
…the scale command

Signed-off-by: Jesus Rodriguez Tinoco <jesus.rodriguez.tinoco@gmail.com>

### CODE REVIEW

**Comment by dnephin** [comment]
Thanks for the PR! This looks correct to me.

Please squash your two commits into a single commit, then LGTM.

**Comment by JesusTinoco** [comment]
@dnephin Done

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Pull request merged**
