### PR TITLE
Allow dependencies to be specified explicitly with `depends_on`

### PR DESCRIPTION
**Pull request by gilclark**
Currently services are started in the order defined by links between services.  We also need services that will share volumes to be started in the right order.  And the net: container:foo statement should be recognized as a project service to be started in the right order and with the proper container name being passed to the using services.  Finally, dependencies need to be explicitly called out even if the services don't use links, volumes_from, net, etc. from each other so that if ordering of service start up is needed it happens correctly.

For example, with this fig.yml file, we will be guaranteed that the data container starts before the db container which starts before the app container which starts before the web container.  And the network container will start before all the rest and it's container id will be properly passed to the using containers.  This allows the "kubernetes pod" type system to be set up easily which was hard to set up with fig before.

```yaml
web:
  image: webimage
  net: "container:network"
  depends_on:
    - app
app:
  image: appimage
  net: "container:network"
  depends_on:
    - db
db:
  image: dbimage
  volumes_from:
    - data
  ports:
    - 1529:1529
data:
  image: dataimage
  volumes: /foo
```
The internals of dependency management have been modified quite a bit with most changes to service.py and project.py.  The unit and integration tests have been modified to check that it all works.

### CODE REVIEW

**Comment by aanand** [comment]
I really like three of the four changes in this PR (I consider them bugfixes), and I'd rather discuss `depends_on` (a new feature) separately. @gilclark, could you move that functionality into a separate PR and rebase/squash this one?

**Comment by gilclark** [comment]
Sorry for the delay, work stuff...

So what's the plan for dependencies that are not links, volumes, or net containers?  I have use cases where I do need to start one container before another.  I suppose I could link them but it would be artificial and someone reading the docker-compose file would be misled as to the container relationships.

Thanks

**Comment by aanand** [comment]
I'd like to properly interrogate the use-cases there, but like I say, I think we should have that discussion separately from the three other (comparatively straightforward) things this PR adds.

**Comment by mbdas** [comment]
Aanand where should we have this discussion. The dependency ordering is a big real world requirement. Copy pasting my comments from #235

Any comment on the dependency ordering that does not involve link or volumes from?
Also the pattern mentioned from docker guys involving config volume containers to have config update containers to be consumed by app containers and in this case both the update container and app container will have volumes_from but the update container needs to run and finish first before app container runs. In terms of ordering there can be 2 use cases. One where one container exits before other runs and in other case the second may run on good health check of first.

**Comment by aanand** [comment]
#235 is the right place for it.

**Comment by gilclark** [comment]
It seems like this is a bookkeeping problem more than anything.  There are the volumes_from and net:container bugs to fix.  And then there is the explicit dependency/ordering issue (235) to address.  For bookkeeping it would be nice to knock off one and then the other but I'd rather not strip out the depends_on (explicit dependency) code and test cases just to put it back in later.

Feel free to suggest whatever keyword you would like.  I'm using "depends_on" but I'm not stuck on it.

Thanks

**Comment by aanand** [comment]
This isn't bookkeeping - bug fixes shouldn't be conflated with feature additions, because the latter merits discussion, and the former shouldn't be held back by it. By way of illustration, see [my comment in 235](https://github.com/docker/compose/issues/235#issuecomment-75939848) - the issue of ordering container startup is *potentially* more complex than just the `depends_on` keyword.

This isn't to rule out `depends_on` as a solution at all: I just don't want that discussion to delay the valuable bug fixes in this PR any longer.

**Comment by gilclark** [comment]
Ok, makes sense.  

So a question: What to do about dependent network containers when a specific service is run with no-deps?  When doing a project.up on a particular named service with --no-deps it currently won't start linked containers for that service.  But, later on the service method _get_volumes_from will create (but not start) any volume container dependencies for the named service.  What should happen with a net:container dependency?  It would have to start (not just be created) to be useful.  Right now I'm not doing that and instead logging a warning that the named service will not have the dependent network container be available.   What's the most appropriate behavior - to be treated like a link? or a volume?
It would depend on the use cases for running single containers.  Any ports of a container that's expecting to use a net container vs. exposing them would not be accessible if that dependency did not start (because of --no-deps).

Thoughts?

Thanks

**Comment by dnephin** [comment]
I see `net:container` as very similar to links, so I would say that it should behave like links (they're both required at "run time").

**Comment by aanand** [comment]
As I see it, our options with `--no-deps` and `net: container` are:

1. Refuse to start the service with a helpful error.
2. Start the other service, but with the same no-deps logic applied (don't start `links` dependencies, do start `volumes_from` and `net` dependencies).
3. Start the service without configuring `net`, so it's standalone.

I see the use case for `--no-deps` as being "I don't want to wait or care about failures in any of the dependencies". From that perspective, (3) sounds best to me.

**Comment by gilclark** [comment]
Ok, sound like the consensus is to start volumes but not links or net
containers when --no-deps is specified.   I'll submit the pull request with
that functionality and make sure the integration tests confirm that.

Thanks

**Comment by stephanbuys** [comment]
@gilclark, are you planning to introduce the "depends_on" feature again as a separate PR?

**Comment by gilclark** [comment]
I can certainly reintroduce depends_on if the community wants it.  In the past there has been resistance because it's not "docker like" in that it doesn't map to existing docker commands.  A work around to force dependency order is to link containers (but that don't really need those links) to force the startup order.

**Comment by stephanbuys** [comment]
@gilclark  +1 from my side, I understand the viewpoint of the community, but is there any real harm? Its not like Docker supports "extends", etc? My use-case is using Weave with Docker, at this stage I have to run Docker-Compose in twice. 
https://gist.github.com/stephanbuys/f16f793ef9373b9b28a6

**Comment by gilclark** [comment]
@aanand, @dnephin,

What are your thoughts on this?  Forcing start up ordering by linking containers in @stephanbuys use case would make no sense at all.

**Comment by dnephin** [comment]
I'm not entirely sure what's going on from that gist, but I don't think you can necessarily rely on those IPs being consistent. You would need to use some other form of service discovery like [one of the many docker dns options](https://github.com/docker/compose/issues/978#issuecomment-74752335) which would let you retry until the services start.

**Comment by stephanbuys** [comment]
@dnephin it needs a little bit of Weave background, the meat of the matter is in the test shell script. Basically it creates a small (weave-based) network between the two containers and statically assigns two IP addresses to the containers involved. But the issue (and why I'm commenting on this thread) is that you can only run the "attach" command (which adds the static IPs to the containers) after the said containers are started. "depends_on" would solve that.

That said, service discovery is a valid strategy, and building more smarts into the weave "attach" command is also an option, so valid point.

**Comment by pikeas** [comment]
Bump, given that `depends_on` was broken off this PR, why hasn't this been merged?

**Comment by gilclark** [comment]
depends_on doesn't match one of the current docker commands so the use of it has been rejected by the compose curators at this time.  I still have the code and unit tests to submit to a pull request but only if I know there's a good chance it will get accepted.

**Comment by pikeas** [comment]
@gilclark What about the part of the PR that treats volumes_from as a dependency?

**Comment by gilclark** [comment]
Yes, that was merged in along with the net container being treated as a dependency.

**Comment by gtmtech** [comment]
+1 for depends_on.   

links don't work for --net=host (see https://github.com/docker/docker/issues/7066) , and yes docker doesn't have depends_on as a core command, (maybe it should), but then docker doesn't manage multiple containers by itself (swarm aside), and the whole point of docker-compose is to manage multiple containers, so IMHO it would be better to include this rather fundamental feature - (especially if it got coded up over 6 months ago) and port it over to use docker "depends_on" if it ever gets provided there at that time. It seems to be a vital missing piece of functionality.

**Comment by aanand** [comment]
@gtmtech The place to discuss this is https://github.com/docker/compose/issues/374 - there's a lot of discussion in there. The fundamental problem is more complex than starting containers in a particular order.

**Comment by dnephin** [comment]
Part of this was pushed in #1076 which doesn't seem to be linked from here for some reason, so adding the link now.

**Comment by dnephin** [comment]
With the new networking coming in (and deprecating links), it might be worth considering a `depends_on` option. It still seems to me like more of a "nice-to-have" than a critical feature, but it's worth some discussion I think.

**Comment by gilclark** [comment]
I had a fork with depends_on a while back.  It's not hard to do since it uses the dependency logic of links and volumes.  Would it be better to add it in before or after links are removed.

**Comment by delfuego** [comment]
It's hard to tell which issue these days is the "right" place to vote for a new docker compose functionality that allows explicit dependencies to be declared, but consider my vote a strong one. With the new Docker 1.9 networking functionality, and looming deprecation of container links in favor of it, there is now no great way to make sure that container A starts up before container B — because if you use Docker 1.9 user-defined networking, you can no longer specify container links. That's... broken.

**Comment by mbdas** [comment]
I think issue 374 is the right place for it. Can you post it there? I was about to post this today myself.

**Comment by delfuego** [comment]
@mbdas Done.

**Comment by kevstigneev** [comment]
Deprecation of links without a replacement boils Compose value down to a basic shell script. The major power of Compose is being a "Make" for containers, so

    docker-compose up <service>

assures that both the <service> and the other services it needs are started. `docker-compose.yml` used to be a reasonable manifest for a composite application that is executable and is easy to translate to the other representations (e.g. Marathon). While

    docker-compose --x-networking up <service>

starts just the <service> itself, so I have either to list its dependencies in the command line or have a separate Compose file for each service.

Networking effect of links is difficult to underestimate ether as it provides static "host names" for service containers regardless `scale` or `COMPOSE_PROJECT_NAME`. But that's off-topic.

**Comment by wr0ngway** [comment]
+1

**Comment by dnephin** [comment]
Thanks for starting the discussion about this. I've opened #2682 so we can continue to discuss the idea.

A lot has changed since this PR was opened, and I believe we applied some of these changes to rename link to deps in a separate branch. Since there's going to be a lot of work to rebase this, and have it only apply to the v2 config, it may be easier to start from scratch.

I'm going to close this PR for now until we've sorted out the details in #2682.

**Pull request closed without merging**
