### PR TITLE
Refactor `StringContains` and `contains` function usages to use `go` ones

### PR DESCRIPTION
**Pull request by ulyssessouza**
**What I did**
Refactor contains functions

### CODE REVIEW

**Review by glours — COMMENTED** [review]
I'm wondering if we shouldn't wait the end of the experimental period before using those functions? 🤔 
>Warning: Packages here are experimental and unreliable. Some may one day be promoted to the main repository or other subrepository, or they may be modified arbitrarily or even disappear altogether.

**Comment by ulyssessouza** [comment]
@glours I was thinking the same. But when I saw the implementation... I cannot think about something that would be change enough for our simple case. There is also a "k8s.io/utils/strings/slices" implementation for `Contains`.
For me that's the same, since the idea of the PR is just not to have "yet another" implementation of a so common function.

**Comment by ndeloof** [comment]
isn't "yet another (copy/paste) implementation for common function" the basis of Golang design ?
kidding appart, shall we keep this PR open?

**Comment by ulyssessouza** [comment]
I'll close it... It's still not extracted from the experimental package and all the files are conflicting... 😞

**Pull request closed without merging**
