### PR TITLE
Add "disambiguation" page for environment variables

### PR DESCRIPTION
**Pull request by aanand**
As described in #3125, there are multiple contexts in which a user might be looking for information on Compose and environment variables. I've attempted to collate them in one place, hopefully so that users can more easily get to where they need to be.

ping @shin- @dnephin @londoncalling

### CODE REVIEW

**Comment by shin-** [comment]
Definitely useful, absolutely needed, LGTM :+1:

**Comment by shin-** [comment]
Should this mention `docker-compose run -e ...` as well?

**Comment by aanand** [comment]
Good point - I've updated with a section on `run`.

**Comment by dnephin** [comment]
rebuild this please

**Comment by dnephin** [comment]
test this please

**Comment by dnephin** [comment]
LGTM

**Comment by denismakogon** [comment]
LGTM +1

**Comment by londoncalling** [comment]
LGTM!

**Pull request merged**
