### PR TITLE
Added support for IPC namespaces, fixes GH-1689

### PR DESCRIPTION
**Pull request by predakanga**
Wasn't sure about the protocol regarding tests for minor changes like this, but there are no edge cases regarding the IPC setting - it's None, or a string, nothing more.

Signed-off-by: Lachlan Pease <predatory.kangaroo@gmail.com>

### CODE REVIEW

**Comment by mnowster** [comment]
Hi @predakanga , thanks for this. I double checked in docker-py and there is indeed support in `create_host_config` for ipc so yeh, we should support it too. 

You raise a good question about tests protocol. Looking at the test coverage we have for `_get_container_host_config`, we don't have a unit test for every option and this doesn't contain extra logic, so I'm OK with it.

LGTM. We're having some issues with Jenkins at the moment, the failure is unrelated to the code changes in this PR.

**Comment by dnephin** [comment]
code looks good, but I think we should add it to the docs in `docs/yml.md` as well

**Comment by predakanga** [comment]
Thanks for the feedback, @mnowster and @dnephin.

I'm adding the documentation at the minute, but noticed two other disparities - docker-compose is missing UTS and Ulimits configuration (see [docker-create](https://docs.docker.com/reference/commandline/create/)).

UTS isn't in docker-py yet, but Ulimits is - should I fold ulimit support into this PR, to save some time?

**Comment by mnowster** [comment]
Hi @predakanga , ah good spot with the missing options, thanks for that :palm_tree: 

If you have the time, it'd be super helpful if you could create a separate issue and PR for `Ulimits`. We try to keep PRs to mostly just doing one thing, where possible, helps us review them.

**Pull request merged**
