### PR TITLE
Support env file

### PR DESCRIPTION
**Pull request by benlangfeld**
Replaces #481 and #479 addressing the issues raised in those tickets.

### CODE REVIEW

**Comment by abesto** [comment]
Looking forward to this a lot. Any chance of a minor release soon? :pray:

**Comment by johanhaleby** [comment]
I'd also be really happy for this. This is a showstopper.

**Comment by petebrowne** [comment]
:+1: Our team is waiting for this one as well.

**Comment by Starefossen** [comment]
+1 we are waiting on this too!

**Comment by dnephin** [comment]
This feature is available in the latest docker-compose RC releases https://github.com/docker/fig/releases

**Pull request merged**
