### PR TITLE
WIP: updated note format for dockerfile per Aanand's comments on PR #…

### PR DESCRIPTION
**Pull request by londoncalling**
…3019

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@aanand please have a look at this. 

* I tried several ways of reformatting that note to keep the structure of the blue vertical bar and text throughout (HTML, CSS, and mix of markdown) but it's just not do-able. I think the way I've structured it now is clearer. Let me know what you think.

* There is a bit of the wording that still is not clear to me. Can you, in fact, use an image together with a Dockerfile in __version 2__ (but not v.1)?. If so, we should explicitly state this. It's not clear from the description or the examples.

* I probably should have attached this to the original PR but wasn't sure how to do i.

**Comment by aanand** [comment]
> Can you, in fact, use an image together with a Dockerfile in version 2 (but not v.1)?

Yes!

> If so, we should explicitly state this. It's not clear from the description or the examples.

Agreed. I'll do a PR.

LGTM

**Comment by aanand** [comment]
Updated docs in https://github.com/docker/compose/pull/3024.

The documentation job is failing on this PR, but I can't find the error message.

**Comment by londoncalling** [comment]
Hey Aanand, I will check this out later tonight as soon as I can, and if I
can't figure it out I'll ping Sven . I've seen a couple of docs builds fail
for quirky reasons lately . More soon.

**Comment by londoncalling** [comment]
@SvenDowideit @moxiegirl : we looked at the Console Output for the failed docs build, and neither @aanand nor I can figure out or find the fail. Can you guys help?

**Comment by dnephin** [comment]
retest this please

**Pull request merged**
