### PR TITLE
Environment variable interpolation in docker-compose.yml

### PR DESCRIPTION
**Pull request by sebglazebrook**
Relating to https://github.com/docker/compose/issues/1377

I know there has been a couple of PR's around this of recent. Here's my two cents.

Note:

- This is my first time writing Python so I'm assuming my code is missing a lot of pythonisms.
- Also was going to do a bit more clean up and structure changes but I wanted someone to look over it first to let me know if I'm on the right path.

Any/all feedback welcome.

### CODE REVIEW

**Comment by aanand** [comment]
Thanks for making a start!

A few things:

- Variable expansion within strings is entirely uncoupled from Compose's duties, and can therefore live in a separate module (or, even better, a separate Python package entirely).

- A lot of the classes and class methods you've got can be reduced to simple top-level functions, which is much more Pythonic.

- I'm wary of regular expressions, as explained in #1377. We need to make sure it's robust and produces good error messages for malformed input.

It might be worth looking at / building upon @kojiromike's beginnings-of-an-implementation of POSIX PE: https://github.com/kojiromike/parameter_expansion

**Comment by timfallmk** [comment]
FWIW this would likely solve #1553

**Comment by funkyfuture** [comment]
@timfallmk what are YOU doing here? ;-)

**Comment by dnephin** [comment]
This was solved with #1765

**Pull request closed without merging**
