### PR TITLE
1224: Check that image or build is specified.

### PR DESCRIPTION
**Pull request by mchasal**
Added the check to make sure that exactly one of the options is specified and a test case to check.
Also had to add an image option to a bunch of the existing test cases that started failing because of the new check.

Will anxiously await any review comments. 

Thanks

### CODE REVIEW

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
LGTM

**Comment by dnephin** [comment]
Thanks for fixing this!

**Comment by mchasal** [comment]
Thanks all. Happy to contribute and looking to do more in the near future.

**Pull request merged**
