### PR TITLE
Only create the default network if at least one service needs it

### LINKED ISSUE #2275: Only create the default network if it's necessary
Our docs (https://github.com/docker/compose/blob/master/docs/networking.md#custom-container-network-modes) claim that we only create the network if it's going to be used, but currently we always create the network when `--x-networking` is set. 

We should only be creating it if at least one container uses the default network.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #2275

### CODE REVIEW

**Comment by shin-** [comment]
LGTM!

Am I the only one who feels that `mode` is a bad name for that property?

**Comment by dnephin** [comment]
Ya, that property was hard to name. It has to represent the difference between each implementation. In some contexts it makes sense (host mode vs bridge mode).

**Comment by dnephin** [comment]
Fixed the test, and `s/all/any/`

**Comment by shin-** [comment]
:+1:

**Pull request merged**
