### PR TITLE
Reorder reference docs

### PR DESCRIPTION
**Pull request by mnowster**
A rebased version of this PR: https://github.com/docker/compose/pull/1798. 

Also included re-ordering of the `docker run` options at the end.

### CODE REVIEW

**Comment by mnowster** [comment]
ping @moxiegirl could you give this a once over glance for me please? It's a rebased version of the other PR. I fixed the conflicts and ensured that the changes made to `volume_driver` docs weren't blatted by git.

**Comment by moxiegirl** [comment]
@mnowster LGTM -- your choice if you want to squash to a single commit.

**Comment by mnowster** [comment]
@moxiegirl thanks for looking over it. Think I'm going to leave it as separate commits so I don't erase the other author's contribution, else it'll merge into two as though it was all done by me.

**Comment by moxiegirl** [comment]
Gotcha.  I'll go ahead and merge this then.

**Comment by dnephin** [comment]
@adrienbrault nice find, would you mind opening an issue for it so we don't forget?

Thanks!

**Pull request merged**
