### PR TITLE
Fix env_file overrides with extends

### LINKED ISSUE #2446: env_file doesn't get extended
https://github.com/vipconsult/dockerfiles

docker-compose -f always-on-prod.yml --x-networking up -d

this extends always-on.yml which on it side extends common.yml which has 
env_file:
        - env 

always-on-prod.yml defines its own env_file
env_file:
        - env-prod

the problem is that envs defined in the env-prod don't override the envs defined in common.yml 

I think this worked as expected before I upgraded from  1.5.0

Docker version 1.9.0, build 76d6bc9
docker-compose version: 1.6.0dev

linux debian jessie

### PR DESCRIPTION
**Pull request by dnephin**
Based on #2405
Fixes #2446

### CODE REVIEW

**Comment by aanand** [comment]
Should this be rebased now that #2405 is in?

**Comment by dnephin** [comment]
I can rebase it to update github, but it won't change the actual merge

**Comment by dnephin** [comment]
Ok, rebased

**Comment by aanand** [comment]
Great. Makes the PR easier to read at least!

LGTM

**Pull request merged**
