### PR TITLE
bump docker/docker and docker/cli v27.0.1-rc.1, compose-go v2.1.3

### PR DESCRIPTION
**Pull request by thaJeztah**
rebased of / updated version of:

- https://github.com/docker/compose/pull/11892
- https://github.com/docker/compose/pull/11893
- supersedes / closes https://github.com/docker/compose/pull/11892
- supersedes / closes https://github.com/docker/compose/pull/11893
- supersedes / closes https://github.com/docker/compose/pull/11916

### go.mod: github.com/compose-spec/compose-go v2.1.3

- related: https://github.com/compose-spec/compose-go/pull/637

diff:

- https://github.com/compose-spec/compose-go/compare/v2.1.2...v2.1.3

### go.mod: docker/docker and docker/cli v27.0.1-rc.1

diffs:

- https://github.com/containerd/ttrpc/compare/v1.2.4...v1.2.5
- https://github.com/docker/cli/compare/v26.1.4..v27.0.1-rc.1
- https://github.com/docker/docker/compare/v26.1.4..v27.0.1-rc.1

**What I did**

**Related issue**

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@akerouanton @glours I rebased @akerouanton's PRs and updated them to v27.0.1-rc.1; I combined both the docker/cli, docker/docker, and compose-go PRs in this one, I think this one should be ready to go.

I may do one more update after this, as one change went into docker/cli
that wasn't in the tag; https://github.com/docker/cli/compare/v27.0.1-rc.1...b83cf582cd3b932b6fce900a54cf0e1e6f61ac17

But I _think_ we're good otherwise.

**Comment by thaJeztah** [comment]
Docker Hub is currently down, so CI is failing right now though 😅

**Comment by thaJeztah** [comment]
Nice! Docker Hub is back; all green now 🥳

**Comment by thaJeztah** [comment]
Heh, that's a good chicken-and-egg issue; If we wait for 27.0.1 to arrive, the version of compose that will be on download.docker.com will be the "current" release of compose. 🙈 

cc @vvoland

**Comment by thaJeztah** [comment]
I think it's probably fine to ship with `rc.1` as it will be mostly identical to "ga". We could do one more revendor after this PR to get the actual commits that will be used for v27.0.1 GA (which would include the diff I linked above).

**Review by vvoland — APPROVED** [review]
There shouldn't be any changes between v27.0.1-rc.1 and the v27.0.0 in the vendored files:
https://github.com/moby/moby/compare/v27.0.1-rc.1...master

So I think it's fine to go with the rc.1 vendor

**Review by glours — APPROVED** [review]
LGTM

**Pull request merged**
