### PR TITLE
Fix bash completion on systems where extglob is not set

### LINKED ISSUE #5658: bash completions fail with macOS's bash 3.2.57
```
==> bash -c 'source /usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose && complete -p docker-compose'
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: syntax error in conditional expression: unexpected token `('
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: syntax error near `@($'
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: `        [[ ${words[$glob_pos]} == @($glob) ]] && echo "$key"'
```

```
bash-3.2$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
bash-3.2$ 
```

### PR DESCRIPTION
**Pull request by briandealwis**
Apply same fix as https://github.com/docker/cli/commit/7fa96238a6c78e6b35a8e9a0758bef0c07a96b15

Fixes #5658

### CODE REVIEW

**Comment by albers** [comment]
Actually this fix needs to be applied twice:

- when the completion script is sourced (your fix)
- when the completion function is being called (missing, see https://github.com/docker/cli/blob/master/contrib/completion/bash/docker#L4935) for the Docker equivalent.

**Comment by albers** [comment]
@briandealwis Oh, I forgot that the second part was already added, so please ignore my comment.
Your fix LGTM once the commit is signed.
Thanks a lot!

**Comment by briandealwis** [comment]
@albers I signed the commit — is there anything further?

**Comment by albers** [comment]
Your PR needs to be approved by the maintainers (I'm no a maintainer, just the primary contributor for the bash completion).
@shin- PTAL. Changes LGTM, tested against the [albers/bash-completion-mac](https://hub.docker.com/r/albers/bash-completion-mac/) image

**Comment by shin-** [comment]
Sweet, thank you both!

**Pull request merged**
