### PR TITLE
bump docker/cli to v1.25 beta.1

### PR DESCRIPTION
**Pull request by g0t4**
**What I did**

Updated `docker/cli` to get access to `RunAttach`. Also updated `docker/docker` and added dependencies + code changes to get build working.

I could use some guidance as I am not familiar with these dependencies! Thanks

**Related issue**

This PR is needed for `docker compose attach` PR: https://github.com/docker/compose/pull/11181

### CODE REVIEW

**Comment by g0t4** [comment]
@ndeloof once this is merged I will get the `attach` PR rebased.

**Comment by ndeloof** [comment]
this will unlock https://github.com/docker/compose/pull/11208 and https://github.com/docker/compose/pull/10939

**Comment by ndeloof** [comment]
just run `go mod tidy` and amend your commit, then we will be all good

**Comment by ndeloof** [comment]
I created https://github.com/docker/compose/pull/11247 to address linter issues

**Comment by milas** [comment]
Merged with 56e2ad9ee59462f535532582cf2d13b701f31eea / #11247.

Thanks for the PR ❤️

**Pull request closed without merging**
