### PR TITLE
Docs don't mention docker-compose also requires read permission.

### PR DESCRIPTION
**Pull request by XavierTalpe**
When installing docker-compose on Ubuntu I ran into the following problem:
````
Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg
````

Based on some Googling and information in https://github.com/docker/compose/issues/1135, adding the read permission solved the issue for me and other people.

### CODE REVIEW

**Comment by aanand** [comment]
Looks like this needs a rebase.

**Comment by dnephin** [comment]
How did you download the binary? It's very strange that it would be downloaded without read permissions.  Are you sure the issue wasn't the user ownership ?

**Comment by XavierTalpe** [comment]
@dnephin Good point. I redid the steps I did yesterday and now it seems to work... /confused. The read flag is indeed set by default. Not sure how I managed to run into this issue. I guess this PR can be closed as invalid.

**Comment by aanand** [comment]
I suppose it wouldn't hurt to add `+rx` though?

**Comment by dnephin** [comment]
Since it's not necessary, I think it might just serve to confuse people instead of actually fixing anything.

**Pull request closed without merging**
