### PR TITLE
Docker Compose roadmap

### PR DESCRIPTION
**Pull request by aanand**
Per https://github.com/docker/docker/issues/9694, here's the start of the Docker Compose roadmap.

### CODE REVIEW

**Comment by aanand** [comment]
The binary name is TBD, yes.

My problem with Git-style subcommands is that they're lengthy: imagine having to type `docker compose`, `docker compose build`, `docker compose rm web` etc. I'd much prefer a name both shorter and un-prefixed.

My first thoughts were `dc` or `cmp`, but both are standard Unix tools. Maybe `dcm`?

**Comment by thaJeztah** [comment]
> I'd much prefer a name both shorter

Agreed - it is a tough one to pick right, `docker compose` obviously has the advantage that it "communicates" the relation with 'docker', but I understand your intent to keep it short.

Perhaps it should be `docker compose`, and install some aliases by default?

Perhaps really far-fetched, but what if "docker compose" would start an interactive shell? e.g.

    $docker compose
    $$ compose [myproject] > start web
    Starting myproject_web_1…
    $$ compose [myproject] > ps

    Name              Command    State   Ports
    -----------------------------------------------------------------
    myproject_web_1   /start.sh  Up      0.0.0.0:49160->80/tcp

**Comment by gabrielgrant** [comment]
@thaJeztah Doesn't seem that far-fetched (cf. `git annex shell`)

**Comment by thaJeztah** [comment]
@gabrielgrant after writing it, I must say I actually liked the idea yes :smile: but not sure how easy it is to implement. Some thought should be given to UX and interaction with other processes (it may be cumbersome to have to "exit" the Compose-shell to for other tasks?). There should be a clear definition of what is possible *inside* the "compose shell", and what not.

**Comment by marksteve** [comment]
Are there also plans to port fig/compose completely to go?

**Comment by aanand** [comment]
@marksteve Nope - see https://github.com/docker/docker/issues/9694. We're going to continue from the Fig codebase.

**Comment by bfirsh** [comment]
@marksteve here is some more papertrail about writing in Go: https://github.com/docker/fig/issues/94

@nathanleclaire and others have been working on it.

**Comment by marksteve** [comment]
:+1:

**Pull request merged**
