### PR TITLE
Add '--timestamps' option to 'up'.

### PR DESCRIPTION
**Pull request by mnottale**
Signed-off-by: Matthieu Nottale <matthieu.nottale@docker.com>

### CODE REVIEW

**Comment by mnottale** [comment]
Unfortunately the "attach" endpoint does not support timestamps, so we have to use "logs", which only works on started containers, hence the added complexity.

**Comment by shin-** [comment]
Hm, that's concerning to me. I feel like we're going to have to deal with a lot of inconsistent results between regular `up` and `up` with  `--timestamps` and that's going to be a headache to maintain. The feature might not be worth the cost down the line.

**Comment by mnottale** [comment]
Hmm, would it be worth it to add a `timestamps` options to `attach`? That seems like an overlook.

**Comment by ijc** [comment]
> Hmm, would it be worth it to add a timestamps options to attach? That seems like an overlook.

Probably it would have been, but I know you've moved on to other things so I'm going to take a chance on closing this now -- if I was wrong and you are still interested please do reopen though.

**Pull request closed without merging**
