### PR TITLE
add memory-reservation support

### PR DESCRIPTION
**Pull request by yank1**
The docker 1.12 would support memory-reservation.
It's very important production feature.

@aanand it's OK now
Ref #3712

### CODE REVIEW

**Comment by aanand** [comment]
Looks like it's failing because docker-py doesn't support `mem_reservation` on container creation. Support needs to be added there first.

**Comment by yank1** [comment]
HI @aanand , I add a pull request at docker-py 

https://github.com/docker/docker-py/pull/1129

**Comment by pascalandy** [comment]
+1

**Comment by chafikhnini** [comment]
The PR seems to make the build failing. Do you know where it comes from ? We are using Docker Compose with AWS ECS and this is a feature we need because ECS forces memory_limit at container creation :( Thanks.

**Comment by lox** [comment]
Any progress on this? @yank1 looks like it needs a rebase.

**Comment by shin-** [comment]
Implemeted in #4563

**Comment by c100k** [comment]
Great job, thanks ! Do you know when it is released ?

**Comment by shin-** [comment]
Late this month / early next month.

**Pull request closed without merging**
