### PR TITLE
docs: unify no trailing dots in docstrings and help

### PR DESCRIPTION
**Pull request by PiotrDabrowskey**
**What I did**
Some docstrings and help strings ends with a trailing dot, but most of do not. Current state is that even `docker compose` output lists some args and commands with a trailing dot, which is not eye pleasing. I've unified this styling but only in short/one-line string. Multi-line and most of multi-sentence docstrings have been left intact.

If such changes are not welcomed, let me know and I'll close the PR (or just close it by yourself).

**Related issue**
N/A

**A picture of a cute animal, if possible in relation to what you did**
Nela :feet: 
image

### CODE REVIEW

**Review by milas — CHANGES_REQUESTED** [review]
Thanks for the PR!

This looks good, and agreed that it's more consistent with CLI conventions.

You will need to rebase/force-push your commit to add the DCO before I can accept the PR, however. See the instructions @ https://github.com/docker/compose/pull/11301/checks?check_run_id=19909474681.

**Comment by PiotrDabrowskey** [comment]
Thanks, I've just added the missing signoff.

**Review by milas — APPROVED** [review]

**Comment by PiotrDabrowskey** [comment]
I see some checks have failed. Will look into it and fix the problems but no earlier than in 10 days or so as I'm afk.

**Comment by PiotrDabrowskey** [comment]
I've fixed the problems detected by checks and rebased resolving conflicts from the main branch.

**Comment by PiotrDabrowskey** [comment]
Sorry, I've missed the linter error - fixed now. I've also rebased on current `main` and rerun `lint` and `docs` to be sure. All should be green.

**Comment by milas** [comment]
Thanks again! Sorry this was a little tricky to get merged 🙃

**Pull request merged**
