### PR TITLE
Update django.md

### PR DESCRIPTION
**Pull request by andradei**
From the [Django documentation](https://docs.djangoproject.com/en/1.7/ref/django-admin/#syncdb): `syncdb` was deprecated in favor of `migrate`.

### CODE REVIEW

**Comment by aanand** [comment]
Thanks!

- Your commit needs signing off (`git commit --amend --signoff`).
- Would you mind pinning the versions in `requirements.txt`, so we can avoid future breakages?

**Comment by andradei** [comment]
The versions seem to be pinned in `requirements.txt` already. Do you want me to do the same for `requirements-dev.txt`?

**Comment by andradei** [comment]
I tested theses changes by running multiple projects with that setup, all working. Do I still need to `--amend --signoff` the commit?

**Comment by aanand** [comment]
Thanks. Signoff is necessary for all contributions, yep - see [CONTRIBUTING.md#sign-your-work](https://github.com/docker/fig/blob/master/CONTRIBUTING.md#sign-your-work)

**Comment by andradei** [comment]
Thanks for the link, and sorry for not reading the document.

It is signed now :)

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
Thanks for the contribution!. Sorry it's taken us a while to merge this.  

If you could rebase onto the latest master,  I think we should be able to get this merged.

**Comment by andradei** [comment]
I'm closing this and redoing the fork since so much has changed. I'll open another PR when I can run the tests locally.

**Pull request closed without merging**
