### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by cloojure**
Showed required use of sudo.

### CODE REVIEW

**Comment by dnephin** [comment]
I think #3061 is a better suggestion

**Comment by JLarky** [comment]
and `sudo su` is frowned upon, that's why article itself mentions `sudo -i` just paragraph above

**Comment by cloojure** [comment]
Hmmm, I'm not familiar with `sudo -i` vs `sudo su`.  Setting up the env from .profile & friends doesn't seem to affect it either way, does it?

**Comment by JLarky** [comment]
all of this stuff is not needed anyway, just use `curl -o` https://github.com/docker/compose/pull/3076#issuecomment-192082391

**Comment by JLarky** [comment]
as for `sudo -i`, it's just proper way to get into root, it is not big a deal in this case, but doing `sudo su` is just teaching kids bad words, so that later they would have to ask "isn't sudo su ok? I've seen some people in the internets do that". You can read more on topic [here](http://askubuntu.com/questions/376199/sudo-su-vs-sudo-i-vs-sudo-bin-bash-when-does-it-matter-which-is-used), it also has some links in it that could be helpful.

**Comment by cloojure** [comment]
Oh, I see using "sudo curl ... -o /usr/local/bin/docker-compose" does away with the problematic shell redirect all together. OK.  #3076

**Comment by dnephin** [comment]
Closing in favour of the suggestions in #3061

**Pull request closed without merging**
