### PR TITLE
add support for `runtime` option in service definitions

### LINKED ISSUE #5360: Please provide docker-compose alternative for docker run --runtime=some-runtime argument
I inspected docker-compose reference and did not find any means to provide "--runtime=some-runtime" argument for starting containers.
Please provide some documentation or add a new feature if it's currently impossible.
Main motivation:
nvidia-docker 2.0 default usage is:
```bash
docker run --runtime=nvidia ...
```

### PR DESCRIPTION
**Pull request by cuckoohello**
Works with [nvidia-docker2](https://github.com/NVIDIA/nvidia-docker)

For docker compose
```
version: '3'
services:
  nvidia:
    image: nvidia/cuda
    runtime: nvidia
    command: nvidia-smi
```
`docker-compose up`
```bash
$ docker-compose up
Creating network "nvidia_default" with the default driver
Creating nvidia_nvidia_1 ...
Creating nvidia_nvidia_1 ... done
Attaching to nvidia_nvidia_1
nvidia_1  | Mon Nov 27 02:22:54 2017
nvidia_1  | +-----------------------------------------------------------------------------+
nvidia_1  | | NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
nvidia_1  | |-------------------------------+----------------------+----------------------+
nvidia_1  | | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
nvidia_1  | | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
nvidia_1  | |===============================+======================+======================|
nvidia_1  | |   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
nvidia_1  | | 28%   42C    P0    39W / 180W |      0MiB /  8112MiB |      0%      Default |
nvidia_1  | +-------------------------------+----------------------+----------------------+
nvidia_1  | |   1  GeForce GTX 1080    Off  | 00000000:03:00.0 Off |                  N/A |
nvidia_1  | |  0%   41C    P0    36W / 180W |      0MiB /  8114MiB |      0%      Default |
nvidia_1  | +-------------------------------+----------------------+----------------------+
nvidia_1  |
nvidia_1  | +-----------------------------------------------------------------------------+
nvidia_1  | | Processes:                                                       GPU Memory |
nvidia_1  | |  GPU       PID   Type   Process name                             Usage      |
nvidia_1  | |=============================================================================|
nvidia_1  | |  No running processes found                                                 |
nvidia_1  | +-----------------------------------------------------------------------------+
nvidia_nvidia_1 exited with code 0
```

close #5360

Signed-off-by: Yafeng Shan <cuckoo@kokonur.me>

### CODE REVIEW

**Comment by cuckoohello** [comment]
@shin-  Thank you for your kind reply.

>  The config schema for v3 can not be changed. Additions to the schema may be suggested on the docker/cli repo and then ported back to Compose. For this PR, support for the option should be added in the 2.3 schema instead

I have recommitted the code which only adding `runtime` option in the 2.3 schema, and will have another pull request to docker/cli repo for v3 schema.

>  There's no tests.

I have tried to add some tests before, but docker only provides `docker-runc` runtime  by default,  and `nvidia` runtime needs a machine with a nvidia gpu and `nivida-docker` installed. So if I just add some tests for nvidia runtime, it won't pass on a general computer.

Could you give me some suggestions, thank you.

**Comment by shin-** [comment]
Cool, thank you for applying the schema changes!

For the tests, I think there are 3 things we would like to do:
1. Add unit tests that make sure the option is picked up in the config (look at [these tests](https://github.com/docker/compose/blob/master/tests/unit/config/config_test.py#L1568-L1680) for example)
2. Create an integration test that explicitly specifies `runc` as the runtime and make sure it works as expected
3. Create a test decorator that checks whether a particular runtime is available and skips the test if it isn't. You can model that one after [`no_cluster`](https://github.com/docker/compose/blob/master/tests/integration/testcases.py#L177-L187). Then you can write a custom runtime test with a `@if_runtime_available('nvidia')` decorator that will only run if `nvidia` is available.

Let me know if any of that is unclear and I'll do my best to assist.

**Comment by cuckoohello** [comment]
Thank you. Let me have a try first.

**Comment by cuckoohello** [comment]
Hi @shin- , I have written both unit and integration tests for the `runtime` option.

But the jenkins reports:

```
  Getting remote pull request #5405...

    Checking pull request #5405
    (not from a trusted source)
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: PR-5405 (70658069fbdf5ac68c5d4bfbf3b85bb10781bc16 → 5fdca0569961e9df6d0df8221439ec7a64b76760)
Scheduled build for branch: PR-5405
```

Please have a look, thank you.

**Comment by cuckoohello** [comment]
@shin- I have created both unit and integration tests for `runtime` option, and pushed the code with a force push.

But jenkins always report error due to `not from a trusted source`. 

Please have a look, thank you.

```
  Getting remote pull request #5405...

    Checking pull request #5405
    (not from a trusted source)
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: PR-5405 (02cfa11ddf88decdfdf4c4b70d719618108e2153 → f700b73964338fb134165e4242859b06cafb2e1e)
Scheduled build for branch: PR-5405

  1 pull requests were processed (query completed)

  1 pull requests were processed

Finished examining docker/compose
```

**Comment by anibali** [comment]
Sorry to randomly interject, but I've been following this PR in eager anticipation of replacing nvidia-docker-compose for good.

@cuckoohello If you look at the build output at https://jenkins.dockerproject.org/job/docker/job/compose/job/PR-5405/9/console you will see that there are in fact errors/warnings that you can address. Namely:

```
04:21:10 [all_py27] tests/integration/testcases.py:190:1: E302 expected 2 blank lines, found 1

04:21:10 [all_py27] tests/integration/testcases.py:200:106: E501 line too long (127 > 105 characters)

04:21:10 [all_py27] tests/integration/project_test.py:979:21: F821 undefined name 'V2_3'

04:21:10 [all_py27] tests/integration/project_test.py:999:21: F821 undefined name 'V2_3'

04:21:10 [all_py27] tests/integration/project_test.py:1015:6: F821 undefined name 'if_runtime_available'

04:21:10 [all_py27] tests/integration/project_test.py:1019:21: F821 undefined name 'V2_3'
```

Thanks for working on this enhancement, it will certainly be very useful for CUDA users in the future!

**Comment by cuckoohello** [comment]
@anibali Thank you. I use gitlab-ci before, and don't use jenkins, not find the console.

@shin- Finally, both the test and integration tests work finnally. And provide `if_runtime_available` test scripts. Please have a look, thank you.

**Comment by andyneff** [comment]
> I have recommitted the code which only adding runtime option in the 2.3 schema, and will have another pull request to docker/cli repo for v3 schema.

@cuckoohello, have you made any progress on this?

**Comment by cuckoohello** [comment]
@andyneff I have tried to add support for docker/cli, but find there're much more work need to be done.  At least there projects need to be adapted.

I will try to manage this next week, and give you feedback

**Comment by shin-** [comment]
@cuckoohello Sorry, it was a busy month. Changes LGTM now for the most part, just a few typos but I'll fix those in a separate commit. Thanks a lot!

**Comment by fredericgermain** [comment]
I'm not sure about this, but is it supposed to work on schema v3?

I just tried the exemple above on master, it only works for me if I change the schema version to 2.3.

**Comment by cuckoohello** [comment]
@fredericgermain You can look at the discussion above first.

If you want to use runtime option for schema v3 and above, the only thing you need to do is just modify the config schema for the  corresponding json file.

But currently config schema json files in docker compose bump from upstream docker repo, don't accept any modification. So if you want to make these files changed, you need to pull request to upstream repo `docker`, and `docker` depends on repo `docker-cli`, you need to add runtime support for swarm first.... A lot of work....

I don't have enough time to do this now...

**Pull request merged**
