### PR TITLE
Add support for docker run --tmpfs flag.

### LINKED ISSUE #2778: Add support for tmpfs
In the latest release candidate for 1.6.0 the --tmpfs options is not available.  Is it possible to add this to the service definition via some other mechanism.

### PR DESCRIPTION
**Pull request by dnephin**
Carry #2978
Fixes #2778

### CODE REVIEW

**Comment by dnephin** [comment]
Oh, this is still blocked on https://github.com/docker/docker-py/pull/939, I didn't realize

**Comment by dnephin** [comment]
Updated the docker-py sha, let's see if we get a green build now.

**Comment by aanand** [comment]
Looks like `tmpfs` is still getting passed to `create_container`, not (just) `create_host_config`?

**Comment by dnephin** [comment]
Test runs are still flaking, but the test passes locally, so it should be unrelated.

**Comment by aanand** [comment]
LGTM

**Pull request merged**
