### PR TITLE
Adds silent flag to install cURL command

### PR DESCRIPTION
**Pull request by iMerica**
The download progress isn't helpful to users installing Compose.

### CODE REVIEW

**Comment by bfirsh** [comment]
LGTM

**Comment by aanand** [comment]
I'm :-1: on this - I like having a progress indicator when downloading anything larger than a text file.

If anyone disagrees vehemently, feel free to make your case! Otherwise I'll close this.

**Comment by dnephin** [comment]
Thanks for the PR. I agree with @aanand here, it's better to keep the progress information on by default.

**Comment by iMerica** [comment]
Sure np.

**Pull request closed without merging**
