### PR TITLE
docker-compose down

### PR DESCRIPTION
**Pull request by MathewT**
This PR adds docker-compose down as a simple alias for docker-compose stop.     docker-compose down seems a bit more intuitive for many than docker-compose stop.

### CODE REVIEW

**Comment by MathewT** [comment]
My apologies for not signing the commit per the rules.  I executed the instructions above.  Please let me know if anything else is required.

**Comment by rvion** [comment]
do you really think an alias is a good idea ?
in my opinion, it only adds confusion.
There is no evidence that it's more intuitive.
Also, all past tutorials will mention stop, so It might confuse the reader about why there is 2 commands. 
People will think the 2 commands are different.
I would -1 this feature

Can't you just add an alias in your personnal config ?

**Comment by rvion** [comment]
Is there some "authority" checking those PR to assure the coherence of the whole ?

**Comment by keiththomps** [comment]
:+1: The opposite of `up` is `down`. Seems more intuitive to me.

**Comment by dnephin** [comment]
Thanks for the PR!

Instead of duplicating the `stop` command, could you try this:

1) rename `stop` to `down`
2) alias `stop` to `down`

```python

    def down(...):
        ...

    stop = down
````

3) I wonder if `docopt` will support an alias, instead of a second line:

```
   down, stop     Stop services

```

Once that's done, please squash your commits to a single commit.

We haven't discussed this much, but I think it probably doesn't hurt to have an alias if users find it more intuitive.

**Comment by dnephin** [comment]
I've been thinking about `stop` vs `down`, and I think `down`and `stop` are actually different.  Maybe we should implement a `down`, but I don't think it will be an alias of `stop` after all. I think `down` would also remove containers.

Let's continue the discussion in #2277

I'm going to close this PR for now, and we can revisit once the we've figured out the correct behaviour.

**Pull request closed without merging**
