### PR TITLE
Handle giving help a nonexistent command

### PR DESCRIPTION
**Pull request by dguo**
The CLI would show an unhandled exception when running: `$ docker-compose help foobar`

Now, it lists the commands.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM, but could probably be squashed to a single commit

**Comment by dguo** [comment]
No problem. I squashed them.

**Comment by dnephin** [comment]
LGTM

**Comment by dguo** [comment]
Hi, I rebased to fix the merge conflicts.

**Pull request merged**
