### PR TITLE
Add cpuset config.

### PR DESCRIPTION
**Pull request by xuxinkun**
Signed-off-by: xuxinkun <xuxinkun@gmail.com>

### CODE REVIEW

**Comment by aanand** [comment]
Needs documentation and tests.

**Comment by xuxinkun** [comment]
Add document and test about cpuset.

**Comment by aanand** [comment]
Thanks! Could you squash to one commit please?

**Comment by xuxinkun** [comment]
Ok, I merge the commits to one and make another pull request. See here https://github.com/docker/compose/pull/1331 , please check.

**Comment by dnephin** [comment]
Replaced by #1331

**Pull request closed without merging**
