### PR TITLE
.partition() is cleaner than .split() for getting both parts

### PR DESCRIPTION
**Pull request by cclauss**
Signed-off-by: Chris Clauss <cclauss@bluewin.ch>

### CODE REVIEW

**Comment by cclauss** [comment]
$ `git clone -b "patch-1" git@github.com:cclauss/compose.git somewhere`
Cloning into 'somewhere'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by aanand** [comment]
Thanks for the code cleanup.

1. Your first commit is unsigned; please either sign it or squash everything to a single signed commit.
2. Your commit messages don't include the fact that you've also changed some conditionals - please note that in the relevant commit.

It's not clear why you're getting permission errors but [this guide](https://help.github.com/articles/error-permission-denied-publickey/) might help.

**Comment by dnephin** [comment]
I like these changes, but you still need to flatten and sign the commit. Try this (assuming you already have a checkout):

```
git fetch --all
git rebase origin/master # If you've called the docker remote something else, replace origin
git rebase -i HEAD~2
# Change the second line to squash instead of edit
# remove the commit message that doesn't have the signoff
```

That should be it

**Comment by thaJeztah** [comment]
The permission denied is because of the `git@...`, try 

    git clone -b "patch-1" https://github.com/cclauss/compose.git somewhere

that should work, and do the same

**Comment by dnephin** [comment]
Closing due to lack of activity.

If you're still interested in contributing this change you'll need to rebase and re-open this PR.  Thanks!

**Pull request closed without merging**
