### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by justinwhite**
Removed a few lines to improve clarity and consistency of the documentation.

### CODE REVIEW

**Comment by aanand** [comment]
Thanks - good idea - but we've already got an overhaul to the front page waiting in https://github.com/docker/compose/pull/1200.

**Comment by justinwhite** [comment]
Gotcha. Missed that one. I think my beef was mostly with the `ADD . /code` because `/code` is mounted as a volume a few lines below. Thought it'd help avoid confusion.

**Comment by aanand** [comment]
Ah yes. We've got one open for that in https://github.com/docker/compose/pull/1186, but it's stalled. If the author doesn't have time to do the fixes we need, feel free to step in and finish it!

**Comment by dnephin** [comment]
Looks like we've already made a similar change http://docs.docker.com/compose/

Thanks for the contribution!

**Pull request closed without merging**
