### PR TITLE
Added uninstall documentation for pip and curl

### PR DESCRIPTION
**Pull request by AndyWendt**

### CODE REVIEW

**Comment by AndyWendt** [comment]
I'm fixing the issues

**Comment by AndyWendt** [comment]
I signed the commits

**Comment by AndyWendt** [comment]
I scanned through the jenkins log and I am not exactly sure what broke the build.  Any direction would be appreciated.

```
ERROR: test_no_change (tests.integration.state_test.BasicProjectTest)
Traceback (most recent call last):
  File "/code/tests/integration/testcases.py", line 20, in tearDown
    self.client.kill(c['Id'])
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 772, in kill
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot kill container 7f340b99a039a8be556431107a6cf072de98fd02cc53e1269c5b5e6dd8cda71f: [2] Container does not exist: container destroyed")

...

FAILED (errors=1)
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
[Compose-PRs] $ /bin/sh -xe /tmp/hudson8281483276407054001.sh
+ set +x

...

+ docker rm -f compose-prs752
Error response from daemon: no such id: compose-prs752
Error: failed to remove containers: [compose-prs752]

...



```

**Comment by aanand** [comment]
Thanks! That was an unrelated transient failure. Tests are green now.

LGTM

ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks Andy!!

I think there was an issue related to this as well that can be closed by this. Will look as soon as I get home

**Comment by AndyWendt** [comment]
@thaJeztah Great!  I see that the [Ubuntu install documentation](http://docs.docker.com/installation/ubuntulinux/) has markdown issues.  I am going to see what I can do to fix those and send another PR.

**Comment by thaJeztah** [comment]
@AndyWendt I *think* those are already fixed in "master" but not yet published on the live docs side, so be sure to check if the issue is still there in the files on GitHub.

Thanks for noticing though!

**Comment by AndyWendt** [comment]
@thaJeztah I cloned it down last night and found that out :smile: 

I will check the issues next time.

**Comment by thaJeztah** [comment]
@AndyWendt haha, yup. See it as a good excercise then :wink:

**Pull request merged**
