### PR TITLE
Fix Invalid Restart Policy

### LINKED ISSUE #3481: [1.7.1] Containers can be created with an invalid restart policy name
`docker-compose.yml`:

``` yaml
version: '2'
services:
  alpine:
    image: "alpine:latest"
    restart: unlesss-stopped
```

In the previous, `unlesss-stopped` is an invalid value for the restart policy name.

``` sh
sudo docker-compose up
```

Does not complain, and a container is created and started with an incorrect restart policy. Incorrect, based on `docker inspect` output.

 In contrast, this fails:

``` sh
sudo docker create --restart='unlesss-stopped' alpine
```

```
docker: invalid restart policy unlesss-stopped.
See 'docker create --help'.
```

**Context**

```
docker-compose version 1.7.1, build 6c29830
Docker version 1.11.1, build 5604cbe
```

### PR DESCRIPTION
**Pull request by johnharris85**
Fixes #3481.
Signed-off-by: John Harris <john@johnharris.io>

### CODE REVIEW

**Comment by johnharris85** [comment]
This look OK @dnephin @aanand ?

**Comment by dnephin** [comment]
see my comment in #3481. I don't think we should be duplicating the supported policies here.

**Comment by johnharris85** [comment]
Thanks @dnephin, only just saw it. Agree, I'll close.

**Comment by johnharris85** [comment]
I have submitted an initial PR crack at fixing this in the engine here https://github.com/docker/docker/pull/24073.

**Pull request closed without merging**
