### PR TITLE
revert commits link to mount API over bind changes

### LINKED ISSUE #12139: [BUG] Unable to bind mount when mount source is within the daemon root
### Description

After upgrading Compose v2.29.6 from v2.29.2, the following service began failing:

```
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
```

Running `docker compose up -d` gives the following error message:

```
Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/", propagation: "rprivate"
```

### Steps To Reproduce

_No response_

### Compose Version

```Text
Docker Compose version v2.29.6
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.3.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.6
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 26.1.3
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.657GiB
 Name: d4d8c60ee1fe
 ID: 186ebd80-8c59-49b8-92ae-007c1c620318
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glours**
**What I did**
I reverted the following commits:

- c16df17e1f2022c907a68b010f380bce53ac3e36
- cb00aaad288ff83ed98835a1edea635800f5b083
- f9c7a0cc085eba94d6140dcae18f16d7ef5a7691

**Related issue**

fixes #12139 #12140

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
image

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]
👍 
This experiment demonstrate `Mount` and `Bind` API are not equivalent, as mount require client to know about engine constraints (typically "_must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root_").
compse-go makes the assumption a bind can be safely expanded in to a mount, so the "long syntax", but actually this is wrong. We will have to manage this in compose-go in a better way, to really distinguish user intent to use mount-specific options. Maybe we should introduce a `mount` section and deprecate use of advanced volume attributes (like `subpath`) which are only supported by the `mount` API, to fully align with the docker CLI

**Comment by thaJeztah** [comment]
@ndeloof IIUC this worked on a bare Linux machine, but failed with desktop? Do we know what Desktop did that made it fail?

**Comment by prashant-shahi** [comment]
The previous release failed in my Linux machine.

**Comment by thaJeztah** [comment]
@prashant-shahi Yes; the long story was that;

1. https://github.com/docker/compose/commit/f9c7a0cc085eba94d6140dcae18f16d7ef5a7691 switched to using a different API (to replace a legacy API)
2. This caused an issue with Docker Desktop, which had some code-path related to mapping host <--> VM mounts that got triggered if no bind-propagation was set https://github.com/docker/compose/commit/cb00aaad288ff83ed98835a1edea635800f5b083
3. Which caused an issue for native Windows containers, because windows has no concept of "bind propagation"; so it was made conditional https://github.com/docker/compose/commit/c16df17e1f2022c907a68b010f380bce53ac3e36

Step `2.` chose to use `rprivate`, as it's the default that would be set by the daemon, so the assumption was that setting the same default on the client-side (compose) would be OK, but that default was not always applicable; a special exception existed on the daemon side to use `rshared` as a default when bind-mounting Docker's own storage location (`/var/lib/docker` by default). That special case is _NOT_ handled when the user ("compose" in this case) explicitly sets a propagation mode. It's also quite likely that exception was never documented (other than "in code"), and bind-mounting `/var/lib/docker` is generally not recommended and more a niche use-case (at least compose did not have tests for this). But for those that _did_ use this, an error was now produced by the daemon, which has a safeguard in place if an incorrect propagation is set;

```
Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/", propagation: "rprivate"
```

This PR reverts all of the above, pending changes in Docker Desktop to allow this again.

**Pull request merged**
