### PR TITLE
Update requests in requirements.txt

### PR DESCRIPTION
**Pull request by edi9999**

### CODE REVIEW

**Comment by brettdh** [comment]
This will conflict with #3376.

**Comment by edi9999** [comment]
Hello again @GordonTheTurtle, I just signed my commits. 

@brettdh PR seems to be stale, and the merge conflict will be obvious to solve, so I propose to merge this in first

**Comment by Kimamisa** [comment]
Can we re-run the tests on this PR ? It seems like the Jenkins history is not kept, and I'd like to know what failed (considering that the PR seems acceptable).

**Comment by edi9999** [comment]
I've rebased onto master and pushed so that the tests rerun now.

**Comment by edi9999** [comment]
Can someone merge this if it is ok ?

**Comment by edi9999** [comment]
Is they any chance that this will be merged sometime ?

**Comment by jgeerds** [comment]
`requests` 2.10 is outdated, see also #4431

**Pull request closed without merging**
