### PR TITLE
[WiP] Enable docker-compose for the latest compose-spec

### PR DESCRIPTION
**Pull request by EricHripko**
# Overview
This PR updates `docker-compose` with the latest version of the schema as specified by [compose-spec](https://github.com/compose-spec/compose-spec/blob/master/schema/config_schema_v3.9.json). This (among other things) enables `condition: service_healthy` to be used in v3 format. I've copied the minimum API/Docker versions from the current latest, as I don't think any new features rely on the newer API/daemon. Please feel free to correct me if not 🙈 

# Testing
- Manually verified that I am able to load a `docker-compose.yaml` with `version: '3.9'`

### CODE REVIEW

**Comment by EricHripko** [comment]
❌ Pre-commit hooks fail for the following reason:
- Seems like `flake8` was updated with new checks, these lint issues are fixed in another PR of mine: #7457.
- Schema from `compose-spec` includes trailing whitespaces, these lint issues are fixed here: https://github.com/compose-spec/compose-spec/pull/79

**Comment by ndeloof** [comment]
@EricHripko schema on compose-spec is **not** version 3.9, this is a WiP.
We still have to define how we plan to release schema versions, and get them used by tools like docker CLI and docker-compose. Or maybe consider https://github.com/compose-spec/compose-spec/issues/13

**Comment by ulyssessouza** [comment]
Hello @EricHripko, about the CI, https://github.com/docker/compose/pull/7473 will fix this, then you just need to rebase it after it's merged.
Considering @ndeloof's comment I will convert this PR to a draft PR just to mark it.

**Comment by EricHripko** [comment]
Makes sense - thank you 👍 I'll rebase my PRs once your fix lands

**Comment by EricHripko** [comment]
Based on the issue mentioned by @ndeloof above, pivoting to require no version.

**Comment by EricHripko** [comment]
The associated [compose-spec change](https://github.com/compose-spec/compose-spec/pull/82) was landed, so gonna mark this PR as ready 🙂

**Comment by ndeloof** [comment]
compose-spec json schema should not be set a `3.9`, especially now that we adopted https://github.com/compose-spec/compose-spec/issues/13

Please also not spec is not yet ready for this, as it does not (yet) include all v2 attributes. For this reason I marked this PR as "Work in Progress"

**Comment by EricHripko** [comment]
@ndeloof - thanks for pointing that out, I'll update the schema to name no version.

I've checked the [PRs on the spec](https://github.com/compose-spec/compose-spec/pulls) and can't see anything v2-related pending. What attributes are remaining? How I can I help?

**Comment by ndeloof** [comment]
I need to double check the possibly missing v2 attributes, at least we need to clarify expectation about `extend` in compose-spec

**Comment by EricHripko** [comment]
This is addressed by @aiordache in this PR: https://github.com/docker/compose/pull/7588. Since linked PR seems to have gotten more traction I'll close this one.

**Pull request closed without merging**
