### PR TITLE
Fixed broken links on pypi

### PR DESCRIPTION
**Pull request by michael-k**
The downside of this is, that `master`'s readme links to files in `release`.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

Just noticed the first link is actually broken now, it should be `overview.md`

**Comment by michael-k** [comment]
@dnephin I updated the commit

**Comment by michael-k** [comment]
Yeah, I do not see how I could have broken the test.

**Comment by dnephin** [comment]
LGTM, thanks!

The test failure is definitely unrelated.

**Comment by aanand** [comment]
LGTM

**Pull request merged**
