### PR TITLE
Add the git sha to version output

### LINKED ISSUE #2377: docker-compose version should show git hash
It would be nice if `docker-compose --version` showed also the Git SHA which the "binary" was compiled with.  Having some struggles with compiling Compose, I wanted to verify that I was in fact using the correct version.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #2377

cc @nathanleclaire

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice Dan!

**Comment by shin-** [comment]
LGTM!

**Comment by aanand** [comment]
Does this change preserve compatibility with the [completion installation commands](https://github.com/docker/compose/blob/master/docs/completion.md), which depend on the output of `docker-compose --version`?

**Comment by dnephin** [comment]
I don't see anything in the completion script that reads the `--version` output. I also tried them both out quickly, and didn't have any issues.

@albers did I miss something?

**Comment by aanand** [comment]
It's the installation instructions in `docs/completion.md` that I'm worried about - e.g. for bash:

     curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose

The `docker-compose --version | awk 'NR==1{print $NF}'` part might break if the output of `--version` changes.

**Comment by dnephin** [comment]
Oh, I missed that, sorry. 

It actually still works. The `awk` expression returns the short git sha, which is valid for that part of the url: https://raw.githubusercontent.com/docker/compose/e406702/contrib/completion/bash/docker-compose

**Comment by albers** [comment]
The download URL was constructed before `docker-compose version --short` existed.
I suggest to use that expression in the download URL. It's shorter and safer.

**Comment by albers** [comment]
created #2512

**Pull request merged**
