### PR TITLE
Fix flaky scale test

### PR DESCRIPTION
**Pull request by jhrotko**
## Problem
In compose there is one flaky test related to scale command. We are removing the latest created container when scaling down https://github.com/docker/compose/blob/07bda5960e07cb6ebee5beaa0c2ba0e42b788b13/pkg/compose/convergence.go#L129-L131

And in the test, might not necessarily be the 3rd service (`front-3`)
First we scale up two `front` services, and we do not know for sure which of `front-2` or `front-3` is going to be created first.
https://github.com/docker/compose/blob/b1c06770d49da1dbcaacf77fb347ae0e6f577f37/pkg/e2e/scale_test.go#L46-L52
https://github.com/docker/compose/blob/b1c06770d49da1dbcaacf77fb347ae0e6f577f37/pkg/e2e/scale_test.go#L63-L67

Running locally the commands this is a possible state:
image

Running `scale_test.go` several times it's possible to get failures locally.
The proposed fix, keeps track of the containers creation order, and asserts if the last created container is the one removed, instead of expecting `scale-basic-tests-front-3` to be the one removed when scaling down.
Note:
in Go there is no lookahead forward/behind, so the regex rule had to be more hacky.

**Related issue**
https://github.com/docker/compose/pull/11473

**Work Item**
https://docker.atlassian.net/browse/COMP-435

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
image

### CODE REVIEW

**Comment by ndeloof** [comment]
might relate to https://github.com/docker/compose/pull/11473

**Comment by laurazard** [comment]
So I don't have full context, but I was looking at https://github.com/docker/compose/blob/d714a2ebee08a697a40efacc93272b89b8fcad49/pkg/e2e/scale_test.go#L102 and https://github.com/docker/compose/pull/11473 and I got the idea that when scaling down, under normal circumstances we shouldn't fall back to using created time and should be using the container number, so this would be deterministic.

Did I get this wrong, or did we do something wrong with https://github.com/docker/compose/pull/11473 and we're falling back to creation date?

**Review by ndeloof — APPROVED** [review]

**Review by milas — COMMENTED** [review]
No concern with the actual code changes but same question as @laurazard - shouldn't the fix from #11473 mean this is not necessary anymore?

**Comment by jhrotko** [comment]
@laurazard  @milas I retested with @ndeloof and it seems it is not flaky anymore

**Pull request closed without merging**
