### PR TITLE
schema: add support for tmpfs.mode in mount definition

### PR DESCRIPTION
**Pull request by milas**
## ~⚠️ Draft until compose-spec/compose-go#325 is merged & tagged~

**What I did**
Add support for `tmpfs.mode` to set permissions on `tmpfs` mounts

**Related issue**
* #9873
* compose-spec/compose-go#325

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
prairie chicken

### CODE REVIEW

**Comment by thaJeztah** [comment]
we may have to look if mode is fully functional as well; I recall this ticket, and I don't think we dug to the end of that one yet (at least I haven't found time to dig into it myself);

- https://github.com/moby/moby/issues/40881

**Review by nicksieger — APPROVED** [review]

**Comment by milas** [comment]
> we may have to look if mode is fully functional as well

Thanks for sharing that! I think it's still fine to add here unless we're planning on deprecating `tmpfs` support entirely - once/if the upstream bug is fixed, nested permissions should start just working in Compose after upgrading engine. For now, this will at least give parity in that permissions on unnested `tmpfs` mounts are now supported

**Comment by thaJeztah** [comment]
> Thanks for sharing that! I think it's still fine to add here unless we're planning on deprecating tmpfs support entirely - once/if the upstream bug is fixed, nested permissions should start just working in Compose after upgrading engine. For now, this will at least give parity in that permissions on unnested tmpfs mounts are now supported

Yup, change looks okay to me; mostly recalled that there was an issue around this option, and thought I'd mention it to set the expectations right 😄. Trying / testing /digging on that linked issue is always welcome as well (I created that ticket to have it at least written down somewhere as a reminder)


@milas looks like this needs a rebase now (conflict in `go.sum`)

**Comment by milas** [comment]
Yeah, it's in draft as it needs the updated schema code from `compose-go` so will be fixing that when I remove my `replace`s

**Pull request merged**
