### PR TITLE
Fix exit code 0 upon parallel pull failure.

### PR DESCRIPTION
**Pull request by aronahl**
Implements enhancement #5091.

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! Would you mind adding a test for it as well?

**Comment by aronahl** [comment]
Sure.

**Comment by aronahl** [comment]
I added it to the same place I found the other pull tests in cli_test.py.

Do hash-dibs comments work for claiming issues in this repository?

**Comment by shin-** [comment]
LGTM - thank you!

> Do hash-dibs comments work for claiming issues in this repository?

Hmm, I don't think so, why?

**Comment by aronahl** [comment]
I was just curious as to a way to own any other bug that might come up so that I don't duplicate work.  The contributing doc points to a parent spec for moby that refers to the bot for assignments.

**Pull request merged**
