### PR TITLE
Add support for squash in build definition

### LINKED ISSUE #4235: Add support for the --squash flag
See https://github.com/docker/docker/pull/22641

### PR DESCRIPTION
**Pull request by shin-**
Fix #4235

### CODE REVIEW

**Comment by shin-** [comment]
cc @dnephin Is it too late to add this to the 3.4 definition?

**Comment by dnephin** [comment]
We should still have time to add it.

Squash is experimental, and now that multi-stage build exists there was talk of removing it instead of making it non-experimental, so maybe we shouldn't support it?

**Comment by shin-** [comment]
Oh, i was not aware. Do you know if there's a public issue discussing the removal?

In any case, I will shelf this until we have a decision then.

**Comment by dnephin** [comment]
I don't think there was an open issue yet, just comments in other related issues, so I created https://github.com/moby/moby/issues/34565.

**Pull request closed without merging**
