### PR TITLE
fix: The correct number is displayed

### PR DESCRIPTION
**Pull request by Goryudyuma**
Resolves https://github.com/docker/compose/issues/6740

### CODE REVIEW

**Comment by ulyssessouza** [comment]
Hello @Goryudyuma! Thank you for the contribution!

Please rebase with the `master` branch to get the CI problem fixed.

**Comment by Goryudyuma** [comment]
ok~, please wait.

**Comment by Goryudyuma** [comment]
I wrote test for this fix on `tests/unit/cli/utils_test.py`, but i found test for `unquote_path` in this file.
`human_readable_file_size` is in `compose.cli.utils`, but `unquote_path` is in `compose.utils`.
I think that `unquote_path` 's test should be in `tests/unit/utils_test.py` .

What should I do?

**Comment by ulyssessouza** [comment]
The placement of the tests should ideally mirror the placement of the tested code.
A little help on your PR, please invert the order of the imports from:
```
from compose.utils import unquote_path
from compose.cli.utils import human_readable_file_size
```
to:
```
from compose.cli.utils import human_readable_file_size
from compose.utils import unquote_path
```

And also, please add tests for all the possibilities in the function (B, KB, MB, GB, TB, PB and EB)

**Pull request merged**
