### PR TITLE
Add 'socks' extra to help with proxied environments

### LINKED ISSUE #4895: Compose exits with "Missing dependencies for SOCKS support"
Hi there! Ran into a bit of an issue with docker-compose 1.13.0, build 1719ceb. In my test the issue goes back to at least 1.11.0.

A script I'm running does `docker-compose down`, which results in an uncaught exception that ends with the line: "requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.":

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 358, in down
  File "compose/project.py", line 286, in down
  File "compose/project.py", line 252, in stop
  File "compose/project.py", line 498, in containers
  File "compose/project.py", line 489, in _labeled_containers
  File "site-packages/docker/api/container.py", line 189, in containers
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/api/client.py", line 183, in _get
  File "site-packages/requests/sessions.py", line 488, in get
  File "site-packages/requests/sessions.py", line 475, in request
  File "site-packages/requests/sessions.py", line 596, in send
  File "site-packages/requests/adapters.py", line 390, in send
  File "site-packages/docker/transport/ssladapter.py", line 56, in get_connection
  File "site-packages/requests/adapters.py", line 290, in get_connection
  File "site-packages/requests/adapters.py", line 184, in proxy_manager_for
  File "site-packages/requests/adapters.py", line 43, in SOCKSProxyManager
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```

I'm running through docker machine and nothing in the docker compose yaml even mentions socks.

The script that wraps the docker-compose does set `ALL_PROXY`, which I think may be causing `requests` or some other library to eagerly load socks support. 

My recommendation would be to add `requests[socks]` to the setup.py and call it good.

### PR DESCRIPTION
**Pull request by shin-**
- Fixes #4895 
- SOCKS support will be included in the bundled (binary) version
- Update some packages in requirements.txt and add some implicit deps

cc @cyli

### CODE REVIEW

**Comment by cyli** [comment]
Unfortunately this probably runs into the same issue that I had here:  https://github.com/docker/docker-py/pull/1563/files#diff-2eeaed663bd0d25b7e608891384b7298R42

If you `pip install requests` and also `pip install requests[socks]`, the PySocks package (which seems to be what also gets installed if you specify `requests[socks]`: https://github.com/requests/requests/blob/master/setup.py#L97) does not actually get installed (see https://github.com/pypa/pip/issues/4391 and https://github.com/pypa/pip/issues/988#issuecomment-303190524)

May need to manually include the `PySocks` package :|

```
$  python setup.py bdist_wheel
...
$  cd ../
$  virtualenv /tmp/socks && source /tmp/socks/bin/activate
...
$  pip install compose/dist/docker_compose-1.15.0.dev0-py2.py3-none-any.whl[socks]
...
$  pip freeze | grep PySocks
$  # there was no output
```

**Comment by shin-** [comment]
@cyli Thank you! I updated the PR to include PySocks in the `setup.py` file directly.

**Comment by cyli** [comment]
@shin- Thanks, LGTM!  Using the updated branch, and the same process as above:

```
$  pip freeze | grep PySocks
PySocks==1.6.7
```

**Comment by moshez** [comment]
Thanks a lot!

**Pull request merged**
