### PR TITLE
First implementation of `viz` subcommand

### LINKED ISSUE #10364: [Feature request]: Generate visual representation (graph) of compose file
### Description

It would be nice if we could see a visual representation of our services declared in the YAML config.

To achieve that we generate graphviz code based on the YAML configuration, and then let the user convert that code to any format she/he wants or even modify it to suit their needs.

## Example

Let's say this is our config file:

```yaml
version: "3.9"
services:
  service1:
    image: guzmanbenjamin/service1
    networks:
      - internal-net

  service2:
    image: guzmanbenjamin/service2
    networks:
      - internal-net
    depends_on:
      - service1
      - postgres
      - mongo

  postgres:
    image: postgres
    networks:
      - internal-net

  mongo:
    image: mongo
    command: --auth
    networks:
      - internal-net

  gateway:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
      - "443:443"
    networks:
      - internal-net
      - public-net
    depends_on:
      - service1
      - service2

networks:
  internal-net:
    external: true
  public-net:
    driver: bridge
    enable_ipv6: true
```

Then, it would be nice if a subcommand existed, let's name it `viz` such that when running

```shell
docker compose viz
```

The following graphviz code is generated

```
digraph {
    service1 [style="filled" fillcolor="burlywood1" label=<<font point-size="15">service1</font><br/><font point-size="10">internal-net</font>>]
    service2 [style="filled" fillcolor="aquamarine" label=<<font point-size="15">service2</font><br/><font point-size="10">internal-net</font>>]
    postgres [style="filled" fillcolor="burlywood1" label=<<font point-size="15">postgres</font><br/><font point-size="10">internal-net</font>>]
    mongo [style="filled" fillcolor="burlywood1" label=<<font point-size="15">mongo</font><br/><font point-size="10">internal-net</font>>]
    gateway [style="filled" fillcolor="lightslateblue" label=<<font point-size="15">gateway</font><br/><font point-size="10">internal-net<br/>public-net<br/>127.0.0.1:80:80<br/>443:443</font>>]

    service2 -> service1
    service2 -> mongo
    service2 -> postgres
    gateway -> service1
    gateway -> service2
}
```

And, finally, when running graphviz tools such as `dot`, this image is generated.

example

Excuse my color selection, but that's exactly what user may be able to customize with options.

List of subcommand options proposed:

- `--network <bool>`: Include the name(s) of the network(s) a service is attached to.
- `--ports <bool>`: Include the exposed port(s) of a service.
- `--image <bool>`: Include the image used to instantiate the container.

Also, more options may be included to configure the graph design such as:

- `--color <string>`: Define how to color nodes in graph. Examples: `depth;red,#00ff00,blue` would color level 1 nodes in red, then level 2 nodes in green, and level 3 nodes in blue. Or, `network;internal-net=pink,public-net=red` would color nodes attached to internal-net red, and so on...
- `--layout <string>`: Define the [layout](https://graphviz.org/docs/layouts/) of the graph. Examples: `twopi`, `circo`.

### PR DESCRIPTION
**Pull request by BenjaminGuzman**
**What I did**
Added `viz` subcommand within `alpha` subcommand.

For example, with `viz` subcommand you can now generate the following graph

out

from the following configuration

```yaml
version: "3.9"
services:
  service1:
    image: guzmanbenjamin/service1
    networks:
      - internal-net

  service2:
    image: guzmanbenjamin/service2
    networks:
      - internal-net
    depends_on:
      - service1
      - postgres
      - mongo

  postgres:
    image: postgres
    networks:
      - internal-net

  mongo:
    image: mongo
    command: --auth
    networks:
      - internal-net

  gateway:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
      - "443:443"
    networks:
      - internal-net
      - public-net
    depends_on:
      - service1
      - service2

networks:
  internal-net:
    external: true
  public-net:
    driver: bridge
    enable_ipv6: true
```

by running

```shell
docker compose alpha viz --ports --networks | dot -Tsvg
```

**Related issue**
closes #10364

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]

**Comment by BenjaminGuzman** [comment]
Hi, sorry if this is a dumb question but, what do I have to do to pass the validate-docs check?

I tried running locally `make docs` and then `make validate-docs` but it failed because some doc files were added (docs/reference/compose_alpha_viz.md, docs/reference/docker_compose_alpha_viz.yaml) and others were modified (docs/reference/compose_alpha.md, docs/reference/docker_compose_alpha.yaml), but I think that's OK since `viz` subcommand is new.

**Comment by glours** [comment]
@BenjaminGuzman you have to generate the doc with `make docs` then commit the changes before doing `make validate-docs`

**Comment by glours** [comment]
Hello @BenjaminGuzman 
I did some test with your branch and I found an issue when the project name contains `-` 
```shell
~/sources/compose/bin/build/docker-compose compose alpha viz
viz command is EXPERIMENTAL
digraph nginx-golang-mysql {
	layout=dot;
	"backend" [style="filled" label=<<font point-size="15">backend</font>>];
	"db" [style="filled" label=<<font point-size="15">db</font>>];
	"proxy" [style="filled" label=<<font point-size="15">proxy</font>>];

	"proxy" -> "backend";
	"backend" -> "db";
}

> ~/sources/compose/bin/build/docker-compose compose alpha viz | dot -Tsvg
viz command is EXPERIMENTAL
Error: <stdin>: syntax error in line 1 near '-'
```

Looking a DOT language format, it seems `-` can't be used,  maybe just adding  the project name between quotes will be sufficient to avoid this kind of issue.

> An ID is one of the following:
>
> * Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits([0-9]), not beginning with a digit;
> * a numeral [-]?(.[0-9]⁺ | [0-9]⁺(.[0-9]*)? );
> * any double-quoted string ("...") possibly containing escaped quotes (\")¹;
>  * an HTML string (<...>).

**Comment by BenjaminGuzman** [comment]
Thanks for pointing that out @glours 👍, I've already added a fix

**Review by glours — APPROVED** [review]
LGTM

**Comment by ndeloof** [comment]
Considering this is an `alpha` command so we can tweak the UX before making this a top-level feature, I'm going to merge this PR so we can get early adopters to give us some feedback.

Thanks a lot for working on this @BenjaminGuzman

**Pull request merged**
