### PR TITLE
Add docker build --pull command.

### PR DESCRIPTION
**Pull request by glogiotatidis**
This waits for https://github.com/docker/docker-py/pull/624

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Interestingly `docker-py` defaults to `pull=True`. I suggested that this gets changed to match docker cli https://github.com/docker/docker-py/issues/622. 

Even more interestingly `pull=True` does not work. I reported the issue here https://github.com/docker/docker/issues/13631.

**Comment by dnephin** [comment]
Resolves #726 and will replace #731

**Comment by dnephin** [comment]
Looks like the latest build is reporting a syntax error, but I don't see it in the diff. If you have a chance to rebase this on master, it would be good to get this in.

**Comment by thaJeztah** [comment]
I see tests are still failing;

```
compose/service.py - Could not parse ast

	Traceback (most recent call last):
	  File "/tmp/.pre-commit/repo7MclqR/py_env-default/lib/python2.7/site-packages/pre_commit_hooks/debug_statement_hook.py", line 38, in check_file_for_debug_statements
	    ast_obj = ast.parse(open(filename).read(), filename=filename)
	  File "/usr/local/lib/python2.7/ast.py", line 37, in parse
	    return compile(source, filename, mode, PyCF_ONLY_AST)
	  File "compose/service.py", line 725
	    pull=pull,
	SyntaxError: keyword argument repeated

Fix End of Files.........................................................Passed
Flake8...................................................................Failed
hookid: flake8

compose/service.py:725:1: E901 SyntaxError: keyword argument repeated
tests/integration/cli_test.py:116:6: F821 undefined name 'patch'
```

**Comment by glogiotatidis** [comment]
@thaJeztah code updated. I still get errors but I need a hint to fix them.

**Comment by dnephin** [comment]
@glogiotatidis don't worry about this error, we have it ticketed as #1922

LGTM

**Comment by dnephin** [comment]
Done in #2041

**Pull request closed without merging**
