### PR TITLE
schema 3.7: support the `runtime` key

### LINKED ISSUE #6239: Support `runtime` in v3.x compose files
## Description of the issue

The `runtime` option exists in v2.3, but not v3.x.

### PR DESCRIPTION
**Pull request by mathstuf**
This is in 2.3, but is not available in 3.x.

Signed-off-by: Ben Boeckel <mathstuf@gmail.com>

Resolves #6239

### CODE REVIEW

**Comment by mathstuf** [comment]
Not sure if this warrants a 3.8 or not.

**Comment by shin-** [comment]
Thanks for the submission!

As highlighted in the issue template, updates to the v3 format should start with a PR to the [docker/cli](https://github.com/docker/cli) repo, as it is the source of truth for v3. And yes, this will warrant a minor version bump!

**Comment by ijc** [comment]
@mathstuf As shin- says, please fix this in https://github.com/docker/cli first, then it can be sync'd over in a PR similar to e.g. https://github.com/docker/compose/pull/6642. I'll close this in anticipation of a replacement syncing over a change from https://github.com/docker/cli.

**Comment by khimaros** [comment]
Was this picked up in another PR? Looking at [the 3.8 schema](https://github.com/docker/compose/blob/master/compose/config/config_schema_v3.8.json), the `runtime` option still does not appear to be supported.

**Pull request closed without merging**
