### PR TITLE
'run' command can use network aliases for service

### PR DESCRIPTION
**Pull request by geigerzaehler**
This PR adds an `--use-alias` option to the `run` command that will add the service network aliases to the container. This is something request in #3492.

### CODE REVIEW

**Comment by geigerzaehler** [comment]
Rebased it again

**Comment by kingbuzzman** [comment]
For those of you that want to test this out AND are using docker-for-mac. Wrote this for my company's docs to get this working in the meantime, it makes a copy of the original `docker-compose` binary, installs a `virtualenv` directory into the docker path, installs _THIS_ version of `docker-compose` and done!, im sure it will be beneficial:

```
# If the backup does not exists ...
([[ -f /Applications/Docker.app/Contents/Resources/bin/docker-compose.bk ]] && echo 'Installed already!') || (
# Make a backup of the original docker-compose binary
mv /Applications/Docker.app/Contents/Resources/bin/docker-compose /Applications/Docker.app/Contents/Resources/bin/docker-compose.bk && \
# Install a virtualenv and the newer version of docker-compose
virtualenv /Applications/Docker.app/Contents/Resources/pyenv && \
/Applications/Docker.app/Contents/Resources/pyenv/bin/pip install git+https://github.com/geigerzaehler/compose@run-with-network-alias && \
# Link the new binary
ln -s ../pyenv/bin/docker-compose /Applications/Docker.app/Contents/Resources/bin/docker-compose && echo 'Done!')
```

_To uninstall:_
```
# Remove the virtualenv
rm -rf /Applications/Docker.app/Contents/Resources/pyenv && \
# Move the original binary back to its original place
mv /Applications/Docker.app/Contents/Resources/bin/docker-compose.bk /Applications/Docker.app/Contents/Resources/bin/docker-compose
```

**Comment by kingbuzzman** [comment]
Bump.

**Comment by kingbuzzman** [comment]
Bump.

**Comment by samcday** [comment]
Bump! I'd love this feature too.

**Comment by kingbuzzman** [comment]
Bump.

**Comment by nickswiss** [comment]
bump

**Comment by kingbuzzman** [comment]
Is it me or is this not needed any more?

steps:
1. `docker-compose down` <- make sure there is nothing running
2. `docker rm $(docker ps -a)` <- make REAL sure nothing is running
3. `docker-compose run --no-deps --service-ports MYAPPNAME bash` <- run my app without anything else
3.1. ```# psql
psql: could not translate host name "postgres" to address: Name or service not known```
       Note: my postgres is indeed not running
4. (new tab) `docker-compose run -d postgres`
5. (back to original tab) `psql`
6. profit!?!?!?!

Looks like it works without this. Can some one confirm. (using docker for mac)

```
$ docker --version
Docker version 17.06.1-ce, build 874a737
$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

**Comment by kingbuzzman** [comment]
@geigerzaehler Can you confirm it working without your PR?

**Comment by kingbuzzman** [comment]
@geigerzaehler can you sync with master?

**Comment by Vanuan** [comment]
I've been using `--name` (which implements deprecated behavior). This looks like a better fit for my use case.

**Comment by Vanuan** [comment]
Wait, the sole purpose of this flag is to enable aliases already provided in a compose file? But isn't it already works by default?

**Comment by kingbuzzman** [comment]
@Vanuan Sadly, no

**Comment by Vanuan** [comment]
Well, I've tested it here and it seems to work:
https://github.com/docker/compose/issues/5147#issuecomment-326461774

**Comment by kingbuzzman** [comment]
@Vanuan indeed works. Is this PR for not then?!

**Comment by Vanuan** [comment]
So this flag is true by default and the flag will be able to switch it off?

**Comment by geigerzaehler** [comment]
#5147 and the `--name` option do not address the issue this this PR tries to solve.

Containers started with `docker-compose run --use-alias SERVICE` should make all networks aliases defined for the service in `docker-compose.yml` (this includes the service name) available to all other containers managed by docker-compose for the given project.

**Comment by Vanuan** [comment]
> all networks aliases defined for the service
> available to all other containers

So, isn't that the default behavior? Could you post an example?
Here's what I see. Given the following service:
```
    master:
        command: sh -c "sleep 1; ping slave1"
        depends_on:
            - slave
        image: busybox
        networks:
            internal:
               aliases:
                 - master1
```

And the following command:
```
docker-compose run master
```

slave will be able to resolve master service by "master1" name.
What would be different with --use-alias? Are you saying that `internal: aliases: master1` part would not be required?

**Pull request closed without merging**
