### PR TITLE
Add support for JSON configuration files

### PR DESCRIPTION
**Pull request by dancrumb**
I switched over to crane because of a Fig issue and have invested heavily in JSON configuration files.

I'd like to start using Fig again, but switching from JSON to YAML will be a pain.

It seems pretty trivial for Fig to support JSON as well as YAML for input file format. Thence this Pull Request.

### CODE REVIEW

**Comment by jerem** [comment]
JSON is a subset of YAML so this should already work out of the box with the current YAML parser.

**Comment by dancrumb** [comment]
Parsing the file is actually the smallest part of this change.
Also, since invalid JSON files can be valid YAML files and valid JSON files with duplicate IDs are not valid JSON files, I think using a YAML parser on JSON could cause confusion down the line with no added benefit.

**Comment by atrauzzi** [comment]
:+1: for JSON configs

**Comment by dnephin** [comment]
Since the Yaml parser supports JSON documents I'm reluctant to make any code changes here.  It might be worth mentioning in the docs that you can use JSON, it's just "not considered a supported feature, even thought it should work in most cases".

**Comment by dnephin** [comment]
This will be documented in #2291

**Pull request closed without merging**
