### PR TITLE
Contributors can build public docs with compose docs in context

### PR DESCRIPTION
**Pull request by moxiegirl**
- Copy down all the other public repo docs and build
- Changed base image
- Users building compose docs can see their changes in the context of the entire docs.docker.com

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by aanand** [comment]
LGTM

**Comment by aanand** [comment]
Scratch that - `script/docs` is no longer working for me (I get `/bin/sh: 1: /src/pre-process.sh: not found` during the build step). Is it still the right way to build the docs?

**Comment by moxiegirl** [comment]
@aanand script/docs looks like something that was used to support mkdocs.  To build documentation, go to docs directory and type `make docs`

**Comment by aanand** [comment]
Okay. I'll remove it in a separate PR.

**Comment by moxiegirl** [comment]
Thanks @aanand

**Pull request merged**
