### PR TITLE
introduce config --images-to-build

### PR DESCRIPTION
**Pull request by abdennour**
**What I did**
Ability to filter images by services which uses built images
implement proposal of #8994 , exactly, option 1

**Related issue**

#8994

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**

### CODE REVIEW

**Comment by abdennour** [comment]
@ndeloof  
> First-time contributors need a maintainer to approve running workflows.
please help to approve @ndeloof @mat007 @glours 

image

**Comment by ndeloof** [comment]
code looks good, but I'm not fan for adding an option that only applies to the `--config` pseudo-command (which should be a subcommand), as this would be confusing and not apply to other (pseudo-)commands.
Maybe time to introduce `compose config images` as a **real** subcommand which could define it's own options?

**Review by glours — CHANGES_REQUESTED** [review]
It doesn't work as defined in the scenario 2 of #8995 
```sh
> ./bin/docker-compose compose -f ~/sources/awesome-compose/nginx-golang/docker-compose.yml convert --only-built
services:
  backend:
    build:
      context: /Users/glours/sources/awesome-compose/nginx-golang/backend
      dockerfile: Dockerfile
    networks:
      default: null
  frontend:
    build:
      context: /Users/glours/sources/awesome-compose/nginx-golang/frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 80
      protocol: tcp
networks:
  default:
    name: nginx-golang_default
> ./bin/docker-compose compose -f ~/sources/awesome-compose/nginx-golang/docker-compose.yml convert --volumes --only-built
~/sources/compose 8994-convert-built-images >
```

I was able to use the flag alone and I was also able to pass it to an unrelated flag such as `--volumes`

**Comment by abdennour** [comment]
Scenario 2 requires a lot of development. 
- Should i finish the combination with other flags one by one ?
- Or just revert to Scenario 1 ?
- Or go with new scenario of @ndeloof  (`docker compose config images` ) ?

@glours @ndeloof  any team decision, so i can proceed?

**Comment by ndeloof** [comment]
A possible issue with my proposed solution is that `compose config` accept a list of `services` as arguments, and introducing sub-commands would conflict with this usage or forbid use of some reserved names as services :'(

No strong opinion yet on the best approach, need to think twice about it

**Comment by abdennour** [comment]
Yep! @ndeloof  , Think about `--only-built` as adjective for services , as global option.
that time, filtering will happen at the level of `project.Services` or `project.WithServices`
Does it make sense!

**Comment by ndeloof** [comment]
Got it, make sense.

**Comment by abdennour** [comment]
Also, @ndeloof we can go **agile** : releasing `config --built-images` , then think about refactoring/re-organizing.

**Comment by abdennour** [comment]
@ndeloof  @glours , since adding new flag depends on `--images` flag requires redesign, i just pushed now the option (1) which is a new flag without dependency to others

`docker compose config --built-images`

I would suggest to accept this feature as incremental release , and with motivation to go AGILE.
Later on, we can think about refactoring this subcommand , indeed, you have already `--resolve-image-disgests`, which should belong to subsubcommand images since long time

**Comment by glours** [comment]
@abdennour 

I don't think we should accept this incremental step and I'll explain why
Compose is a wildy used project, if we introduce a new command or a new flag this new feature will be quickly used to script some bots or used in CI flows and then we'll be block (or it'll a least been painful) to remove this "temporary" increment. 
This is typically the kind of behaviour which drive a project to feature overload.

I really prefer that we took few days to think to a proper solution instead of rushing.

**Comment by ndeloof** [comment]
I tend to agree. Agile != "let's add random stuff and change our mind any time", especially when it comes to UX. Once we introduce a new flag, it will be there forever.

**Comment by abdennour** [comment]
Totally agree @glours @ndeloof , this is INTERFACE design pattern & it should be stable by Design.
BTW, i am not blocked @glours , as i forked it and i released the feature in the fork: https://github.com/ElmCompany/compose/releases/tag/v2.2.3

**Comment by abdennour** [comment]
Reminder @ndeloof @glours

**Comment by abdennour** [comment]
@ndeloof  @glours  i made the change as per my comment here https://github.com/docker/compose/issues/8994#issuecomment-996905644
It should be acceptable now.
Let me know if you need any change

**Comment by abdennour** [comment]
I really want to know if you need anything in order to approve/merge/release this PR.
@ndeloof @glours Kind reminder !!

**Comment by abdennour** [comment]
@glours You are requested for review.
@ndeloof  who is the backup of @glours

**Comment by abdennour** [comment]
I really want to know if you need anything in order to approve/merge/release this PR.
@ndeloof @glours  Kind reminder !!

**Comment by glours** [comment]
Hello @abdennour 

Sorry for the delay of the response.
I still prefer the option of having a dedicated `compose config images` [option mentioned](https://github.com/docker/compose/issues/8994#issuecomment-986009381) by @ndeloof 
With the holidays period we didn't have time to talk about this option internally ATM.
cc @ulyssessouza FYI

**Pull request closed without merging**
