### PR TITLE
Remove custom docs script

### PR DESCRIPTION
**Pull request by aanand**
Pass straight through to `cd docs && make docs`.

ping @moxiegirl - I figured it was best to keep the script around so there's always one reliable way to build the docs, should the workflow ever change again.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@aanand The one reliable way going forward should be `make docs`.

**Comment by aanand** [comment]
OK, I've removed `script/docs`.

**Comment by moxiegirl** [comment]
Thanks!

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
