### PR TITLE
Implement 'labels' option

### PR DESCRIPTION
**Pull request by aanand**
Using unstable versions of docker-py (for label support) and requests, because docker-py requires a newer version but [this fix](https://github.com/kennethreitz/requests/pull/2533) hasn't landed yet.

Sadly, even after that fix, the binary still isn't working:

```
+ dist/docker-compose-Linux-x86_64 --version
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/code/build/docker-compose/out00-PYZ.pyz/compose", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 11, in <module>
ImportError: No module named docker.errors
```

Might be another weird requests/pyinstaller bug - going to see if I can produce a minimal failing test case outside of Compose.

### CODE REVIEW

**Comment by aanand** [comment]
Plot thickens: the binary builds fine on Jenkins. Sigh. Can anyone else successfully run `script/build-linux` locally on this branch?

**Comment by funkyfuture** [comment]
nope, unfortunately the build fails like yours.

**Comment by aanand** [comment]
Have upgraded to `requests==2.6.1`, but I'm still getting the same error locally.

@funkyfuture Thanks for checking. Could you try once more with the current commit?

**Comment by aanm** [comment]
```
...
Step 14 : ENTRYPOINT /usr/local/bin/docker-compose
 ---> Running in ebbc535559d6
 ---> 9826101aa1ad
Removing intermediate container ebbc535559d6
Successfully built 9826101aa1ad
++ pwd
+ docker run --rm --user=user --volume=/home/aanm/git-repos/go/src/github.com/noironetworks/compose:/code --entrypoint=script/build-linux-inner docker-compose
++ pwd
+ mkdir -p /code/dist
++ pwd
+ chmod 777 /code/dist
chmod: changing permissions of `/code/dist': Operation not permitted
```
Maybe it's my fault but the /code/dist was not created inside the compose directory.

**Comment by funkyfuture** [comment]
sorry, same here. tests are passing though.

fun fact: i was just noting down this pr as a predicate for another project.

**Comment by funkyfuture** [comment]
@aanm this doesn't happen on my box.

**Comment by dnephin** [comment]
I wonder if it would be easier to start looking at alternatives to pyinstaller. We've hit a few problems with it (py3 support, six version conflict, and now requests version conflict).  In https://github.com/docker/compose/issues/1051#issuecomment-76730135 I mentioned http://docs.python-guide.org/en/latest/shipping/freezing/  which seems to have a bunch of options for doing this.

**Comment by funkyfuture** [comment]
@dnephin the comparison table looks like `cx_freeze` is the only one beside `PyInstaller` that supports Linux, OS X, Windows and Python 3.

**Comment by aanand** [comment]
I can reproduce the problem outside Compose by trying to build a binary with just `import docker` in it, and installing docker-py from a Git URL (even if it's the commit for a stable, released version). Using `docker-py==1.1.0` fixes it (but obviously the code doesn't work / tests don't pass at that point, because there's no labels support in docker-py 1.1.0).

The easiest way to fix this right now - so that this and #1356 can be merged with confidence - might be to just get a docker-py release out with labels support, so we don't have to rely on Git URLs.

@shin-: any thoughts on that?

**Comment by funkyfuture** [comment]
what about bundling the `docker-py`-code for the time being?

**Comment by aanand** [comment]
\*re-reads https://github.com/docker/compose/pull/375 for old times' sake\*

laugh_crying_kristen_bell

**Comment by shin-** [comment]
docker-py 1.2.0 is in the works, there's only a few things left which I've listed here: https://github.com/docker/docker-py/milestones/1.2.0

Sorry, I realize it's long overdue!

**Comment by aanand** [comment]
Thanks! This is ready to go now.

ping @bfirsh @dnephin

**Comment by dnephin** [comment]
LGTM!

**Comment by thaJeztah** [comment]
Awesome! https://github.com/docker/swarm/pull/673

**Comment by aanand** [comment]
@thaJeztah Nice.

**Pull request merged**
