### PR TITLE
add support of environment secret during build step

### LINKED ISSUE #9606: Compose 2.6.1 build.secrets only supports file-based secrets
**Description**

Notice that https://github.com/docker/compose/pull/9553 would allow one to specify environment-based top level secrets such as 

```yaml
secrets:
  github_token:
    environment: GITHUB_TOKEN
```
But this does not seem to work when accessing such as secret during build `build.secrets`

**Steps to reproduce the issue:**

1. Create the following Dockerfile 
```dockerfile
FROM alpine
RUN --mount=type=secret,id=SOME_SECRET cat /run/secrets/SOME_SECRET
```
2. Create the following docker-compose.yml 
```yaml
version: "3.3"
services:
  service:
    build: 
      secrets:
        - SOME_SECRET
secrets:
  SOME_SECRET:
    environment: SOME_SECRET
```
3. Run `export SOME_SECRET=foo
3. Run `DOCKER_BUILDKIT=1 docker build --secret id=SOME_SECRET .`
4. Run `DOCKER_BUILDKIT=1 docker-compose build service`

**Describe the results you received:**

Step 4 was successful in building a docker image by reading `/run/secrets/SOME_SECRET` from host environment variable `SOME_SECRET`

Step 5 throws an error with `build.secrets only supports file-based secrets`

**Describe the results you expected:**

Both steps 4 and 5 should be able to build a docker image by reading `/run/secrets/SOME_SECRET` from host environment variable `SOME_SECRET`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.6.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 21
  Running: 16
  Paused: 0
  Stopped: 5
 Images: 26
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.182
 Operating System: Buildroot 2020.02.12
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: minikube
 ID: ZKWF:MDX4:GF5N:U252:6LVW:VVZS:FDAX:R22U:4I4O:XIJG:4HY3:4UEB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=hyperkit
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

### PR DESCRIPTION
**Pull request by glours**
**What I did**
Allow usage of secrets based on environment variables during the build step

**Related issue**
fixes #9606 

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

### CODE REVIEW

**Comment by peteryhwong** [comment]
Thanks @glours !

**Review by peteryhwong — APPROVED** [review]

**Review by milas — APPROVED** [review]

**Comment by LyleDavis** [comment]
@glours thanks for this, I was wondering why it wasn't working as I thought it would! Is there a schedule for when this will be released? Would be great to be able to use this at work rather than have to rely on random bash scripts that build things before compose gets there.

**Comment by maciek16180** [comment]
I am also interested when this fix will be released

**Comment by StefanScherer** [comment]
It is released in Compose 2.7.0 which also is part of Docker Desktop 4.11.0 that will be released today.

**Pull request merged**
