### PR TITLE
Add logging when initializing a volume.

### LINKED ISSUE #2849: docker-compose log should show the Volume creation
Hello,

when you create a network in docker-compose, you can see it in the log when the creation is done
`Creating network "contrib_default" with the default driver`

However, it's not the same for Volume.

I expect something like:

`Creating Volume "contrib_clair-data" with the default driver`

```
🐳 〔default〕➜  contrib git:(develop) docker-compose up -d
Creating network "contrib_default" with the default driver
Creating clair
Creating hyperclair_dev
Creating registry
Creating auth
Creating hyperclair
🐳 〔default〕➜  contrib git:(develop) docker volume ls
DRIVER              VOLUME NAME
local               90f7961046a7b545199d0e7cd739b25286d764bc6ee2c763bd6eb0147606e25b
local               11e10cfd723ad02c5136a14c61187854f7d5c2d02a8c0f6b37cd3ad41aec2e53
local               174022a4616e81395c5feb80a567e456c042a9d3984c7212193035e5182d1a40
local               46f40889b0bc99419650a6b098ebbf2717c742cdf9be961401559815af71a672
local               c6fd2336d72eef540a2e8e996f2c67043386eea7c163e37b0f5a261a0f511749
local               36a85ac92bfcc150dcc594f0a6a3327925af342f2aab840a9b6f7a900ca5e015
local               contrib_clair-data
local               2a88aad1fc5bc27dd87ddb207c47c20bd9dc9d7a5e2af5370047fd0ca483eb4c
local               78c6a7f594cfcf5d856311426786d762928bd675eba1dc5791f3b54c65ad7d41
local               5a207163e75caa3e48fb69663de6ca4b37c06db6d570ff10e24eb36182b4de58
```

### PR DESCRIPTION
**Pull request by shin-**
Fixes #2849

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
Strange flake8 error in CI:

```
Traceback (most recent call last):
  File "/tmp/.pre-commit/repoTLbQav/py_env-default/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/tmp/.pre-commit/repoTLbQav/py_env-default/lib/python2.7/site-packages/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/tmp/.pre-commit/repoTLbQav/py_env-default/lib/python2.7/site-packages/flake8/engine.py", line 236, in get_style_guide
    _disable_extensions(kwargs['parser'], options)
  File "/tmp/.pre-commit/repoTLbQav/py_env-default/lib/python2.7/site-packages/flake8/engine.py", line 219, in _disable_extensions
    enabled = set(_parse_multi_options(options.enabled_extensions))
AttributeError: Values instance has no attribute 'enabled_extensions'
```

**Comment by jonleighton** [comment]
Is this log message supposed to appear even when the volume already exists? It seems to do so, which makes things kind of noisy...

**Comment by dnephin** [comment]
Hmm, ya it looks like we only check  `if volume.exists()` in the case when it's external.

**Comment by KJTsanaktsidis** [comment]
+1 the message made me worry that I'd lost the existing data in the volume, but it's actually all good. Please don't print this when the volume already exists!

**Pull request merged**
