### PR TITLE
Clarifies key-dependency of dockerfile

### PR DESCRIPTION
**Pull request by funkyfuture**

### CODE REVIEW

**Comment by funkyfuture** [comment]
@GordonTheTurtle Do you know Mrs. Eliza?

Signed-off is amended.

**Comment by aanand** [comment]
Thanks!

I think it needs to say `Signed-off-by:` not `Signed-off:`

**Comment by funkyfuture** [comment]
nu aber.

**Comment by aanand** [comment]
LGTM

ping @moxiegirl

**Comment by mnowster** [comment]
Docs have changed a lot since this was first opened. Closing it in favour of https://github.com/docker/compose/pull/2274

**Pull request closed without merging**
