### PR TITLE
Add upgrade instructions for fig users to README

### PR DESCRIPTION
**Pull request by albers**
This addresses #1053 by adding a link to the Compose release notes right behind _Previously known as Fig_. The 1.1.0 release notes are perfectly suited for this purpose.

### CODE REVIEW

**Comment by albers** [comment]
rebased.

**Comment by thaJeztah** [comment]
lgtm (not a maintainer)

@aanand @dnephin I think it won't hurt to merge this (At least as a placeholder)?

**Comment by dnephin** [comment]
LGTM, seems like a good thing to have, although it conflicts with the addition of the build status , so will need a rebase

**Comment by albers** [comment]
@dnephin rebased.

**Comment by dnephin** [comment]
This would have been good to have, but now I think it's been long enough that most people have probably already migrated.  Going to close this PR.

**Comment by albers** [comment]
I agree.

**Comment by thaJeztah** [comment]
Thanks anyway for this, @albers! :-)

**Pull request closed without merging**
