### PR TITLE
Use original LD_LIBRARY_PATH when shelling out to credential stores

### LINKED ISSUE #5930: docker-compose cannot use gcloud credential helper on Linux (pyinstaller release)
## Description of the issue

`docker-compose pull` fails to retrieve images from Google Cloud Repository (using gcloud credential helper), with the following exception:
```
Pulling hello-world ... 
ERROR: gcloud failed to load: 'module' object has no attribute 'HTTPSConnection'
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import display
    from googlecloudsdk.calliope import display_taps
    from googlecloudsdk.core.resource import resource_printer_base
    from googlecloudsdk.core.resource import resource_projector
    from apitools.base.py import encoding as protorpc_encoding
    from apitools.base.py.base_api import *
    from apitools.base.py import http_wrapper
    import httplib2
    from httplib2.python2.httplib2 import *
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/bin/python2

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/

ERROR: for hello-world  Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "".',)
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 71, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['/usr/bin/docker-credential-gcloud', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 126, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 33, in get
  File "site-packages/dockerpycreds/store.py", line 84, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-gcloud exited with "".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 729, in pull
  File "compose/project.py", line 556, in pull
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/project.py", line 549, in pull_service
  File "compose/service.py", line 1163, in pull
  File "site-packages/docker/api/image.py", line 380, in pull
  File "site-packages/docker/auth.py", line 47, in get_config_header
  File "site-packages/docker/auth.py", line 94, in resolve_authconfig
  File "site-packages/docker/auth.py", line 143, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "".',)
[9076] Failed to execute script docker-compose
```

## Context information (for bug reports)

```
$ docker-compose --version
docker-compose version 1.21.1, build 5a3f1a3Output of "docker-compose version"
```

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24
```

```
$ docker-compose config
services:
  hello-world:
    image: gcr.io/library/hello-world
version: '3.0'
```

## Steps to reproduce the issue

After installing the Linux pyinstaller release:
```
wget -O $HOME/.local/bin/docker-compose https://github.com/docker/compose/releases/download/1.21.1/docker-compose-Linux-x86_64
chmod +x $HOME/.local/bin/docker-compose
```
and setting up gcloud credential helper in `~/.docker/config.json`:
```
{
  "credHelpers": {
    "gcr.io": "gcloud"
  }
}
```
Trying to pull images (`docker-compose pull`) for the following sample `docker-compose.yaml`:
```
version: "3"
services:
  hello-world:
    image: gcr.io/library/hello-world
```
fails with the above traceback.

## Additional information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

```
$ gcloud --version
Google Cloud SDK 200.0.0
alpha 2018.04.30
beta 2018.04.30
bq 2.0.33
core 2018.04.30
gsutil 4.31
```

### PR DESCRIPTION
**Pull request by shin-**
Fixes #5930

### CODE REVIEW

**Comment by shin-** [comment]
Artifacts:
Linux: https://1062-15045751-gh.circle-artifacts.com/0/docker-compose-Linux-x86_64
Darwin: https://1064-15045751-gh.circle-artifacts.com/0/docker-compose-Darwin-x86_64
Windows: https://ci.appveyor.com/api/buildjobs/xp5ra4dcjtj8r0a1/artifacts/dist%2Fdocker-compose-Windows-x86_64.exe

**Comment by falnyr** [comment]
Can confirm @shin- Thank you!

```
falnyr@pink-asus:/home/falnyr/Projects/docker-compose-test  $ ll
total 12M
-rwxrwxr-x 1 falnyr falnyr 12M Jun 14 11:40 docker-compose-artifact
-rw-rw-r-- 1 falnyr falnyr 273 Jun 14 11:46 docker-compose.yml
-rw-rw-r-- 1 falnyr falnyr  84 Jun 14 11:46 index.html
falnyr@pink-asus:/home/falnyr/Projects/docker-compose-test  $ ./docker-compose-artifact up
Creating network "docker-compose-test_default" with the default driver
Pulling web (gcr.io/my-gcr-123456/php:7.2-apache-postgres)...
7.2-apache-postgres: Pulling from my-gcr-123456/php
f2aa67a397c4: Already exists
c533bdb78a46: Already exists
65a7293804ac: Already exists
35a9c1f94aea: Already exists
651774c607cc: Already exists
7c01fbe5ed3d: Already exists
9ff29ed84bfc: Already exists
647feb0f6355: Already exists
0b9d1c540863: Already exists
3416ab5471ed: Already exists
246c5fc29b1a: Already exists
98923ca5a50a: Already exists
8931bc5b7082: Already exists
fb2e6680ec40: Already exists
36c71eb6672c: Already exists
bb1658459ec8: Pull complete
50f39ef70e03: Pull complete
0c404f34312f: Pull complete
f66863a523cd: Pull complete
b3941480d0ab: Pull complete
Digest: sha256:cd180528cb50ecdb1e6206369509b7cfa3f5adddd7879acab40f16b1b0813480
Status: Downloaded newer image for gcr.io/my-gcr-123456/php:7.2-apache-postgres
Creating test-web ... done
```

**Comment by berendo** [comment]
> Can confirm @shin- Thank you!

I can also confirm - and thanks from me as well!

**Comment by shin-** [comment]
@falnyr @berendo Thank you! 👍

**Comment by nirodg** [comment]
It worked on Ubuntu, thank you!

**Comment by jorgecuesta** [comment]
I work for me too in Xubuntu 18.10

**Pull request merged**
