### PR TITLE
Fixes #1135 - Use a new version of pyinstaller 3.2 to build a valid E…

### LINKED ISSUE #1135: Cannot open self /usr/bin/docker-compose or archive /usr/bin/docker-compose.pkg
I installed `docker-compose` on my server I reconnect later it said :

``` sh
Cannot open self /usr/bin/docker-compose or archive /usr/bin/docker-compose.pkg
```

I have to reinstall it all the time :/

Thanks for your help!

### PR DESCRIPTION
**Pull request by garthy**
…LF file to stop prelinking breaking compose

### CODE REVIEW

**Comment by dnephin** [comment]
If you sign your commit and the build is green then we can get this into 1.8

**Comment by dnephin** [comment]
Although it looks like the windows binary is broken with this change.

**Comment by garthy** [comment]
sorry can't test on windows so didn't catch this.

This failed due to https://github.com/pyinstaller/pyinstaller/issues/1976 Looks like it will be fixed in a later version.

But it looks like there is a strange issue with github reporting tags that don't exist in the docker/docker repo causing a test script to fail

**Comment by dnephin** [comment]
We've got #3558 open to use 3.2.1 once it gets released so going to close this PR.

**Pull request closed without merging**
