### PR TITLE
support specifying a tar file as context

### LINKED ISSUE #1209: Add support for pointing to tarball contexts in the 'build' parameter.
Since the docker client used by compose (docker-py) supports receiving externally generated tarballs as a parameter for its build() method, this alternative should be available in the project configuration file. i.e.:

> service:
> 
> > build: path/to/tarball.tar.gz

The  contents within the compressed file should pass the same level of validation as the currently supported directory paths (for example, 'there must be a Dockerfile at the root inside the tar archive'). Aside from that, the general idea is that the archive is some kind of externally validated artifact, auto-generated by a continuous integration stack, so there should be no need for parsing .dockerignore. 

If this sounds like a good idea I can start working on a PR (I already have an working prototype).

### PR DESCRIPTION
**Pull request by MichaelKim0407**
Resolves #1209 

Implemented the support for both docker-py and cli build. Very minimal changes were required since both docker-py and cli already support the behavior.

I probably need to add tests and documentation somewhere, which I haven't done yet. If anyone can point me to the correct locations, I'll be happy to add them

### CODE REVIEW

**Comment by benmosher** [comment]
is there a proper way to "bump" this? would love this feature. and I see that #1209 was recently closed for staleness.

**Comment by ndeloof** [comment]
Compose v1 is EoL, compose v2 codebase should be considered for new features

**Comment by glours** [comment]
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.

**Comment by MichaelKim0407** [comment]
Lol this PR was opened more than 2 years ago.

I'm not sure if I want to spend the effort to create another one if this is how it works here.

**Pull request closed without merging**
