### PR TITLE
add support for read_only parameter

### PR DESCRIPTION
**Pull request by lsde**
add support for specifying read_only flag as per https://github.com/docker/compose/issues/961

### CODE REVIEW

**Comment by aanand** [comment]
Nice, thanks! Needs a test, some documentation and your commit needs signing off.

**Comment by lsde** [comment]
ok, added test, simple docs and signed.

**Comment by lsde** [comment]
The problem is that Wrecker doesn't have 1.5 box to make tests pass, what would you propose to get this merged?

**Comment by dnephin** [comment]
This was done in #1335

**Pull request closed without merging**
