### PR TITLE
Fix byte/str typing error

### PR DESCRIPTION
**Pull request by sanmai-NL**
See #3576.

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! Change LGTM.
@aanand WDYT?

**Comment by aanand** [comment]
Will this break on Python 2?

**Comment by shin-** [comment]
In Python 2, `b'...'` and `'...'` are one and the same, right?

**Comment by aanand** [comment]
Usually, but we've got a `from __future__ import unicode_literals` at the top, so it'll be a Unicode string in both Python versions.

**Comment by shin-** [comment]
Ah, good point.
I just tested it in ipython and it seems to work fine either way.
Python 2:
```python
In [3]: sys.stdin.readline().rstrip('\n')
hello
Out[3]: 'hello'

In [4]: sys.stdin.readline().rstrip(u'\n')
hello
Out[4]: u'hello'
```

Python 3:
```python
In [3]: sys.stdin.readline().rstrip(b'\n')
hello
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-cefaff8b347e> in <module>()
----> 1 sys.stdin.readline().rstrip(b'\n')

TypeError: rstrip arg must be None or str

In [5]: sys.stdin.readline().rstrip(u'\n')
hello
Out[5]: 'hello'
```

Python 2 with `unicode_literals`:
```
In [1]: from __future__ import unicode_literals

In [2]: import sys

In [3]: sys.stdin.readline().rstrip('\n')
hi
Out[3]: u'hi'
```

**Comment by aanand** [comment]
Great. LGTM

**Pull request merged**
