### PR TITLE
Support --build-arg for build command

### PR DESCRIPTION
**Pull request by dattran-vn01**
Support --build-arg for build command. Discussed [here](https://github.com/docker/compose/issues/3790)

Signed-off-by: Dat Tran dattran.vn01@gmail.com

### CODE REVIEW

**Comment by shin-** [comment]
Fixed and merged in #4564 

Thank you for your help!

**Comment by prestonprice57** [comment]
HELP! I can't get this to work. It seems like 
`docker-compose build --build-arg -t customer-core-dev-container:latest .` 
should work but when I run that I get:

> Services are built once and then tagged as project_service,
> e.g. composetest_db. If you change a service's Dockerfile or the
> contents of its build directory, you can run docker-compose build to rebuild it.
> 
> Usage: build [options] [SERVICE...]
> 
> Options:
>     --force-rm  Always remove intermediate containers.
>     --no-cache  Do not use cache when building the image.
>     --pull      Always attempt to pull a newer version of the image.

I've tried various configurations for the command but I get this no matter what.

**Comment by shin-** [comment]
`docker-compose version`?

**Comment by prestonprice57** [comment]
I've tried with both version 2 and 3. From what I understand it should at least be supported in the latest release (3.3) right?

**Comment by prestonprice57** [comment]
Actually when I try using version 3.3 it says:
`ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0")`

Either way, it doesn't work with 2.0 or 3.0

**Comment by shin-** [comment]
No, like, literally, what's the output of the `docker-compose version` command?

**Comment by prestonprice57** [comment]
Oh duh. This is the output:

> docker-compose version 1.11.2, build dfed245
> docker-py version: 2.1.0
> CPython version: 2.7.12
> OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Comment by shin-** [comment]
@prestonprice57 `--build-arg` was added in [1.12.0](https://github.com/docker/compose/releases/tag/1.12.0).

**Comment by prestonprice57** [comment]
Oh okay that makes sense. I thought I had the latest version. Oops. Thanks for the help!

**Pull request closed without merging**
