### PR TITLE
Update zsh completion with last changes

### LINKED ISSUE #1912: Implement zsh completion for pause and unpause
Functionality added in https://github.com/docker/compose/pull/1766.

### PR DESCRIPTION
**Pull request by sdurrheimer**
Resolves #1912 

Ping @aanand

 - sdurrheimer/docker-compose-zsh-completion@4ff5c0d Add pause and unpause commands
 - sdurrheimer/docker-compose-zsh-completion@9948d66 Add -t/--timeout flag to scale command
 - sdurrheimer/docker-compose-zsh-completion@7cf14c8 Improve -p/--publish flag for the run command
 - sdurrheimer/docker-compose-zsh-completion@cb16818 Don't trigger expensive completion function for flags
 - sdurrheimer/docker-compose-zsh-completion@52d33fa Several cosmetic improvements and return responses
 - sdurrheimer/docker-compose-zsh-completion@632ca9c Bump to version 1.5.0
 - sdurrheimer/docker-compose-zsh-completion@22f92d9 Refactor compose file and project-name option flags when invoking docker-compose
 - sdurrheimer/docker-compose-zsh-completion@1b512fc Refactor --help flags

Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Comment by aanand** [comment]
LGTM. Thanks!

**Comment by dnephin** [comment]
I haven't used zsh much (it's on my todo list to try out!), but I installed the completions from this patch.  It seems to be working, except for pause/unpause. I don't see them in the list of commands when I try to complete.

Any idea why that would be?  I'm not getting any errors, and the rest of the changes here seem to be working (from what I can tell).

**Comment by sdurrheimer** [comment]
@dnephin docker-compose list of commands are coming by calling docker-compose itself and then cached (@see https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose#L152).
pause and unpause commands are not displaying because they are not listed in the docker-compose commands list.

**Comment by dnephin** [comment]
Ah, I see what you mean, we missed that in the PR.  I'll open a new issue for it.

LGTM

I've kicked off another build of jenkins

**Pull request merged**
