### PR TITLE
Dependabot Generated PRs

### PR DESCRIPTION
**Pull request by ksylvan**
**What I did**

These showed up in my fork of docker/compose when Dependabot created PRs to deal with security fixes/issues.

**A picture of a cute animal, if possible in relation to what you did**

image

### CODE REVIEW

**Comment by ndeloof** [comment]
Docker compose v1 is soon to be EoL, you should not waste time with this

**Comment by ksylvan** [comment]
@ndeloof isn't this Docker Compose v2? In any case the changes are dependabot security updates and the details are in the commits.

**Comment by ndeloof** [comment]
`master` branch is Docker Compose v1
prefer (default) v2 branch

**Comment by ksylvan** [comment]
> commits only tell me about the commit range but not about security issue those updates are supposed to fix. As v1 will be EoL in June, I don't expect we approve such updates without a critical/security issue in mind. Or is this just because depdendabot PRs are annoying you'd like this merged ?

No, I am not attached to whether or not you merge this; Dependabot PRs are not annoying to me. I find them helpful.

Regarding the "commits only tell me about the commit range" - if you see above, click on the "..." and then look at the information in the longer commit message.

Or you can look at the Dependabot PRs (closed) in my fork: [PR list](https://github.com/ksylvan/compose/pulls?q=is%3Apr+is%3Aclosed)

I updated the description above to make it easier to see the security fixes.

**Comment by milas** [comment]
As mentioned, Compose v1 does not receive updates anymore. Security updates ended October 2022. See https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/. The code remains in this repository to preserve history but is frozen, we are not accepting PRs to `master` / v1 anymore.

Currently, Compose v2 lives on the `v2` branch, which is set as the "default" in this repository. The dependency files are `go.mod` and `go.sum` now, as Compose v2 is a Go application unlike Compose v1, which was written in Python (and had `requirements.txt` file(s) as a result).

**Pull request closed without merging**
