### PR TITLE
docker build --pull 

### PR DESCRIPTION
**Pull request by yograterol**
Support for the --pull option in build images from Dockerfile

Issue: https://github.com/docker/fig/issues/726

Before merge we need "--pull" support in docker-py.

The test fails for the block. This feature is compatible with the next version of docker-py.

Block: https://github.com/docker/docker-py/pull/421

### CODE REVIEW

**Comment by tianon** [comment]
ping @yograterol :wink:

**Comment by yograterol** [comment]
@aanand Yes I will add test an sign my commit.

@tianon :+1: dont worry ;)

**Comment by tianon** [comment]
:heart:

**Comment by vdemeester** [comment]
@yograterol Still willing to work on this one ?

**Comment by t128** [comment]
squashing?! wow that's ugly

**Comment by briceburg** [comment]
I think having the --pull flag (either in `docker-compose build` or `docker-compose up --force-recreate`) is quite useful. Any interest?

**Comment by mahnunchik** [comment]
+1

**Comment by t128** [comment]
:+2:

**Comment by dnephin** [comment]
Closing as duplicate of #1494 which has an integration test

**Pull request closed without merging**
