### PR TITLE
Fix typo in unpause reference doc

### PR DESCRIPTION
**Pull request by vdemeester**
Found a small type in `docs/reference/unpause.md` :stuck_out_tongue_closed_eyes:.

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM, not sure why docs validation failed

**Comment by thaJeztah** [comment]
LGTM :smile:

**Comment by vdemeester** [comment]
Updated.

**Comment by thaJeztah** [comment]
ping @dnephin looks like this is ready(ish) to merge?

**Pull request merged**
