### PR TITLE
Do not wrap table cells

### PR DESCRIPTION
**Pull request by ekristen**
Fixed https://github.com/docker/compose/issues/1691

### CODE REVIEW

**Comment by aanand** [comment]
This removes the width-detection behaviour and wrapping entirely, which makes for unpleasant terminal output in the normal case. It would be best to disable wrapping only if we can't retrieve a terminal size.

**Comment by aanand** [comment]
(This would simply entail changing `80` to `0`, I think.)

**Comment by ekristen** [comment]
@aanand I fixed it to be 0

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Comment by ralphtheninja** [comment]
:+1:

**Pull request merged**
