### PR TITLE
Docs: fix env_file example

### PR DESCRIPTION
**Pull request by spk**
I had some problems with that, thinking the `env` file is in YAML format.
Cheers

### CODE REVIEW

**Comment by spk** [comment]
The build errors don't seems related to the changes. How can I ask for rebuild ?

**Comment by aanand** [comment]
Thanks!

It'd be even better to spell out what an `env` file is:

> Compose expects each line in an env file to be in `VAR=VAL` format. Lines beginning with `#` (i.e. comments) are ignored, as are blank lines.

The env file sample could include an example blank line and comment, for clarity.

**Comment by spk** [comment]
Yes it's better ! Thanks I fix that.

**Comment by aanand** [comment]
Great, thanks. Commit just needs signing off:

    $ git commit --amend --reuse-message=HEAD --signoff
    $ git push --force

**Comment by spk** [comment]
Ready :seedling:

**Comment by bfirsh** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Comment by spk** [comment]
Cool ! Thanks

**Pull request merged**
