### PR TITLE
Fixes https://github.com/docker/compose/issues/4099

### PR DESCRIPTION
**Pull request by hholst80**
Signed-off-by: Henrik Holst <holst@matmech.com>

### CODE REVIEW

**Comment by hholst80** [comment]
Looks like the jenkins tests are broken. 

```
16:52:43 [all_py34] tests/acceptance/cli_test.py::CLITestCase::test_pull_with_ignore_pull_failures FAILED
16:52:46 [all_py27] tests/acceptance/cli_test.py::CLITestCase::test_pull_with_ignore_pull_failures FAILED
```

Those are not related to this commit.

**Comment by hholst80** [comment]
@shin- whats going on with the jenkins installation?

**Comment by fichte** [comment]
any progress on this PR? i guess a lot of people need this

**Comment by shin-** [comment]
Rebased + merged in #4582 

Thank you!

**Pull request closed without merging**
