### PR TITLE
Allowing null for build args

### LINKED ISSUE #3020: Build arguments with only a key don't work with object syntax, contradicting  documentation
[`build.args` doc](https://docs.docker.com/compose/compose-file/#args) states:

> Build arguments with only a key are resolved to their environment value on the machine Compose is running on.

It's the same feature as for [`environment`](https://docs.docker.com/compose/compose-file/#environment).

However, it doesn't work with object syntax:
```yaml
version: '2'
services:
  test:
    build:
      context: .
      args:
        BLA:
```
```shell
$ BLA=foo docker-compose config
ERROR: Validation failed in file './docker-compose.yml', reason(s):
services.test.build.args contains null, which is an invalid type, it should be a string, or a number
```
It should work (and maybe it shouldn't not accept a number, I don't know).

Array syntax does work:
```yaml
version: '2'
services:
  test2:
    build:
      context: .
      args:
        - BLA
```
```shell
$ BLA=foo docker-compose config
networks: {}
services:
  test2:
    build:
      args:
        BLA: foo
      context: /xxx
version: '2.0'
volumes: {}
```

Also, `build.args` doc is missing example for these specific points. `environment` has nice examples for that.

### PR DESCRIPTION
**Pull request by dbonev**
Fixes #3020

Signed-off-by: Dimitar Bonev <dimitar.bonev@gmail.com>

### CODE REVIEW

**Comment by dnephin** [comment]
Thanks for the PR!

Change looks correct. A quick unit test in `tests/unit/config/config_test.py` would be great.

I believe the current test failures are unrelated.

**Comment by dnephin** [comment]
Looking at this again, I think the right fix might actually be to use `{$ref: #/definitions/list_or_dict},`. We're removing `boolean` from the accepted values, and at that point it should be identical to the schema here.

**Comment by dbonev** [comment]
Done. Thx @dnephin

**Comment by dnephin** [comment]
LGTM

**Comment by shin-** [comment]
LGTM!

**Pull request merged**
