### PR TITLE
Properly validate volume definition

### PR DESCRIPTION
**Pull request by shin-**
+ Test valid empty volume definitions

### CODE REVIEW

**Comment by dnephin** [comment]
Works for me. 

Maybe a test case for this new error case?

Do you want to update the two `driver: default` references in the docs in this PR as well?

**Comment by shin-** [comment]
There should be one already that I included in the external volumes PR.

**Comment by dnephin** [comment]
Ah, right, there is, cool

**Comment by aanand** [comment]
LGTM

**Pull request merged**
