### PR TITLE
Port ranges

### PR DESCRIPTION
**Pull request by mnowster**
Add port range support to docker compose.

Allows us to remove our split_port function and use docker-py's split_port function.

### CODE REVIEW

**Comment by aanand** [comment]
LGTM.

@uvgroovy @mnowster: Thanks team!

**Comment by mnowster** [comment]
Yay! Yes, thank you @uvgroovy for your helpful contribution :sparkles:

**Comment by tequilaskywalk** [comment]
why is this missing in 1.8.0-rc1 (build 9bf6bc9 )?

OSX: Native Docker   Version 1.12.0-rc2-beta16 (build: 9493)
f615be9fb245904fbdf1aa0cad251d418c869428

**Comment by aanand** [comment]
@tequilaskywalk This has been in Compose for several versions now. I just tried your example on Docker for Mac and it crashed the VM. My guess would be that simultaneously binding 1001 ports puts a bit of a strain on it.

**Comment by ellioseven** [comment]
This still seems to be an issue for me? Am I 

``` bash
[example] cat docker-compose.yml                                                                                                                                                                                    
# PHP Web Server
web:
  # Build the Drupal 8 image
  # https://hub.docker.com/r/_/drupal/
  image: drupal:8
  # Environment variables
  environment:
    # Drupal settings
    DRUPAL_PROFILE: standard
    DRUPAL_SITE_NAME: Drupal
    DRUPAL_USER: admin
    DRUPAL_PASS: admin
    DRUPAL_DBURL: mysql://drupal:drupal@database:3406/drupal
  ports:
    # Host machine's port 8000 will map to Drupal's port 80
    - "8000-8100:80"
  volumes:
    # Drupal should live in the "drupal" directory
    - ./drupal:/app
  links:
    - database:database
  command: php -S 0.0.0.0:80 -t /app
  working_dir: /app
  restart: always

# MySQL Server
database:
  image: mysql:5
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
    - "3306-3406:3306"
  volumes:
    - ./mysql:/var/lib/mysql
  restart: always
[example] docker-compose up                                                                                                                                                                                         
ERROR: The Compose file './docker-compose.yml' is invalid because:
database.ports is invalid: Port ranges don't match in length
web.ports is invalid: Port ranges don't match in length
[example] docker-compose --version                                                                                                                                                                                  
docker-compose version 1.7.1, build 0a9ab35
[example] docker --version                                                                                                                                                                                          
Docker version 1.11.2, build b9f10c9
```

**Comment by aanand** [comment]
@ellioseven We don't yet support mapping a range on the host to a single container port. This is tracked in https://github.com/docker/compose/issues/3150.

**Pull request merged**
