### PR TITLE
Import dotenv file to os environment

### PR DESCRIPTION
**Pull request by ulyssessouza**
**What I did**
Import dotenv file to os environment to enable setting variables like `DOCKER_BUILDKIT` and others through `.env` file

**Related issue**
Resolves https://github.com/docker/compose/issues/9345

### CODE REVIEW

**Review by glours — APPROVED** [review]
LGTM

**Review by laurazard — APPROVED** [review]
Looks good

**Comment by wbydc** [comment]
Hi, looks like this breaks `env_file` option a bit.

Previously I had `.env` with private values for global setup, and generated `service-name.env` for several services in compose, witch were overwriting some values like this:

```shell
# .env
KEY=DEFAULT_VALUE

# first-service.env
KEY=VALUE_FOR_FIRST_SERVICE

# second-service.env
KEY=VALUE_FOR_SECOND_SERVICE
```

```yml
services:
    first-service:
        ...
        env_file:
            - .env
            - first-service.env
        ...

    second-service:
        ...
        env_file:
            - .env
            - second-service.env
        ...
```

But now it always uses values specified in `.env`, no matter the order in `env_file`.

I guess such behaviour should be mentioned in the documentation.

**Comment by digaoddc** [comment]
I agree with @wbydc, the env files passed with the `env_file` options are now ignored. I'm having problems with this new version of docker-compose in our project.

We use it like this:
```
app:
  env_file:
     - .docker.env
     - .docker.env.local
```

Before this PR, first, the `docker.env` was loaded, then the file `docker.env.local` merge any settings defined in the first env file.

Now, these env files declared in the `docker-compose.yml` are completely ignored. I don't think this is the expected behavior.

**Comment by curry684** [comment]
They are not ignored, just processed in the wrong order as demonstrated in https://github.com/docker/compose/issues/9608#issuecomment-1176735103

Either way, this 'fix' is currently breaking production environments and should be rolled back or fixed asap.

**Comment by crzdg** [comment]
Do we really want to have the `.env`-file loaded automatically in any case. Regardless of having it loaded before or after the defined files in the `docker-compose`. If so, there should at least by a function to disable this feature. And with this, we're back to the current feature set where you have to define the file in the `docker-compose` and the corresponding `env_file`-key. 

I really can't understand why we want to have this feature in any place? As far as I understand it should be no problem to achieve the requested behavior with features available `<2.6.0`. This breaks and changes a lot, not only conceptional but also concerning security, CI/CD, and dev-ops in general.

I would love to see to roll-back this and hardly think again about this "feature"

**Comment by ulyssessouza** [comment]
This precedence issues should be fixed with https://github.com/docker/compose/pull/9636.

About the `.env` file load. That can be avoided by setting `--env-file /dev/null` for example. That would make Docker Compose avoid the loading of `.env`

**Pull request merged**
