### PR TITLE
Use Docker 1.7 RC5

### PR DESCRIPTION
**Pull request by aanand**
day_today_businews

### CODE REVIEW

**Comment by thaJeztah** [comment]
Erm, rc5 was just pushed (not kidding)

**Comment by thaJeztah** [comment]
image

**Comment by aanand** [comment]
Ah, the fast-paced world of open source. Updated.

**Comment by thaJeztah** [comment]
Thanks! Yes, two releases in under 24hrs :/. Hopefully the last one!

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
