### PR TITLE
switch to XML as default format for compose files

### PR DESCRIPTION
**Pull request by thaJeztah**
for the upcoming compose v4.1.0 release

YAML is known to be difficult to write, due to its formatting heavily relying
on white-spacing (indentation).

This patch switches the preferred format for compose files to XML, which is
a proven file format, widely used in our industry, and provides a stronger
schema validation, among others.

Support for YAML files is kept for backward compatibility.

For comparison, the following compose file in YAML:

```yaml
services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
      - 80443:443
```

Can be written in XML as:

```xml
<services>
  <web>
    <image>nginx:alpine</image>
    <ports>8080:80</ports>
    <ports>10443:443</ports>
  </web>
</services>
```

With this patch:

```bash
docker-compose up -f docker-compose.xml
[+] Running 2/2
 ⠿ Network compose_default  Created                                                                                                                                                                    0.1s
 ⠿ Container compose-web-1  Created                                                                                                                                                                    0.1s
Attaching to compose-web-1
compose-web-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
compose-web-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
compose-web-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
compose-web-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
compose-web-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
compose-web-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
compose-web-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
compose-web-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: using the "epoll" event method
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: nginx/1.21.3
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: OS: Linux 5.10.104-linuxkit
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: start worker processes
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: start worker process 32
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: start worker process 33
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: start worker process 34
compose-web-1  | 2022/04/01 12:49:26 [notice] 1#1: start worker process 35
```

**What I did**

**Related issue**

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**

sddefault

### CODE REVIEW

**Comment by jurrian-cgi** [comment]
I love this april's fools joke! 😜

**Comment by thaJeztah** [comment]
@jurrian-cgi give it a try.. it works! 😉 all XML heaven!

**Comment by ludoch** [comment]
"Go" for it.
"Java" for it.

**Comment by glours** [comment]
Thanks @thaJeztah You can start thinking about next year April Fools 😉

**Comment by thaJeztah** [comment]
Next year, we'll do punch cards! 🤓 😂  https://makezine.com/2014/12/05/punch-card-interface-now-on-twitter/

Used_Punchcard_(5151286161)

**Pull request closed without merging**
