### PR TITLE
Support COMPOSE_IGNORE_ORPHANS for `compose run`

### PR DESCRIPTION
**Pull request by PIG208**
**What I did**
Made `compose run` respect the env var COMPOSE_IGNORE_ORPHANS. E2E test cases added.

**Related issue**

This revives #7020 and resolves the issue mentioned in [#4992 (comment)](https://github.com/docker/compose/pull/4992#issuecomment-696569463).

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
mimi

### CODE REVIEW

**Comment by PIG208** [comment]
@ndeloof @ulyssessouza any feedbacks will be greatly appreciated

**Comment by juninhocruzg3** [comment]
+1
I need to use `COMPOSE_IGNORE_ORPHANS` on `docker-compose run`, but after #4992 it works only for `docker-compose up`.
Thank you for revive it!

**Review by ndeloof — CHANGES_REQUESTED** [review]
LGTM from a code and feature point of view
reference doc need to be updated to reflect this new option: https://github.com/docker/compose/blob/v2/docs/reference/docker_compose_run.yaml

**Review by ndeloof — APPROVED** [review]
Oh yes indeed, env var only. But nice addition to the docs, thanks

**Comment by PIG208** [comment]
The missing file that caused the CI to fail was added.

**Pull request merged**
