### PR TITLE
Add `index` for `logs` CLI command

### LINKED ISSUE #10130: docker-compose logs for a specific instance of a service
### Description

When we have multiple replicas of a service, it would be useful to be able to query the logs for a specific instance.

Similar to how we have for `docker-compose exec` via the `index` option:

```
$ docker-compose exec -ti --index 1 <service name> <command>
```

I looked at the open issues and couldn't see this.

I will be happy to work on a PR as well, if this sounds sensible to add.

Thanks.

### PR DESCRIPTION
**Pull request by asaha123**
Signed-off-by: Amit Saha <asaha@atlassian.com>

**What I did**

**Related issue**

Fixes #10130

### CODE REVIEW

**Review by ndeloof — APPROVED** [review]

**Comment by asaha123** [comment]
Hi @ndeloof - I can't seem to get the E2E log tests to pass locally, for example while on the `v2` branch:

```
$ go test  -v -count=1 -parallel=1 --tags=standalone ./pkg/e2e -run TestLocalComposeLogs/logs_ping
=== RUN   TestLocalComposeLogs
=== PAUSE TestLocalComposeLogs
=== CONT  TestLocalComposeLogs
    logs_test.go:29: WARNING: docker-buildx cli-plugin not found, using default buildx installation.
    logs_test.go:29: Docker Compose version bc1a66dd.m

=== RUN   TestLocalComposeLogs/logs_ping
    logs_test.go:45: assertion failed:
        Command:  /home/asaha/work/github.com/atlassian-forks/compose/bin/build/docker-compose --project-name compose-e2e-logs logs ping
        ExitCode: 0
        Stdout:
        Stderr:

        Failures:
        Expected stdout to contain "PING localhost (127.0.0.1)"
=== CONT  TestLocalComposeLogs
    framework.go:127: Contents of config dir:
    framework.go:129:   - /tmp/TestLocalComposeLogs914397335/001
    framework.go:129:   - /tmp/TestLocalComposeLogs914397335/001/cli-plugins
    framework.go:129:   - /tmp/TestLocalComposeLogs914397335/001/cli-plugins/docker-compose
    framework.go:129:   - /tmp/TestLocalComposeLogs914397335/001/cli-plugins/docker-scan
--- FAIL: TestLocalComposeLogs (0.05s)
    --- FAIL: TestLocalComposeLogs/logs_ping (0.01s)
FAIL
FAIL    github.com/docker/compose/v2/pkg/e2e    0.066s
FAIL

```

I am on Linux with the following docker engine version:

```
$ docker --version
Docker version 20.10.23, build 715524332f
```

Can you see something obvious that I am doing wrong?

**Comment by glours** [comment]
Hello @asaha123 
Thanks for your contribution 🙏 
The business logic is missing from your PR, you need to apply limit the `/pkg/compose/logs.go` file. You can take the [implementation](https://github.com/docker/compose/blob/a54d4883034596ab6c2cd4ca7b2f8e79646e1d87/pkg/compose/cp.go#L96) of the `cp` command as example

**Comment by asaha123** [comment]
> Hello @asaha123 Thanks for your contribution pray The business logic is missing from your PR, you need to apply limit the `/pkg/compose/logs.go` file. You can take the [implementation](https://github.com/docker/compose/blob/a54d4883034596ab6c2cd4ca7b2f8e79646e1d87/pkg/compose/cp.go#L96) of the `cp` command as example

Thank you @glours - that's right, I haven't yet implemented the business logic as I am trying to first write a failing test forcing me to then implement the feature.

However, as I shared in https://github.com/docker/compose/pull/10193#issuecomment-1406013035 i am having difficulty in getting an existing test to pass as well, so not sure what's going on- can you see anything for me to do differently?

**Comment by glours** [comment]
@asaha123 you should use `make e2e` to run the end-to-end tests locally, and if you want to run an explicit test you can define it with the `E2E_TEST` variable like this:
`E2E_TEST=TestLocalComposeLogs make e2e`

**Comment by asaha123** [comment]
Hi @glours thank you, i tried your suggestion, I get this error on the latest `v2` branch:

```
$ E2E_TEST=TestLocalComposeLogs/logs_ping make e2e
go test -run TestLocalComposeLogs/logs_ping -race -coverprofile=coverage.out -covermode=atomic -count=1 ./pkg/e2e
--- FAIL: TestLocalComposeLogs (0.25s)
    logs_test.go:29: WARNING: docker-buildx cli-plugin not found, using default buildx installation.
    logs_test.go:29: Docker Compose version bc1a66dd.m

    --- FAIL: TestLocalComposeLogs/logs_ping (0.04s)
        logs_test.go:45: assertion failed:
            Command:  docker compose --project-name compose-e2e-logs logs ping
            ExitCode: 0
            Stdout:
            Stderr:

            Failures:
            Expected stdout to contain "PING localhost (127.0.0.1)"
    framework.go:127: Contents of config dir:
    framework.go:129:   - /tmp/TestLocalComposeLogs3604419756/001
    framework.go:129:   - /tmp/TestLocalComposeLogs3604419756/001/cli-plugins
    framework.go:129:   - /tmp/TestLocalComposeLogs3604419756/001/cli-plugins/docker-compose
    framework.go:129:   - /tmp/TestLocalComposeLogs3604419756/001/cli-plugins/docker-scan
FAIL
coverage: 38.7% of statements
FAIL    github.com/docker/compose/v2/pkg/e2e    0.295s
FAIL
make: *** [Makefile:64: e2e-compose] Error 1
```

I can try and debug this, but does anything jump out to you? I am on Linux.

**Comment by ndeloof** [comment]
@asaha123 any plan to move forward with this PR? Do you want me to adopt it and get this feature in Docker Compose ?

**Comment by asaha123** [comment]
Hi @ndeloof sorry about that. if my code is any good, please feel free to adop it.

**Comment by ndeloof** [comment]
see https://github.com/docker/compose/pull/11231

**Pull request closed without merging**
