### PR TITLE
Support version command in Bash completion

### PR DESCRIPTION
**Pull request by albers**
See #878 and #1499 for corresponding zsh completion
Thanks @sdurrheimer for pointing me to this addition.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Comment by albers** [comment]
@dnephin @aanand Could you please include this into 1.4.1 so that completion and functionality match?

**Comment by aanand** [comment]
Didn't realise it hadn't made the 1.4.0 cut - I've added it to the milestone for 1.4.1.

**Comment by albers** [comment]
@aanand Thanks very much!

**Comment by albers** [comment]
@dnephin why did you exclude this from 1.4.1?

**Comment by dnephin** [comment]
@albers while I was merging branches I realized it was already in the 1.4.0 release, I think we just tagged it wrong!

**Comment by dnephin** [comment]
and we close the old milestones, so I couldn't add the 1.4.0 milestone to it.

**Comment by albers** [comment]
@dnephin oh yes, it is indeed included in both versions. I'm sorry. Thanks.

**Pull request merged**
