### PR TITLE
Rename CHANGES.md to CHANGELOG.md

### PR DESCRIPTION
**Pull request by aanand**
To align with the docker/docker repo.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM great!

**Comment by bfirsh** [comment]
Might be worth setting up a symlink. A bunch of places link to it, like http://docs.docker.com/release-notes/

**Comment by aanand** [comment]
I've given it a go, but it looks like GitHub doesn't handle symlinks all that gracefully:

https://github.com/aanand/fig/blob/478054af4775d6f78fcca4b479f91bf569ff04f7/CHANGES.md

screen shot 2015-08-14 at 11 29 14

**Comment by thaJeztah** [comment]
> A bunch of places link to it

I think those links are actually incorrect because they're pointing to "master", but should point to the release notes for *that* release, e.g.
https://github.com/docker/compose/blob/1.4.0/CHANGES.md :smile:

**Comment by mnowster** [comment]
LGTM

**Comment by bfirsh** [comment]
Are the release notes getting fixed, too? Might be worth checking recent blog posts too. :/

**Comment by aanand** [comment]
https://github.com/docker/docker/pull/15715

**Comment by aanand** [comment]
https://github.com/docker/docs-base/pull/137

**Pull request merged**
