### PR TITLE
Win32 interactive run - Connect container to networks before starting

### LINKED ISSUE #4212: docker-compose run fails to set up link aliases in Windows interactive mode
https://github.com/docker/for-win/issues/278

### PR DESCRIPTION
**Pull request by shin-**
Fixes #4212

### CODE REVIEW

**Comment by shin-** [comment]
@rneugeba confirmed this fixes the issue on Docker for Windows

cc @aanand

**Comment by rubenhenriques** [comment]
Is this related to https://forums.docker.com/t/connecting-to-containers-ip-address/18817 ?

**Comment by aanand** [comment]
LGTM

**Comment by forevermatt** [comment]
Thanks for getting this fixed so quickly. Very impressive!

**Pull request merged**
