### PR TITLE
Updated CLI help for docker-compose pull command

### PR DESCRIPTION
**Pull request by londoncalling**
### What's changed

- updated Help for the `pull` command per user feedback

### Related
- [Issue 3190 in `docker.github.io` docs repo](https://github.com/docker/docker.github.io/issues/3190)

- [Comment in PR 3197 expanded on pull command, added links to Compose samples](https://github.com/docker/docker.github.io/pull/3197#discussion_r115339449)

### Reviewers

@shin- @dnephin @joaofnfernandes 

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by joaofnfernandes** [comment]
LGTM

**Comment by shin-** [comment]
Where does the mention of `docker-stack.yml` come from though? Is that Docker Cloud bleeding through? It's not mentioned anywhere else in the Compose project AFAIK.

**Comment by londoncalling** [comment]
@shin- this is the `docker-stack.yml` that operates essentially as a Compose file and uses the `deploy` key, not related to the Cloud stack file. (That naming confusion needs to be addressed.) Should I not mention it at all here, I can take it out.

**Comment by londoncalling** [comment]
@shin- you are right. It doesn't work with `docker-stack.yml`. I'll change the Help description.

**Comment by shin-** [comment]
@londoncalling The term we use in other parts of the CLI is "Compose file", like in `docker-compose down`:

```
...
By default, the only things removed are:

- Containers for services defined in the Compose file
- Networks defined in the `networks` section of the Compose file
...
```

Or `docker-compose config`:

```
Validate and view the compose file.
...
```

It might be better to use the same term for consistency (also because `docker-compose.yml` is the default, but not the only possible name for a Compose file)

**Comment by londoncalling** [comment]
@shin- this should be good now, and it past the CI build! :-) Can you merge it for me once you think it's okay?

**Pull request merged**
