### PR TITLE
Allowing running containers to be rm'd by stop flag

### PR DESCRIPTION
**Pull request by rawkode**
Signed-off-by: David McKay david@rawkode.com

### CODE REVIEW

**Comment by rawkode** [comment]
I don't believe my changes have caused this build to fail ... I hope. Hopefully somebody can advise :+1: 

@aanand ?

**Comment by shin-** [comment]
Sorry, I accidentally broke `master` yesterday. It should work now if you rebase your changes.

**Comment by rawkode** [comment]
Fixed. Thanks @shin-

**Comment by rawkode** [comment]
@shin- Is there anything else I can provide to improve this PR, or is there doubt to it's usefulness?

**Comment by rawkode** [comment]
Hi,

I know this has been idle  for a few months, but I believe we should look at this. I'm not overly sold on there being a `--stop`, but the disparity between `--force` with `compose` and the `docker-cli` should probably be addressed.

`--force` within compose removes confirmation but won't remove a running container, whereas `docker-cli`'s `--force` will `Force the removal of a running container (uses SIGKILL)`

Thoughts?

**Comment by shin-** [comment]
Sorry for the months-long silence! I think adding the `--stop` flag makes sense. We probably shouldn't change the meaning of `--force` since people have probably come to rely on it. PR as it is right now looks good to me :+1:

**Pull request merged**
