### PR TITLE
corrected description of network aliases, added real-world example pe…

### PR DESCRIPTION
**Pull request by londoncalling**
…r #2907

Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by londoncalling** [comment]
@shin- @aanand @dnephin @moxiegirl can you all take a look at this updated network aliases description? This is a follow-on fix per the docs-related part of the  thread in #2907 . 

It is essentially Aanand's suggestion with small tweaks. Let me know if it looks good, and if so please merge. --Thanks!

**Comment by shin-** [comment]
LGTM :+1:

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
LGTM

**Pull request merged**
