### PR TITLE
Add docker-compose push and docker-compose bundle

### PR DESCRIPTION
**Pull request by dnephin**
* `push` pushes services images to a registry
* `bundle` pulls/pushes as needed and builds a bundle file to be consumed by https://github.com/docker/docker/pull/23522

### CODE REVIEW

**Comment by shin-** [comment]
Are we okay with merging this without tests to get it into the RC? 
Overall code LGTM.

**Comment by aanand** [comment]
Yeah, we should follow-up with test coverage ASAP but I'm happy to merge it without.

**Comment by dnephin** [comment]
I'll start working on the tests for this

**Comment by albers** [comment]
There are no reference docs for `bundle` and `push` yet.

**Comment by dnephin** [comment]
Opened #3636 for the reference docs

**Pull request merged**
