### PR TITLE
prefix volumes with `container:` as we resolve service into container

### LINKED ISSUE #8592: `volumes_from` not resolving correct container name when using `docker compose run`
**Description**

Docker Compose v2 doesn't seem to use the correct container name for volumes defined with `volumes_from` when using `docker compose run`. This worked correctly with docker-compose v1 but not with the new version.

**Steps to reproduce the issue:**
1. Create a `docker-compose.yml` with the following content:
```yml
version: "3"

services:
  test1:
    image: alpine
    command: sleep 100000
    volumes:
      - ./testvolume:/testvolume

  test2:
    image: alpine
    volumes_from:
      - test1
```
2. Run the following command:
```
docker compose run --rm test2 echo test2
```

**Describe the results you received:**
```
Error response from daemon: No such container: test1
```

**Describe the results you expected:**
The same result as docker compose v1 (though presumably the starting/creating format would be different):
```
Starting docker-volume-repo_test1_1 ... done
Creating docker-volume-repo_test2_run ... done
test2
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Starting the services with `docker compose up` works exactly as expected, with both versions of compose so it seems to be specific to `run`.

**Output of `docker-compose --version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0-rc.1
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:** 

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 148
  Running: 5
  Paused: 0
  Stopped: 143
 Images: 4212
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.805GiB
 Name: docker-desktop
 ID: OJQE:MQQQ:IBIS:Z5BC:YA7C:BRKE:3YWL:IIXD:DDNM:6IRP:FD3W:QQQG
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 56
  Goroutines: 57
  System Time: 2021-08-23T18:40:27.356312695Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
I've only been able to test this with Docker for Mac, but I'd assume it would happen elsewhere too.

### PR DESCRIPTION
**Pull request by ndeloof**
As we resolve service dependencies by `volumes_from` into actual containers, prefix by `container:` to keep the compose model consistent
Also include a sanity check we only get `container:*` by the time `volumes_from` is passed to the moby API.

Resolves #8592

### CODE REVIEW

**Review by lorenrh — APPROVED** [review]

**Comment by jaspertandy** [comment]
When is this getting released? We were told in #8592 that this would be in RC3 but this was 8 days ago and RC3 is 13 days ago. When can we expect this to be fixed? It's _super_ inconvenient as we basically can't start projects that use volumes_from without it.

**Comment by ndeloof** [comment]
My comment about RC3 was an assumption we wouldn't need an extra fix (which this PR is about)
There's no release yet to include this fix, and the timeline to drop a release is not yet defined.

**Comment by jaspertandy** [comment]
I understand that, but this is a pretty show-stopping bug. Are we talking about RC4, or another version we'll be waiting for for compose to be functional again? I don't think it's unreasonable to ask for a timeline since I'm now paying for Docker!

**Comment by mat007** [comment]
@jaspertandy the next release of Docker Desktop is for now scheduled for the 30th of this month.
There will be a new release of Compose V2 shipped with it.

**Comment by jaspertandy** [comment]
@mat007 great - thank you!

**Pull request merged**
