### PR TITLE
Output valid config in config command

### LINKED ISSUE #3429: Docker produces invalid configuration when using 'config' CLI
Just noticed this today - external networks seem to add the invalid `external_name` key

source file:
```yaml
version: '2'

networks:
  rabbitmq:
    external:
      name: rabbitmq_default

services:
  web:
    build: .
    ports:
      - '7000:8080'
    networks:
      - default
      - rabbitmq
```

result of `docker-compose config`
```yaml
networks:
  rabbitmq:
    external:
      name: rabbitmq_default
    external_name: rabbitmq_default
services:
  web:
    build:
      context: /app
    networks:
      default: null
      rabbitmq: null
    ports:
    - 7000:8080
version: '2.0'
volumes: {}
```

I also noticed the `networks` section of a service seems to be converted from an array to a dict.  Dunno if thats bad or not - probably not great.

Ran this with the HEAD version (1.8.0dev) as well as 1.7.0

### PR DESCRIPTION
**Pull request by shin-**
- Remove external_name from serialized config output

Fixes #3429

### CODE REVIEW

**Comment by shin-** [comment]
Updated with test.

**Comment by denismakogon** [comment]
LGTM +1

**Comment by dnephin** [comment]
LGTM

**Comment by shin-** [comment]
Reverted the context path change.

**Comment by aanand** [comment]
LGTM

**Pull request merged**
