### PR TITLE
Remove the tutorials repo - its private now

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@dnephin @moxiegirl @thaJeztah

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by dnephin** [comment]
Already done in #2884

**Comment by SvenDowideit** [comment]
yay :)

**Pull request closed without merging**
