### PR TITLE
Add trove classifier to declare supported python versions.

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

Thanks!

**Comment by mnowster** [comment]
@dnephin do we need to specify each major.minor version it'll work with? For each version of Python 3.x I mean.

**Comment by dnephin** [comment]
I think it's really up to us. We could add the generic "Python 2" and "Python 3" classifiers. I think there are actually a few more we could add as well. From https://pypi.python.org/pypi?%3Aaction=list_classifiers


```
Development Status :: 5 - Production/Stable
Environment :: Console
Intended Audience :: Developers
License :: OSI Approved :: Apache Software License
Programming Language :: Python :: 2
Programming Language :: Python :: 3
```

**Comment by mnowster** [comment]
Ok cool, I'll create a separate issue for us and we can add some more in later.

LGTM.

**Pull request merged**
