### PR TITLE
Fix overriding volumes from cli when running a service

### PR DESCRIPTION
**Pull request by eddwardo**
Signed-off-by: Piotr Szymanski <p.szymanski@bidpy.pl>

In case where volumes are defined for a service in compose yaml file,
user might want to override this volume from cli command as such:
docker-compose run -v local:/overrided_remote foo

Currently, if user tries to override the volume from cli, command is
ignored.

Bug has been introduced in 1.14.0 afaik.

### CODE REVIEW

**Comment by eddwardo** [comment]
Locally, this test passes.

**Comment by shin-** [comment]
Can you clarify what bug this is supposed to fix?

Also, tests do need to pass on our CI. In this case, the issue is that you're not creating the mounted file on the remote host. Look at `test_run_one_off_with_volume_merge` for how to achieve this.

**Comment by eddwardo** [comment]
@shin- Update the commit message:
```
In case where volumes are defined for a service in compose yaml file,
user might want to override this volume from cli command as such:
docker-compose run -v local:/overrided_remote foo

Currently, if user tries to override the volume from cli, command is
ignored.
```

**Comment by eddwardo** [comment]
When can this land?

**Comment by eddwardo** [comment]
Ping?

**Comment by eddwardo** [comment]
This blocks my company from upgrading from 1.14.0 to the latest.
How can I get this PR to land?

**Comment by eddwardo** [comment]
fixed

**Pull request closed without merging**
