### PR TITLE
6008 update urllib3

### LINKED ISSUE #6008: Support urllib3 v1.23
## Description of the issue
[urllib3](https://github.com/urllib3/urllib3/) released version [1.23](https://github.com/urllib3/urllib3/releases/tag/1.23) on June 5th, and it breaks docker-compose.

## Context information (for bug reports)

```
docker-compose version 1.21.2, build unknown
```

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

## Steps to reproduce the issue

1. Upgrade urllib3
2. Run docker-compose

### Observed result
An error is thrown, saying docker-compose depends on urllib3 version `<1.23`

### Expected result
docker-compose to work as usual

### PR DESCRIPTION
**Pull request by venthur**
Updated urllib3 requirements to version 1.23 (the current one). Since the requests version we depend on has a hardcoded dependency on `urllib3 < 1.23` but will be updated [next week](https://github.com/requests/requests/issues/4673#issuecomment-395069592), I've also updated the requirement to the next version of the `requests` package.

Since this requests version does not exist yet, the build for this PR will fail until the new `requests` version is released.

Resolves #6008

### CODE REVIEW

**Comment by ofek** [comment]
@shin- Hello again! Does this look fine? Many of us would like to use the newest version of `requests`.

**Comment by venthur** [comment]
Refreshed the patch.

**Comment by ofek** [comment]
@shin- Can you please take one last look at this?

**Comment by ofek** [comment]
@shin- Can you please take a final look?

**Comment by shin-** [comment]
@ofek This is rude and uncalled for, please stop. I've seen the issue. As I mentioned, we need to be careful updating requests/urllib3 because it can have unexpected side effects. For example, this new version of `urllib3` drops support for Python 3.3 and prevents installation on that version, which we may not want to do yet for Compose.

Once I'm confident in the viability of the upgrade, I'll happily push the button ; until then, Compose works just fine with `urllib3==1.21.1`.

**Comment by shin-** [comment]
@ofek No harm done!

FWIW, I'm currently working on updating dependencies [on the SDK end of things](https://github.com/docker/docker-py/pull/2089), including support for Python 3.7 while retaining support for 3.3; once that hurdle is clear, it'll be much easier to transition these upgrades to Compose.

**Comment by ofek** [comment]
Ah, very interesting! I'll have to test it but I think I see a way forward.

**Comment by shin-** [comment]
Closing via #6092

**Pull request closed without merging**
