### PR TITLE
gha: test against docker v27.0.3

### PR DESCRIPTION
**Pull request by thaJeztah**
- supersedes/closes https://github.com/docker/compose/pull/11946

Switch to the test-channel, using the test.docker.com script, which has both stable and pre-releases.

**What I did**

**Related issue**

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

### CODE REVIEW

**Comment by thaJeztah** [comment]
hmm getting some "overlapping IP" errors in CI against 27.0.1-rc.1;

```
=== Failed
=== FAIL: pkg/e2e TestRestart/Up_a_project (0.11s)
    restart_test.go:42: Running command: docker compose --project-name e2e-restart down
    restart_test.go:44: Running command: docker compose -f ./fixtures/restart-test/compose.yaml --project-name e2e-restart up -d
    restart_test.go:44: assertion failed: 
        Command:  docker compose -f ./fixtures/restart-test/compose.yaml --project-name e2e-restart up -d
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:    Network e2e-restart_default  Creating
         Network e2e-restart_default  Error
        failed to create network e2e-restart_default: Error response from daemon: cannot create network 0ac38a64a6c14c79f806084b10eb2f59310dd0fe28d373ff35dd10d9f5721823 (br-0ac38a64a6c1): conflicts with network 54d12c569b435cdbd722dfec95899fe6d151c4b780117066dc875c91cb99cc42 (br-54d12c569b43): networks have overlapping IPv4
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    --- FAIL: TestRestart/Up_a_project (0.11s)

=== FAIL: pkg/e2e TestRestart (0.31s)
    restart_test.go:37: WARNING: docker-buildx cli-plugin not found, using default buildx installation.
    restart_test.go:37: Running command: docker compose version
Docker Compose version 0d6ec2c
    framework.go:130: Contents of config dir:
    framework.go:132:   - /tmp/TestRestart1830938976/001
    framework.go:132:   - /tmp/TestRestart1830938976/001/cli-plugins
    framework.go:132:   - /tmp/TestRestart1830938976/001/cli-plugins/docker-compose
    framework.go:132:   - /tmp/TestRestart1830938976/001/cli-plugins/docker-scan

=== FAIL: pkg/e2e TestRecreateWithNoDeps (0.27s)
    recreate_no_deps_test.go:26: WARNING: docker-buildx cli-plugin not found, using default buildx installation.
    recreate_no_deps_test.go:26: Running command: docker compose version
Docker Compose version 0d6ec2c
    recreate_no_deps_test.go:30: Running command: docker compose -f fixtures/dependencies/recreate-no-deps.yaml up -d
    recreate_no_deps_test.go:31: assertion failed: 
        Command:  docker compose -f fixtures/dependencies/recreate-no-deps.yaml up -d
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   time="2024-06-20T23:31:27Z" level=warning msg="/home/runner/work/compose/compose/pkg/e2e/fixtures/dependencies/recreate-no-deps.yaml: `version` is obsolete"
         Network recreate-no-deps_default  Creating
         Network recreate-no-deps_default  Error
        failed to create network recreate-no-deps_default: Error response from daemon: cannot create network 4c5b0f13d9d3cf404944e0664a1444ebef98383b0384a604e4ff8f92c24ce212 (br-4c5b0f13d9d3): conflicts with network 54d12c569b435cdbd722dfec95899fe6d151c4b780117066dc875c91cb99cc42 (br-54d12c569b43): networks have overlapping IPv4

**Comment by glours** [comment]
@thaJeztah we have some flakiness with those tests, I restarted them and they're all green now

**Comment by thaJeztah** [comment]
Ah! Thanks! I just got back to this PR, because I was I had written a "ping" in Slack to Albin that .. didn't send 😂 

I'll move this one out of draft; we can update the matrix to different versions if we want to after this (I'm considering changing to `23.0` (Mirantis's "LTS" release), `25.0` (Mirantis's _upcoming_ LTS release) and "Latest", but we can look what combinations make most sense.

**Comment by thaJeztah** [comment]
Rebased, and updated to v27.0.1

**Comment by thaJeztah** [comment]
> hmm getting some "overlapping IP" errors in CI against 27.0.1-rc.1;

🤔 And now wondering if I should've pinged the networking folks after all; https://github.com/moby/moby/pull/48089

**Comment by thaJeztah** [comment]
Either way; rebased, and updated to v27.0.2

**Review by glours — APPROVED** [review]

**Pull request merged**
