### PR TITLE
Introduce a new env var "COMPOSE_DOCKER_CLI_BUILD_EXTRA_ARGS"

### LINKED ISSUE #7025: Enable ssh option as build parameter for buildkit
**Is your feature request related to a problem? Please describe.**
When building a container we need access to other Resources like ssh and dont want to expose a private key in the container. 

**Describe the solution you'd like**
Support of `--ssh` in the build process that already works in buildkit.

**Additional context**
I tried `1.25.0-rc4`, but it does not support `--ssh` option. Tried the same as in bug 6440:

```
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
docker-compose build --ssh default my_image
```
This would be a major security improvement and save us so much pain.

Thanks,
bert

### PR DESCRIPTION
**Pull request by moriyoshi**
This patch allows one to pass arbitrary arguments in the docker command invocation through `COMPOSE_DOCKER_CLI_BUILD_EXTRA_ARGS`.

Resolves #7025.

### CODE REVIEW

**Comment by Syntactical01** [comment]
Only note, to be conistent with `COMPOSE_DOCKER_CLI_BUILD` you should probably use `COMPOSE_DOCKER_CLI_BUILD_EXTRA_ARGS`. That being said can someone review this? Docker compose REALLY needs support for the `--ssh` argument.

**Comment by mecampbellsoup** [comment]
Please merge!! Like many others we want to use `--ssh` when running builds thru docker compose. Thanks.

**Comment by itsjef** [comment]
Any progress update on this PR? 🤔

**Comment by mecampbellsoup** [comment]
Workaround:

```bash
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build {app-name-that-uses-build-kit}
```
Also here is my Docker daemon config:

```json
{
  "debug": true,
  "experimental": true,
  "features": {
    "buildkit": true
  }
}
```

**Comment by ppg** [comment]
That workaround doesn't help with `--ssh` or any other buildkit options that aren't explicitly supported by compose right? That's just a way to save typing `DOCKER_BUILDKIT=1`, i.e. you could simply do:
```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build {app-name-that-uses-build-kit}
```
But neither of them help with the fact the argument list is hardcoded (see https://github.com/docker/compose/blob/440c94ea7a7e62b3de50722120ca34c4e818205a/compose/service.py#L1790-L1803) and thus we will always be playing catchup to a buildkit build's options unless we have some pass through like this, specifically in this case the desire to pass `--ssh`.

**Comment by thaJeztah** [comment]
I don't think we should implement this; this would be a global option, which means that in a compose-file that has multiple `build` instructions, this option would grant all builds access to the ssh-agent, which is not desirable.

**Comment by ppg** [comment]
Is there an alternative plan? https://github.com/docker/compose/pull/7046 mentions https://github.com/docker/compose/pull/7046 but that is again hard-coding a new argument, so it will suffer the same issue of playing keep up, but also it's only adding `--secrets`; I didn't think you could implement the `--ssh` flag with `--secrets`?

**Comment by thaJeztah** [comment]
https://github.com/docker/compose/pull/7046 might still be the way forward, but might need to be proposed in https://github.com/compose-spec/compose-spec

**Comment by hannahkamundson** [comment]
Would love to see this merge request put in!

**Comment by tommie** [comment]
I filed https://github.com/compose-spec/compose-spec/issues/81 to continue the compose-spec discussion there.

**Comment by philomory** [comment]
I'd _very_ much prefer to see this in the `docker-compose.yaml` rather than adding more and more environment variables. In fact, I'd really prefer if `COMPOSE_DOCKER_CLI_BUILD` was moved to the `docker-compose.yaml` as well (but that probably belongs in a separate issue).

**Comment by moriyoshi** [comment]
> I don't think we should implement this; this would be a global option, which means that in a compose-file that has multiple build instructions, this option would grant all builds access to the ssh-agent, which is not desirable.

Passing a different key to each build sounds pretty much unusual to me. As for the compatibility, I don't think the build will be broken if `SSH_AUTH_SOCK` is present because its Dockerfile should have explicitly seeded the required key somewhere in the container in the first place.

And in case the behavior is undesirable, one can always choose not to use the option at all.

**Comment by eliliam** [comment]
Lets get this merged in guys, any devs know why the build it failed?

**Comment by goetas** [comment]
I do not think that this is the best solution. `COMPOSE_DOCKER_CLI_BUILD_EXTRA_ARGS` would be a global option, but not all the services being built might need those extra args, or might need them different. https://github.com/docker/compose/issues/6358 (in particular https://github.com/docker/compose/issues/6358#issuecomment-443661538) proposes a much safer solution (still a bit hacky but IMO good enough)

**Comment by Billy-** [comment]
> I don't think we should implement this; this would be a global option, which means that in a compose-file that has multiple `build` instructions, this option would grant all builds access to the ssh-agent, which is not desirable.

@thaJeztah how can we get a definitive decision? If we definitely don't want this, should we close this PR to avoid confusion? And people spending time on it?

> I do not think that this is the best solution. `COMPOSE_DOCKER_CLI_BUILD_EXTRA_ARGS` would be a global option, but not all the services being built might need those extra args, or might need them different. #6358 (in particular [#6358 (comment)](https://github.com/docker/compose/issues/6358#issuecomment-443661538)) proposes a much safer solution (still a bit hacky but IMO good enough)

I agree, this is a good suggestion. Looks like maybe we should either discuss further on that issue or file a new issue (as that issue is specifically about secrets, and this PR is about passing any flags you like).

**Comment by Seros** [comment]
When can we expect to have this feature done or is there something we can support to speed up the process?

**Comment by glours** [comment]
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.

**Pull request closed without merging**
