### PR TITLE
Add documentation which showcases using YAML anchors and aliases

### PR DESCRIPTION
**Pull request by nickjj**
Signed-off-by: Nick Janetakis <nick.janetakis@gmail.com>

### CODE REVIEW

**Comment by hadim** [comment]
So usefull !

**Comment by Starefossen** [comment]
Nicely done @nickjj :+1:

**Comment by SvenDowideit** [comment]
that's very nice!

**Comment by dnephin** [comment]
Now that we have extends, I'm not sure we need to call this out.

**Comment by dnephin** [comment]
Thanks for the PR!

Now that we have both `extends` and support for multiple files (http://docs.docker.com/compose/extends/), I think there is less of a need for yaml anchors and aliases.

We've added a link to the yaml docs at the top of http://docs.docker.com/compose/compose-file/

Our concern is that by documenting this feature of yaml, we'll be encouraging people to use it and there will be some expectation of support for this feature.  I don't think we'll be able to accept this PR.

**Comment by nickjj** [comment]
I still think anchors are useful in the case where you just want 1 file which isn't terribly complex but yeah the PR was opened almost a year ago when `extends` wasn't available so I definitely agree that it's less important to draw attention to anchors.

**Comment by grayside** [comment]
Now that extends is gone, might bringing back support for anchors be considered?

**Pull request closed without merging**
