### PR TITLE
Update docs about networking for current release

### LINKED ISSUE #2248: Network aliases created with full container name & not short name
Per https://github.com/docker/compose/blob/0409b287ad3ede39282c199d611456aab15dca71/docs/networking.md

image

However, what I am seeing is that the aliases are created with the full container name from compose e.g. context_web_1

This eliminates the benefit of consistent aliases, as compose will dynamically assign network alias depending on number of containers & where they are run from.

My simple test below.
image

image

image

### PR DESCRIPTION
**Pull request by dnephin**
cc @dave-tucker, @aanand 

I've updated the compose networking docs to match what the engine supports for this release.

Fixes #2248

### CODE REVIEW

**Comment by dave-tucker** [comment]
LGTM

**Comment by mnowster** [comment]
I think I understand why the scaling section has been removed, do you think it'd be worth including a section/statement about scaling that describes why it's not currently available? I can see users being a bit confused that it's not there/asking about it maybe?

Everything else is LGTM :)

**Comment by dnephin** [comment]
With this setup scaling is available, it's just not that useful because you'd have to do some form of client-side load balancing or have an external, but that's how it was with links.

I think the section existed for the "hostname" version of this doc because the behaviour was changing from links, but now that it's the same, I don't think we need to call it out in the document.

**Comment by mnowster** [comment]
@dnephin ah I see, ok, cool.

**Pull request merged**
