### PR TITLE
forward signal to container

### PR DESCRIPTION
**Pull request by ndeloof**
**What I did**
as compose run a container, forward signals to container the same way `docker run` does
we have to because `RunStart` only doest it for container without a TTY (https://github.com/docker/cli/blob/master/cli/command/container/start.go#L91)

As container is ran interactive from a terminal (`--tty=true`), `RunStart` uses `setRawTerminal` and doing so user to hi `Ctrl+C` just directly send those keys to target process, not `compose` command itself.
But when signal is sent to compose by a `kill` command it has to handle this and forward signal explicitly, just like `RunStart` does when container has no TTY.

**Related issue**
fixes https://github.com/docker/compose/issues/10586

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

### CODE REVIEW

**Review by glours — APPROVED** [review]
LGTM

**Comment by g0t4** [comment]
Would this fix allow for `Ctrl+R` to be sent to a container started with `docker compose up`? I'm trying to find if there are any open issues with regards to `stdin` and `docker compose` managed containers.

**Comment by ndeloof** [comment]
@g0t4 `docker compose up` is not interactive, it doesn't attach to a specific container, and as such won't forward signals to service(s). You can use `docker compose kill -s [SIGNAL] SERVICE` for this purpose

**Comment by kuro337** [comment]
@ndeloof Hello sir, is this still true?

If a process is launched with  docker compose up  - there is no way for my image to be sent the shutdown signal?

Are there any ways to achieve it?

**Comment by ndeloof** [comment]
Ctrl+C or `down` command will send a SIGINT signal to your container, you can tweak signal being sent and timeout waiting for termination in your compose.yaml file, see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#stop_grace_period

**Pull request merged**
