### PR TITLE
enable -v flag for docker-compose run command

### PR DESCRIPTION
**Pull request by eddwardo**
Give user ability to attach volumes while running containers with
docker-compose run command. Example is given in the test implementation,
command is compatible with the one provided by docker engine.

Signed-off-by: Piotr Szymanski skyleton@gmail.com

### CODE REVIEW

**Comment by eddwardo** [comment]
Implemented tests pass locally
```
(compose) (run-v)ed@piotr-mac:~/work/compose > docker --version
Docker version 1.12.2, build bb80604, experimental
(compose) (run-v)ed@piotr-mac:~/work/compose > py.test tests/ -k test_run_one_off -v
==================================================================== test session starts =====================================================================
platform darwin -- Python 2.7.10 -- py-1.4.31 -- pytest-2.7.2 -- /Users/ed/.pyenv/versions/2.7.10/envs/compose/bin/python2.7
rootdir: /Users/ed/work/compose, inifile: tox.ini
plugins: cov
collected 770 items

tests/acceptance/cli_test.py::CLITestCase::test_run_one_off_with_multiple_volumes PASSED
tests/acceptance/cli_test.py::CLITestCase::test_run_one_off_with_volume PASSED

======================================================== 768 tests deselected by '-ktest_run_one_off' ========================================================
========================================================== 2 passed, 768 deselected in 4.88 seconds ==========================================================
(compose) (run-v)ed@piotr-mac:~/work/compose >
```

**Comment by eddwardo** [comment]
@shin- when I execute tests (`tox -e py27`) locally, they all pass. What should be the steps to examine failures on jenkins? Stderr doesn't say much.

**Comment by dmitrieveu** [comment]
@eddwardo There's a file missing on test run - "Stderr: cat: can't open '/data/example.txt': No such file or directory"
https://jenkins.dockerproject.org/job/docker/job/compose/job/PR-4042/14/consoleFull

**Comment by eddwardo** [comment]
@dmitrieveu I am aware of that, to problem does not arise when running tests with tox locally.
`Docker version 1.13.0-rc4, build 88862e7`

**Comment by eddwardo** [comment]
Closing since, https://github.com/docker/compose/pull/4566 includes changes and fixes.

**Pull request closed without merging**
