### PR TITLE
Fix unicode in environment variables for python2

### LINKED ISSUE #1732: UnicodeDecodeError - for environment variable with non-ascii character value
```
$ docker-compose --version
docker-compose version: 1.3.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

$ cat docker-compose.yml 
code:
  image: busybox

$ docker-compose run -e FOO=bär code ls
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 342, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 225, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.container", line 38, in create
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 237, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.utils.utils", line 528, in create_container_config
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #1732

### CODE REVIEW

**Comment by mnowster** [comment]
LGTM

**Comment by omidraha** [comment]
I have the same issue for Unicode environment that set from the command line,

`$ export SITE_TITLE="مثال"`

Details:
```
Python 2.7.6
docker-compose version 1.8.0, build f3628c7
Docker version 1.12.3, build 6b644ec
Linux ubuntu 3.13.0-71-generic 
```

Traceback:
```
ERROR: for web  'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)
docker-compose returned -1

```

**Comment by aanand** [comment]
@omidraha How is the `SITE_TITLE` variable used in your application? Does it appear in `docker-compose.yml`?

**Comment by omidraha** [comment]
Yes, it defined on the  docker-compose.yml file, on the environment section of its service:
```
   environment:
    - SITE_TITLE
```

**Comment by omidraha** [comment]
I can reproduce the UnicodeDecodeError  error with this sample docker-compose.yml file:
```
version: '2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    environment:
    - SITE_TITLE
```

And next in the command line: 

```
$  export SITE_TITLE="مثال"
$  docker-compose up
```

Traceback:
```
Recreating deploy_nginx_1

ERROR: for nginx  'ascii' codec can't decode byte 0xd9 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd9 in position 0: ordinal not in range(128)
docker-compose returned -1
```
Packages Detail:
```
docker-compose version 1.8.0, build f3628c7
docker-machine version 0.9.0-rc1, build ed849a7
Python 2.7.12+
Linux debian 4.0.0-2-amd64 #1 SMP Debian 4.0.8-2 (2015-07-22) x86_64 GNU/Linux
```

**Comment by aanand** [comment]
@omidraha This issue was fixed in [Compose 1.9.0](https://github.com/docker/compose/releases/tag/1.9.0):

> Fixed a bug where unicode values in environment variables would sometimes raise a unicode exception when retrieved.

I've confirmed that using 1.9.0 does indeed fix your test case.

**Pull request merged**
