### PR TITLE
Bug fix - Ignore build context path validation when it is not necessary

### LINKED ISSUE #7359: Ignore missing build directory if not building images
Hello,
We have a single Compose file that should be used for both building images and starting services.
Images are built on one machine (manually or with CI/CD) and pushed to company's private Docker registry.

Compose file snippet:
```
version: "3.7"
services:
    standalone:
        build:
          context: build/wildfly/standalone
        ...
```
We want to be able to start the services with _docker-compose_ CLI on any other machine in our company, using the same Compose file, while pulling the previously built images from company's private Docker registry.

Those other machines don't have access to the build files, only the Compose file.
The problem is, when starting services with `up`, build path specified in the Compose file must exist, otherwise an error is thrown, even if building is not required or is explicitly turned off with `--no-build`.

```
docker-compose -f all-standalone-demo.yml up --no-build
ERROR: build path /home/vpriscan/...../build/wildfly/standalone either does not exist, is not accessible, or is not a valid URL.
```

I propose that missing build directory is ignored when services being started don't require building the images, or alternatively if `--no-build` flag is present.

Kind regards,
Vedran

### PR DESCRIPTION
**Pull request by bartier**
Resolves #7359 #7363

PR summary :
- If we specify `--no-build` then the build context path does not really need to exists. This allows scenarios where you want to 
 use docker-compose only to spin up services with a compose .yml file with already available images in docker.
- When using `docker-compose pull` the build context path is not checked anymore because we are only pulling images instead of building them.
- Tests to validate the scenarios described in #7359 and #7363.

### CODE REVIEW

**Comment by bartier** [comment]
The CI check returned the errors below:

```
[2020-06-27T18:11:01.185Z] + docker pull dockerbuildbot/compose:debian-cfc746081b1405b6a555c44ed7e03175119b537b
[2020-06-27T18:11:01.186Z] Error response from daemon: manifest for dockerbuildbot/compose:debian-cfc746081b1405b6a555c44ed7e03175119b537b not found: manifest unknown: manifest unknown
...
...

[2020-06-27T18:16:05.980Z] Put https://registry-1.docker.io/v2/dockerbuildbot/compose/blobs/uploads/015cbade-172e-4efb-b28e-5de45777cb18?_state=qUzeAqOvLOUR1lV0pPNsl8FtV-3eQv2hA8dnn9A2dvt7Ik5hbWUiOiJkb2NrZXJidWlsZGJvdC9jb21wb3NlIiwiVVVJRCI6IjAxNWNiYWRlLTE3MmUtNGVmYi1iMjhlLTVkZTQ1Nzc3Y2IxOCIsIk9mZnNldCI6MTI0MjksIlN0YXJ0ZWRBdCI6IjIwMjAtMDYtMjdUMTg6MTY6MDFaIn0%3D&digest=sha256%3Afad985599cc50e392d05b204b92097406320eb5d4ffb8c090e07efbb845dc393: EOF
```

I'm not sure how to fix this or how this relates to my PR. May anyone helps? :)

**Comment by zerozez** [comment]
It looks similar to #5780 but much simplified version and that exactly on what was pointed in https://github.com/docker/compose/pull/5780/files#r190403905 . Would be nice to see it merged!



> The CI check returned the errors below:
> 
> ```
> [2020-06-27T18:11:01.185Z] + docker pull dockerbuildbot/compose:debian-cfc746081b1405b6a555c44ed7e03175119b537b
> [2020-06-27T18:11:01.186Z] Error response from daemon: manifest for dockerbuildbot/compose:debian-cfc746081b1405b6a555c44ed7e03175119b537b not found: manifest unknown: manifest unknown
> ...

That's ok. It just cannot find the image in the registry, then builds it from the commit.

> [2020-06-27T18:16:05.980Z] Put https://registry-1.docker.io/v2/dockerbuildbot/compose/blobs/uploads/015cbade-172e-4efb-b28e-5de45777cb18?_state=qUzeAqOvLOUR1lV0pPNsl8FtV-3eQv2hA8dnn9A2dvt7Ik5hbWUiOiJkb2NrZXJidWlsZGJvdC9jb21wb3NlIiwiVVVJRCI6IjAxNWNiYWRlLTE3MmUtNGVmYi1iMjhlLTVkZTQ1Nzc3Y2IxOCIsIk9mZnNldCI6MTI0MjksIlN0YXJ0ZWRBdCI6IjIwMjAtMDYtMjdUMTg6MTY6MDFaIn0%3D&digest=sha256%3Afad985599cc50e392d05b204b92097406320eb5d4ffb8c090e07efbb845dc393: EOF
> ```

This is more interesting, since debian image has been pushed into registry, but not alpine. And, as I understand, related to https://docs.docker.com/registry/recipes/nginx.

**Comment by bartier** [comment]
I made a update in this branch to make the CI pass. May anybody do a code review, please? :) 

As @zerozez pointed out, I focused on doing a simplified approach to fix the behavior explained in #7359 because [PR 5780 - Code review](https://github.com/docker/compose/pull/5780/files#r190403905) had a discussion about it.

**Comment by mlewiarz** [comment]
Hi, will it also apply to docker-compose down?

**Comment by Vuwij** [comment]
Hi, can you make this also apply to docker-compose down?

**Comment by acz-a** [comment]
Please apply this to docker-compose restart.
I cannot restart active containers at the end devices this is nonesense.

**Pull request merged**
