### PR TITLE
Cherry pick v1.7.1 docs fixes

### PR DESCRIPTION
**Pull request by SvenDowideit**
get ready to publish docs fixes

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@aanand @bfirsh @shin- @thaJeztah could you please confirm that I've gotten all the docs you want published, and that i've not included something from v1.8?

also - please ignore the code change, that's come in with a (nice) PR that had docs to go with the code change :)

**Comment by SvenDowideit** [comment]
mmm, looking at the output of `git diff upstream/docs upstream/master`, I get the feeling that we can set the `docs` branch to == `master`

I'll wait for further info from @aanand / @dnephin  / @bfirsh

**Comment by dnephin** [comment]
No I don't think we should reset the `docs` branch. We update the docs branch with the release branch after every release. What's in the docs branch is always what has been released. 

If you need to get a code change into the docs branch before a release you can cherry pick it into the docs branch.a

**Comment by dnephin** [comment]
I've run that command, so the `docs` branch should be up to date with the release branch now.

**Comment by SvenDowideit** [comment]
@dnephin does that mean you guys don't have any docs updates you want published?

**Comment by dnephin** [comment]
Any docs update from 1.7.1 should now be in the `docs` branch.

**Comment by SvenDowideit** [comment]
@dnephin wow. so here are the docs that you guys haven't published.

please make sure none should be kept back, and when you merge, I'll get the out to your users.

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
These docs would have been published with the 1.8 release, but it doesn't hurt to push them out early I guess, since they don't refer to any new features.

LGTM

**Comment by londoncalling** [comment]
@SvenDowideit in terms of the changes to the sample apps I was hoping to get included, yes this LGTM (leaving it to @dnephin regarding other changes that he says are a bit early)

**Comment by SvenDowideit** [comment]
yay, merging so we can add it to today's release.

**Pull request merged**
